<?php

namespace Database\Seeders;

use App\Models\Asset;
use Illuminate\Database\Seeder;

class AssetSeeder extends Seeder
{
    public function run(): void
    {
        $assets = [

            // ═══════════════════════════════════════════════════════
            // VEHICLES
            // ═══════════════════════════════════════════════════════
            [
                'name'             => 'Bajaj Boxer 150cc',
                'slug'             => 'bajaj-boxer-150',
                'brand'            => 'Bajaj',
                'category'         => 'vehicle',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 80000,
                'monthly_income'   => 12000,
                'monthly_cost'     => 3500,
                'income_description' => 'Boda-boda fares (avg 15 trips/day)',
                'cost_description'   => 'Fuel, oil change, tyre wear',
                'appreciation_rate'  => -1.20,
                'volatility'         => 0.05,
                'risk_level'         => 2,
                'icon'             => '🏍️',
                'image_url'        => 'https://loremflickr.com/800/500/motorcycle,motorbike?lock=101',
                'description'      => 'The workhorse of Nairobi\'s last-mile economy. A Bajaj Boxer gets you from Rongai to CBD and back. Join the boda-boda revolution.',
                'flavor_text'      => '"Uchumi wa barabara" — the economy of the road starts here.',
                'educational_note' => 'Motorbikes depreciate fast but can generate more income per shilling invested than a car. Track fuel costs or profits vanish.',
                'creates_bill_slug'=> 'motorbike-insurance',
                'max_per_player'   => 3,
                'is_active'        => true,
            ],
            [
                'name'             => 'TVS Apache RTR 160',
                'slug'             => 'tvs-apache-160',
                'brand'            => 'TVS',
                'category'         => 'vehicle',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 115000,
                'monthly_income'   => 0,
                'monthly_cost'     => 4200,
                'income_description' => '',
                'cost_description'   => 'Fuel, insurance, servicing',
                'appreciation_rate'  => -1.50,
                'volatility'         => 0.03,
                'risk_level'         => 2,
                'icon'             => '🏍️',
                'image_url'        => 'https://loremflickr.com/800/500/motorcycle,sport?lock=102',
                'description'      => 'A sporty, reliable commuter. Great for the graduate who wants to skip the matatu queue and arrive fresh.',
                'flavor_text'      => 'Beat the Thika Road jam every single morning.',
                'educational_note' => 'Personal vehicles are liabilities — they cost money without generating income. Only buy if the time saved is worth the monthly cost.',
                'creates_bill_slug'=> 'motorbike-insurance',
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Honda Fit 2015',
                'slug'             => 'honda-fit-2015',
                'brand'            => 'Honda',
                'category'         => 'vehicle',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 720000,
                'monthly_income'   => 0,
                'monthly_cost'     => 14500,
                'income_description' => '',
                'cost_description'   => 'Fuel Ksh 8k, insurance Ksh 4k, servicing Ksh 2.5k',
                'appreciation_rate'  => -1.50,
                'volatility'         => 0.04,
                'risk_level'         => 2,
                'icon'             => '🚗',
                'image_url'        => 'https://loremflickr.com/800/500/honda,automobile?lock=103',
                'description'      => 'The beloved "Fit" — Kenya\'s most popular entry-level import. Automatic, fuel-efficient, fits everywhere including Westgate basement.',
                'flavor_text'      => 'The first car is always a Honda Fit. It\'s practically Kenyan law.',
                'educational_note' => 'Cars depreciate ~15% per year. That Ksh 720k car is worth Ksh 612k next year before you\'ve paid a shilling of insurance.',
                'creates_bill_slug'=> 'car-insurance',
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Nissan Note 2017',
                'slug'             => 'nissan-note-2017',
                'brand'            => 'Nissan',
                'category'         => 'vehicle',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 850000,
                'monthly_income'   => 0,
                'monthly_cost'     => 16000,
                'income_description' => '',
                'cost_description'   => 'Fuel, comprehensive insurance, servicing',
                'appreciation_rate'  => -1.40,
                'volatility'         => 0.04,
                'risk_level'         => 2,
                'icon'             => '🚗',
                'image_url'        => 'https://loremflickr.com/800/500/nissan,automobile?lock=104',
                'description'      => 'The Nissan Note — slightly bigger than a Fit, slightly bigger ego. Popular with young professionals in Kilimani and Kasarani.',
                'flavor_text'      => 'When you outgrow the Fit but the Prado is still a dream.',
                'educational_note' => 'Comprehensive car insurance is expensive but crucial. One accident without insurance can wipe out years of savings.',
                'creates_bill_slug'=> 'car-insurance',
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Toyota Fielder 2018',
                'slug'             => 'toyota-fielder-2018',
                'brand'            => 'Toyota',
                'category'         => 'vehicle',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 1650000,
                'monthly_income'   => 0,
                'monthly_cost'     => 22000,
                'income_description' => '',
                'cost_description'   => 'Fuel, insurance, servicing, parking',
                'appreciation_rate'  => -1.20,
                'volatility'         => 0.03,
                'risk_level'         => 2,
                'icon'             => '🚗',
                'image_url'        => 'https://loremflickr.com/800/500/toyota,stationwagon?lock=105',
                'description'      => 'The Toyota Fielder — "the car that settled Kenya." Spacious enough for family errands, tough enough for murram roads upcountry.',
                'flavor_text'      => 'Sunday drives to Karura Forest just hit different in a Fielder.',
                'educational_note' => 'Toyota holds value better than most brands. Resale value matters — always check the market before buying any car.',
                'creates_bill_slug'=> 'car-insurance',
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Matatu 14-Seater Stake',
                'slug'             => 'matatu-14-seater',
                'brand'            => 'Isuzu',
                'category'         => 'vehicle',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 1200000,
                'monthly_income'   => 45000,
                'monthly_cost'     => 28000,
                'income_description' => 'Daily fares minus driver/tout wages (owner share)',
                'cost_description'   => 'Fuel, NTSA inspection, insurance, maintenance, sacco fee',
                'appreciation_rate'  => -2.00,
                'volatility'         => 0.25,
                'risk_level'         => 4,
                'icon'             => '🚌',
                'image_url'        => 'https://loremflickr.com/800/500/minibus,transport?lock=106',
                'description'      => 'Own a piece of Nairobi\'s chaotic heartbeat. A Kayole–CBD matatu can earn you Ksh 45k/month — if it doesn\'t break down.',
                'flavor_text'      => '"Si wewe ndio owner?" — the power move at any stage.',
                'educational_note' => 'Matatus are high-risk, high-reward. Engine failure, police fines, and passenger surges can swing income dramatically.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 2,
                'is_active'        => true,
            ],
            [
                'name'             => 'Toyota Prado 2020',
                'slug'             => 'toyota-prado-2020',
                'brand'            => 'Toyota',
                'category'         => 'vehicle',
                'tier'             => 4,
                'age_group'        => '26+',
                'base_price'       => 7800000,
                'monthly_income'   => 0,
                'monthly_cost'     => 68000,
                'income_description' => '',
                'cost_description'   => 'Fuel (high consumption), comprehensive insurance, servicing, parking',
                'appreciation_rate'  => -0.80,
                'volatility'         => 0.05,
                'risk_level'         => 2,
                'icon'             => '🚙',
                'image_url'        => 'https://loremflickr.com/800/500/toyota,suv?lock=107',
                'description'      => 'The Prado says "I made it" without saying a word. Spotted outside every serious church in Karen and Runda every Sunday.',
                'flavor_text'      => 'You don\'t own a Prado. The Prado owns you — and your payslip.',
                'educational_note' => 'Luxury vehicles have lower depreciation rates but astronomical running costs. A Prado costs more per month than many salaries.',
                'creates_bill_slug'=> 'car-insurance',
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'BMW 3 Series 2021',
                'slug'             => 'bmw-3-series-2021',
                'brand'            => 'BMW',
                'category'         => 'vehicle',
                'tier'             => 4,
                'age_group'        => '26+',
                'base_price'       => 5800000,
                'monthly_income'   => 0,
                'monthly_cost'     => 55000,
                'income_description' => '',
                'cost_description'   => 'Premium fuel, BMW dealer service, insurance, import duties surcharge',
                'appreciation_rate'  => -1.80,
                'volatility'         => 0.06,
                'risk_level'         => 3,
                'icon'             => '🚘',
                'image_url'        => 'https://loremflickr.com/800/500/bmw,sedan?lock=108',
                'description'      => 'The Ultimate Driving Machine on Kenyan roads. Ngong Road on a clear morning. The Uhuru Highway at 2am. Pure.',
                'flavor_text'      => 'They see the badge, not the bank statement.',
                'educational_note' => 'European luxury cars depreciate faster than Japanese in Kenya and cost more to service. Prestige has a monthly price tag.',
                'creates_bill_slug'=> 'car-insurance',
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Porsche Cayenne 2022',
                'slug'             => 'porsche-cayenne-2022',
                'brand'            => 'Porsche',
                'category'         => 'vehicle',
                'tier'             => 5,
                'age_group'        => '26+',
                'base_price'       => 18500000,
                'monthly_income'   => 0,
                'monthly_cost'     => 145000,
                'income_description' => '',
                'cost_description'   => 'Porsche-dealer-only servicing, premium insurance, fuel, KRA excise duty buffer',
                'appreciation_rate'  => -1.00,
                'volatility'         => 0.05,
                'risk_level'         => 3,
                'icon'             => '🏎️',
                'image_url'        => 'https://loremflickr.com/800/500/porsche,luxury?lock=109',
                'description'      => 'Muthaiga. Karen. Gigiri. The Porsche Cayenne is not a car — it\'s a postcode. Ultra-premium. Ultra-expensive. Ultra-statement.',
                'flavor_text'      => '"Which one is yours?" — the valet already knows.',
                'educational_note' => 'At this wealth level, assets should be generating more income than this car costs. Is it worth the Ksh 145k/month?',
                'creates_bill_slug'=> 'car-insurance',
                'max_per_player'   => 1,
                'is_active'        => true,
            ],

            // ═══════════════════════════════════════════════════════
            // PROPERTY
            // ═══════════════════════════════════════════════════════
            [
                'name'             => '1/8 Acre Plot — Mavoko',
                'slug'             => 'plot-mavoko',
                'brand'            => null,
                'category'         => 'property',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 180000,
                'monthly_income'   => 0,
                'monthly_cost'     => 500,
                'income_description' => '',
                'cost_description'   => 'Land rates, security levy',
                'appreciation_rate'  => 0.80,
                'volatility'         => 0.08,
                'risk_level'         => 2,
                'icon'             => '🌍',
                'image_url'        => 'https://loremflickr.com/800/500/land,landscape?lock=110',
                'description'      => 'Raw land in Mavoko — on the Mombasa Road corridor, minutes from Konza Technopolis. Buy now, sell later, or build later.',
                'flavor_text'      => 'Every millionaire in Nairobi started with a plot.',
                'educational_note' => 'Land is one of the few assets that never wears out. In a growing city, patience turns Ksh 180k into Ksh 1M.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 5,
                'is_active'        => true,
            ],
            [
                'name'             => '1/4 Acre Plot — Ruiru',
                'slug'             => 'plot-ruiru',
                'brand'            => null,
                'category'         => 'property',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 380000,
                'monthly_income'   => 0,
                'monthly_cost'     => 800,
                'income_description' => '',
                'cost_description'   => 'Land rates, security fence maintenance',
                'appreciation_rate'  => 0.90,
                'volatility'         => 0.07,
                'risk_level'         => 2,
                'icon'             => '🌍',
                'image_url'        => 'https://loremflickr.com/800/500/land,green?lock=111',
                'description'      => 'A quarter acre in Ruiru — serviced, with road access. The Northern Bypass has made this corridor explode. Buy before the next project announcement.',
                'flavor_text'      => '"Ruiru ni ya watu wa akili" — the wise ones moved early.',
                'educational_note' => 'Infrastructure projects (bypass, expressway) dramatically increase nearby land values. Research what\'s planned before you buy.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 3,
                'is_active'        => true,
            ],
            [
                'name'             => 'Studio Apartment — Ruaka',
                'slug'             => 'studio-ruaka',
                'brand'            => null,
                'category'         => 'property',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 2850000,
                'monthly_income'   => 18000,
                'monthly_cost'     => 4500,
                'income_description' => 'Monthly rent from tenant',
                'cost_description'   => 'Service charge, water bill, annual maintenance reserve',
                'appreciation_rate'  => 0.50,
                'volatility'         => 0.06,
                'risk_level'         => 2,
                'icon'             => '🏠',
                'image_url'        => 'https://loremflickr.com/800/500/apartment,interior?lock=112',
                'description'      => 'A studio apartment in Ruaka — the tech-worker suburb. Fully finished, near Ndenderu. Occupied the day you list it.',
                'flavor_text'      => '"Tenant amenia" — the most satisfying SMS every 5th of the month.',
                'educational_note' => 'Rental yield = annual rent / property price. This studio yields ~7.5% — better than a bank FD.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 3,
                'is_active'        => true,
            ],
            [
                'name'             => 'Bedsitter — Umoja',
                'slug'             => 'bedsitter-umoja',
                'brand'            => null,
                'category'         => 'property',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 950000,
                'monthly_income'   => 8500,
                'monthly_cost'     => 1500,
                'income_description' => 'Monthly rent from tenant',
                'cost_description'   => 'Maintenance reserve, caretaker fee',
                'appreciation_rate'  => 0.40,
                'volatility'         => 0.08,
                'risk_level'         => 2,
                'icon'             => '🏠',
                'image_url'        => 'https://loremflickr.com/800/500/apartment,room?lock=113',
                'description'      => 'A solid bedsitter in Umoja — one of Nairobi\'s most stable rental markets. Low vacancy. Steady income. Simple management.',
                'flavor_text'      => 'Sometimes the unglamorous investment wins the race.',
                'educational_note' => 'Lower-income rentals often have more stable occupancy than premium properties. Diversify across tiers.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 5,
                'is_active'        => true,
            ],
            [
                'name'             => '2BR Apartment — Kilimani',
                'slug'             => '2br-kilimani',
                'brand'            => null,
                'category'         => 'property',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 9800000,
                'monthly_income'   => 65000,
                'monthly_cost'     => 12000,
                'income_description' => 'Expatriate / diplomat tenant at premium rate',
                'cost_description'   => 'Service charge, water, maintenance fund, property manager 5%',
                'appreciation_rate'  => 0.60,
                'volatility'         => 0.05,
                'risk_level'         => 2,
                'icon'             => '🏢',
                'image_url'        => 'https://loremflickr.com/800/500/apartment,luxury?lock=114',
                'description'      => 'Premium 2BR in Kilimani — finished to expat standard with backup power and water. Demand outstrips supply. Your AIRBNB option too.',
                'flavor_text'      => 'Kilimani rents are priced in USD. Think about that.',
                'educational_note' => 'Premium property can command USD-pegged rents from expatriates, protecting against Kenyan shilling depreciation.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 2,
                'is_active'        => true,
            ],
            [
                'name'             => 'Townhouse — Syokimau',
                'slug'             => 'townhouse-syokimau',
                'brand'            => null,
                'category'         => 'property',
                'tier'             => 4,
                'age_group'        => '26+',
                'base_price'       => 18500000,
                'monthly_income'   => 0,
                'monthly_cost'     => 8000,
                'income_description' => '',
                'cost_description'   => 'Service charge, security, maintenance',
                'appreciation_rate'  => 0.70,
                'volatility'         => 0.05,
                'risk_level'         => 1,
                'icon'             => '🏡',
                'image_url'        => 'https://loremflickr.com/800/500/townhouse,house?lock=115',
                'description'      => 'A 4BR townhouse in Syokimau — gated community, SGR station 5 minutes away. The forever home. Or your highest-value investment.',
                'flavor_text'      => 'The SGR brought Mombasa Road to Nairobi CBD in 4 minutes. Syokimau is now CBD-adjacent.',
                'educational_note' => 'A primary residence is not a pure investment — it eliminates your rent expense while also being the most expensive purchase of your life.',
                'creates_bill_slug'=> 'mortgage-repayment',
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Commercial Stall — Gikomba',
                'slug'             => 'stall-gikomba',
                'brand'            => null,
                'category'         => 'property',
                'tier'             => 2,
                'age_group'        => '26+',
                'base_price'       => 650000,
                'monthly_income'   => 22000,
                'monthly_cost'     => 5000,
                'income_description' => 'Sub-tenant operates mitumba stall; fixed monthly rent',
                'cost_description'   => 'Nairobi County levy, structure maintenance, security',
                'appreciation_rate'  => 0.30,
                'volatility'         => 0.12,
                'risk_level'         => 3,
                'icon'             => '🏪',
                'image_url'        => 'https://loremflickr.com/800/500/market,stall?lock=116',
                'description'      => 'A commercial stall in Gikomba market — Africa\'s largest second-hand clothing market. Your tenant sells mitumba, you collect rent.',
                'flavor_text'      => 'While Nairobi sleeps, Gikomba is already counting tomorrow\'s stock.',
                'educational_note' => 'Commercial property yields more than residential but has higher vacancy risk. One slow season and tenants struggle to pay.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 3,
                'is_active'        => true,
            ],

            // ═══════════════════════════════════════════════════════
            // BUSINESS
            // ═══════════════════════════════════════════════════════
            [
                'name'             => 'Mama Mboga Kiosk',
                'slug'             => 'mama-mboga-kiosk',
                'brand'            => null,
                'category'         => 'business',
                'tier'             => 1,
                'age_group'        => '13-17',
                'base_price'       => 15000,
                'monthly_income'   => 8000,
                'monthly_cost'     => 4500,
                'income_description' => 'Sales of vegetables, tomatoes, onions, sukuma wiki',
                'cost_description'   => 'Daily stock replenishment at Wakulima Market, display rent',
                'appreciation_rate'  => 0.00,
                'volatility'         => 0.20,
                'risk_level'         => 3,
                'icon'             => '🥬',
                'image_url'        => 'https://loremflickr.com/800/500/vegetables,market?lock=117',
                'description'      => 'The OG Kenyan business. A vegetable kiosk feeds the neighbourhood and funds school fees. Small capital, daily cash flow, big hustle.',
                'flavor_text'      => '"Mama mboga" built this economy. Don\'t let anyone tell you otherwise.',
                'educational_note' => 'Cash-flow businesses require daily management. Stock spoils if unsold — inventory management is a real skill.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 3,
                'is_active'        => true,
            ],
            [
                'name'             => 'Cyber Café — 5 Computers',
                'slug'             => 'cyber-cafe-5pc',
                'brand'            => null,
                'category'         => 'business',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 75000,
                'monthly_income'   => 18000,
                'monthly_cost'     => 9500,
                'income_description' => 'Printing, scanning, browsing, M-Pesa, eCitizen services',
                'cost_description'   => 'Rent, electricity, internet (Safaricom SME), UPS maintenance',
                'appreciation_rate'  => -0.50,
                'volatility'         => 0.15,
                'risk_level'         => 3,
                'icon'             => '🖥️',
                'image_url'        => 'https://loremflickr.com/800/500/computer,cafe?lock=118',
                'description'      => 'Still printing, still winning. The cyber café in Kayole or Githurai is the unofficial government services agent, exam preparation hub, and printing empire.',
                'flavor_text'      => '"Print yangu ni haraka, mimi na hurry" — every customer, always.',
                'educational_note' => 'Even "dying" industries stay profitable in underserved markets. Understand your customer before assuming an industry is dead.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 2,
                'is_active'        => true,
            ],
            [
                'name'             => 'M-PESA Agent Float',
                'slug'             => 'mpesa-agent-float',
                'brand'            => 'Safaricom',
                'category'         => 'business',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 280000,
                'monthly_income'   => 35000,
                'monthly_cost'     => 8000,
                'income_description' => 'Commission on deposits, withdrawals, business pay, Fuliza collections',
                'cost_description'   => 'Shop rent, staff wages, float interest cost, security',
                'appreciation_rate'  => 0.10,
                'volatility'         => 0.10,
                'risk_level'         => 2,
                'icon'             => '📱',
                'image_url'        => 'https://loremflickr.com/800/500/mobile,payment?lock=119',
                'description'      => 'An M-PESA agent till with a healthy float. Commission on every transaction. Kenya processes billions through these tills daily.',
                'flavor_text'      => '"Wewe ni agent?" is the most popular question in any market.',
                'educational_note' => 'Float management is critical. Locking float in overdraft kills income. Keep your float liquid and your turnover high.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 3,
                'is_active'        => true,
            ],
            [
                'name'             => 'Salon & Barber Shop',
                'slug'             => 'salon-barber',
                'brand'            => null,
                'category'         => 'business',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 180000,
                'monthly_income'   => 42000,
                'monthly_cost'     => 22000,
                'income_description' => 'Haircuts, braiding, treatments, beard trims',
                'cost_description'   => 'Rent, staff wages, products (relaxers, shampoo), electricity',
                'appreciation_rate'  => 0.00,
                'volatility'         => 0.12,
                'risk_level'         => 3,
                'icon'             => '💈',
                'image_url'        => 'https://loremflickr.com/800/500/salon,beauty?lock=120',
                'description'      => 'A busy salon in a residential estate — Rongai, Kasarani, or Thika Road. Staff runs it. You collect at month end.',
                'flavor_text'      => 'Hair is recession-proof. People cut it even when broke.',
                'educational_note' => 'Service businesses are people-dependent. Losing a skilled stylist can cost you half your customers overnight.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 2,
                'is_active'        => true,
            ],
            [
                'name'             => 'Fuel Station — 2 Pumps',
                'slug'             => 'fuel-station-2pump',
                'brand'            => null,
                'category'         => 'business',
                'tier'             => 4,
                'age_group'        => '26+',
                'base_price'       => 2800000,
                'monthly_income'   => 180000,
                'monthly_cost'     => 120000,
                'income_description' => 'Fuel margin × daily litres pumped, lubricants, car wash',
                'cost_description'   => 'Fuel procurement, staff (3 attendants), EPRA licence, security',
                'appreciation_rate'  => 0.20,
                'volatility'         => 0.18,
                'risk_level'         => 4,
                'icon'             => '⛽',
                'image_url'        => 'https://loremflickr.com/800/500/petrolstation,fuel?lock=121',
                'description'      => 'A two-pump petrol station on a busy road. High turnover, tight margins, immense cash flow. The dream and the headache.',
                'flavor_text'      => '"Fuel imefika" — three words that change Kenyan mornings.',
                'educational_note' => 'Fuel stations have high revenue but thin margins per litre. Volume is everything. Location determines survival.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Tech Startup Stake (5%)',
                'slug'             => 'tech-startup-stake',
                'brand'            => null,
                'category'         => 'business',
                'tier'             => 4,
                'age_group'        => '26+',
                'base_price'       => 1500000,
                'monthly_income'   => 0,
                'monthly_cost'     => 0,
                'income_description' => 'No dividends until exit (pre-revenue startup)',
                'cost_description'   => '',
                'appreciation_rate'  => 2.00,
                'volatility'         => 0.40,
                'risk_level'         => 5,
                'icon'             => '🚀',
                'image_url'        => 'https://loremflickr.com/800/500/technology,startup?lock=122',
                'description'      => 'A 5% equity stake in a Nairobi-based fintech — B2B payments, agri-fintech, or healthtech. No dividends now. Massive upside (or total wipeout).',
                'flavor_text'      => '"We\'re the Mpesa of X" — the most common pitch. Sometimes it\'s true.',
                'educational_note' => 'Startup equity is illiquid and high-risk. Most startups fail. Diversification is critical — never put everything here.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 3,
                'is_active'        => true,
            ],

            // ═══════════════════════════════════════════════════════
            // FIXED INCOME (own category — MMF, T-Bills, T-Bonds behave
            // like actual fixed-income instruments, not appreciating assets)
            // ═══════════════════════════════════════════════════════
            [
                'name'             => 'Money Market Fund',
                'slug'             => 'money-market-fund',
                'brand'            => 'CIC / Sanlam',
                'category'         => 'fixed_income',
                'tier'             => 1,
                'age_group'        => 'all',
                'base_price'       => 5000,
                'monthly_income'   => 46,
                'monthly_cost'     => 0,
                'income_description' => '~11% p.a. (net of fund fees), paid monthly',
                'cost_description'   => '',
                'appreciation_rate'  => 0,
                'volatility'         => 0,
                'risk_level'         => 1,
                'maturity_ticks'     => null,
                'locked'             => false,
                'early_exit_penalty_pct' => 0,
                'maturity_bonus_pct' => 0,
                'icon'             => '💰',
                'image_url'        => 'https://loremflickr.com/800/500/finance,money?lock=123',
                'description'      => 'The smartest first investment. A Money Market Fund pools your cash with thousands of others and lends to banks overnight. Safe, liquid, growing.',
                'flavor_text'      => '"Accumulate quietly" — the MMF investor motto.',
                'educational_note' => 'MMFs beat bank savings accounts by 4-6x while keeping your money accessible any time — no lock-in, unlike a T-Bill or T-Bond.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'Treasury Bills (91-Day)',
                'slug'             => 'treasury-bills-91',
                'brand'            => 'CBK',
                'category'         => 'fixed_income',
                'tier'             => 1,
                'age_group'        => 'all',
                'base_price'       => 50000,
                'monthly_income'   => 0,
                'monthly_cost'     => 0,
                'income_description' => 'No monthly payout — bought at a discount, redeemed at face value in one lump sum on maturity',
                'cost_description'   => '',
                'appreciation_rate'  => 0,
                'volatility'         => 0,
                'risk_level'         => 1,
                'income_period_ticks'=> 91,
                'maturity_ticks'     => 91,
                'locked'             => true,
                'early_exit_penalty_pct' => 0,
                'maturity_bonus_pct' => 4.31,
                'icon'             => '🏛️',
                'image_url'        => 'https://loremflickr.com/800/500/finance,government?lock=124',
                'description'      => 'Lend to the Kenyan government for 91 days at a guaranteed rate. Zero default risk. Locked until maturity — the highest risk-free rate in the region.',
                'flavor_text'      => '"Government imekubali" — safer than any bank.',
                'educational_note' => 'T-bills are considered risk-free (the government prints the currency). You buy at a discount and get the full face value back 91 days later — the discount IS your return.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 20,
                'is_active'        => true,
            ],
            [
                'name'             => 'Treasury Bonds (5-Year)',
                'slug'             => 'treasury-bonds-5yr',
                'brand'            => 'CBK',
                'category'         => 'fixed_income',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 500000,
                'monthly_income'   => 45000,
                'monthly_cost'     => 0,
                'income_description' => '~18% p.a. coupon of Ksh 45,000, paid every 6 months',
                'cost_description'   => '',
                'appreciation_rate'  => 0,
                'volatility'         => 0,
                'risk_level'         => 1,
                'income_period_ticks'=> 182,
                'maturity_ticks'     => 1825,
                'locked'             => false,
                'early_exit_penalty_pct' => 20,
                'maturity_bonus_pct' => 0,
                'icon'             => '📜',
                'image_url'        => 'https://loremflickr.com/800/500/bonds,documents?lock=125',
                'description'      => 'A 5-year government bond. Your money is locked for 5 years, but the government pays you a coupon every 6 months. Selling early forfeits 20% to a haircut — patient money wins.',
                'flavor_text'      => '"Hatua moja, thamani kubwa." — One step, great value.',
                'educational_note' => 'Bonds pay a fixed coupon on schedule no matter what markets do — the trade-off is your capital is tied up for the full term, and cashing out early costs you.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 5,
                'is_active'        => true,
            ],
            [
                'name'             => 'Safaricom Shares (1000)',
                'slug'             => 'safaricom-shares-1000',
                'brand'            => 'Safaricom',
                'category'         => 'investment',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 30000,
                'monthly_income'   => 250,
                'monthly_cost'     => 0,
                'income_description' => 'Dividend yield ~10% p.a. (approx Ksh 3/share/year)',
                'cost_description'   => '',
                'appreciation_rate'  => 0.40,
                'volatility'         => 0.12,
                'risk_level'         => 3,
                'icon'             => '📈',
                'image_url'        => 'https://loremflickr.com/800/500/stockmarket,trading?lock=126',
                'description'      => '1,000 Safaricom shares on the NSE. Kenya\'s most-traded company. M-PESA, mobile data, financial services — Saf is everywhere.',
                'flavor_text'      => 'When every Kenyan uses your product, the dividend cheque finds you.',
                'educational_note' => 'Owning shares means owning a piece of the company. Share price reflects market sentiment, but dividends reflect real profit.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'SACCO Share Capital',
                'slug'             => 'sacco-share-capital',
                'brand'            => null,
                'category'         => 'investment',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 12000,
                'monthly_income'   => 100,
                'monthly_cost'     => 0,
                'income_description' => 'Annual dividend on shares (~10% p.a.), shown as monthly',
                'cost_description'   => '',
                'appreciation_rate'  => 0.80,
                'volatility'         => 0.02,
                'risk_level'         => 1,
                'icon'             => '🤝',
                'image_url'        => 'https://loremflickr.com/800/500/community,finance?lock=127',
                'description'      => 'Share capital in a registered SACCO — Stima, Mwalimu, Unaitas. Your shares earn dividends AND unlock access to 3× loans at low rates.',
                'flavor_text'      => '"Umoja ni nguvu, utengano ni udhaifu." — Unity is strength.',
                'educational_note' => 'SACCOs are cooperative banks owned by members. They consistently outperform commercial banks on loan rates and savings dividends.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'NSE REIT Unit (100)',
                'slug'             => 'nse-reit-100',
                'brand'            => 'ILAM Fahari',
                'category'         => 'investment',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 100000,
                'monthly_income'   => 700,
                'monthly_cost'     => 0,
                'income_description' => 'Quarterly distribution (rent income from commercial properties)',
                'cost_description'   => '',
                'appreciation_rate'  => 0.30,
                'volatility'         => 0.08,
                'risk_level'         => 2,
                'icon'             => '🏗️',
                'image_url'        => 'https://loremflickr.com/800/500/realestate,office?lock=128',
                'description'      => 'Own a slice of commercial real estate without buying a building. The ILAM Fahari I-REIT on the NSE holds offices and retail space across Nairobi.',
                'flavor_text'      => 'Real estate money without the tenant calls at midnight.',
                'educational_note' => 'REITs must pay 80% of income as dividends. Low maintenance, diversified exposure — real estate for the rest of us.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'Private Equity Fund Unit',
                'slug'             => 'private-equity-unit',
                'brand'            => 'Helios / Actis',
                'category'         => 'investment',
                'tier'             => 5,
                'age_group'        => '26+',
                'base_price'       => 2000000,
                'monthly_income'   => 0,
                'monthly_cost'     => 0,
                'income_description' => 'No distributions until fund exit (5-7 year horizon)',
                'cost_description'   => '',
                'appreciation_rate'  => 2.50,
                'volatility'         => 0.25,
                'risk_level'         => 5,
                'icon'             => '💎',
                'image_url'        => 'https://loremflickr.com/800/500/investment,wealth?lock=129',
                'description'      => 'A unit in a pan-African private equity fund. Illiquid, long horizon, high minimum. But returns beat every listed asset class over 7 years.',
                'flavor_text'      => 'Old money doesn\'t wait 3 months for quarterly reports. It waits 7 years for the exit.',
                'educational_note' => 'Private equity is illiquid — you cannot sell until the fund exits. Only invest money you will not need for 5-7 years.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 3,
                'is_active'        => true,
            ],

            // ═══════════════════════════════════════════════════════
            // GADGETS (for younger players)
            // ═══════════════════════════════════════════════════════
            [
                'name'             => 'Smartphone — Tecno Spark',
                'slug'             => 'tecno-spark',
                'brand'            => 'Tecno',
                'category'         => 'gadget',
                'tier'             => 1,
                'age_group'        => '13-17',
                'base_price'       => 12000,
                'monthly_income'   => 0,
                'monthly_cost'     => 500,
                'income_description' => '',
                'cost_description'   => 'Data bundles, charging, accessories',
                'appreciation_rate'  => -5.00,
                'volatility'         => 0.05,
                'risk_level'         => 1,
                'icon'             => '📱',
                'image_url'        => 'https://loremflickr.com/800/500/smartphone,mobile?lock=130',
                'description'      => 'The Tecno Spark. Good camera, good battery, affordable. The phone that got most Kenyan students online for the first time.',
                'flavor_text'      => 'First phone. First step into the digital economy.',
                'educational_note' => 'Phones lose value extremely fast — over 50% in the first year. They are tools, not investments. Use them to earn, not to show.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Laptop — HP 250 G9',
                'slug'             => 'laptop-hp-250',
                'brand'            => 'HP',
                'category'         => 'gadget',
                'tier'             => 2,
                'age_group'        => '13-17',
                'base_price'       => 55000,
                'monthly_income'   => 3500,
                'monthly_cost'     => 800,
                'income_description' => 'Freelance graphic design, content creation, online tutoring',
                'cost_description'   => 'Data bundles, electricity, antivirus',
                'appreciation_rate'  => -4.00,
                'volatility'         => 0.05,
                'risk_level'         => 1,
                'icon'             => '💻',
                'image_url'        => 'https://loremflickr.com/800/500/laptop,computer?lock=131',
                'description'      => 'An HP 250 — the campus workhorse. Essays, code, design, video editing. In the right hands, this pays for itself in 3 months.',
                'flavor_text'      => 'Every freelancer started somewhere. Start here.',
                'educational_note' => 'A laptop is a depreciating asset BUT can be used to earn income. The key question is whether it generates more than it costs.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],

            // ═══════════════════════════════════════════════════════
            // MORE VEHICLES
            // ═══════════════════════════════════════════════════════
            [
                'name'             => 'Piaggio Tuk-Tuk',
                'slug'             => 'piaggio-tuktuk',
                'brand'            => 'Piaggio',
                'category'         => 'vehicle',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 380000,
                'monthly_income'   => 22000,
                'monthly_cost'     => 7000,
                'income_description' => 'Short-hop passenger fares in Mombasa, Kisumu, or estate roads',
                'cost_description'   => 'Fuel, insurance, minor repairs',
                'appreciation_rate'  => -1.80,
                'volatility'         => 0.10,
                'risk_level'         => 3,
                'icon'             => '🛺',
                'image_url'        => 'https://loremflickr.com/800/500/tuktuk,rickshaw?lock=132',
                'description'      => 'A tuk-tuk for the coast or estate short-hop trade. Cheaper to buy and run than a boda, and passengers don\'t get rained on.',
                'flavor_text'      => '"Bao tatu, twende!" — three seats, always full at rush hour.',
                'educational_note' => 'Niche vehicles do well in niche markets. A tuk-tuk struggles on Nairobi\'s highways but thrives on Mombasa\'s flat estate roads.',
                'creates_bill_slug'=> 'motorbike-insurance',
                'max_per_player'   => 2,
                'is_active'        => true,
            ],
            [
                'name'             => 'Toyota Vitz 2016',
                'slug'             => 'toyota-vitz-2016',
                'brand'            => 'Toyota',
                'category'         => 'vehicle',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 620000,
                'monthly_income'   => 0,
                'monthly_cost'     => 12500,
                'income_description' => '',
                'cost_description'   => 'Fuel, insurance, servicing',
                'appreciation_rate'  => -1.60,
                'volatility'         => 0.04,
                'risk_level'         => 2,
                'icon'             => '🚗',
                'image_url'        => 'https://loremflickr.com/800/500/toyota,hatchback?lock=133',
                'description'      => 'The cheaper cousin of the Fit. A Vitz gets a first-time car owner off the matatu without breaking the bank.',
                'flavor_text'      => 'Small car, small fuel bill, big freedom.',
                'educational_note' => 'The cheapest car in a class still carries full insurance and servicing costs — budget for the whole picture, not just the price tag.',
                'creates_bill_slug'=> 'car-insurance',
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Isuzu D-Max Pickup',
                'slug'             => 'isuzu-dmax-pickup',
                'brand'            => 'Isuzu',
                'category'         => 'vehicle',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 3200000,
                'monthly_income'   => 55000,
                'monthly_cost'     => 32000,
                'income_description' => 'Hardware/produce delivery contracts, per-trip hire',
                'cost_description'   => 'Diesel, insurance, servicing, driver wage',
                'appreciation_rate'  => -1.00,
                'volatility'         => 0.15,
                'risk_level'         => 3,
                'icon'             => '🛻',
                'image_url'        => 'https://loremflickr.com/800/500/pickup,truck?lock=134',
                'description'      => 'A workhorse pickup for hire — moving cement, produce, furniture. Every hardware store and farm needs one on speed dial.',
                'flavor_text'      => '"Tuma D-Max" — the Nairobi logistics answer to almost anything.',
                'educational_note' => 'Commercial vehicles earn more than personal ones because they generate income on every trip — the vehicle itself becomes the business.',
                'creates_bill_slug'=> 'car-insurance',
                'max_per_player'   => 2,
                'is_active'        => true,
            ],

            // ═══════════════════════════════════════════════════════
            // MORE PROPERTY
            // ═══════════════════════════════════════════════════════
            [
                'name'             => 'Warehouse Unit — Industrial Area',
                'slug'             => 'warehouse-industrial-area',
                'brand'            => null,
                'category'         => 'property',
                'tier'             => 4,
                'age_group'        => '26+',
                'base_price'       => 22000000,
                'monthly_income'   => 140000,
                'monthly_cost'     => 15000,
                'income_description' => 'Logistics/distribution tenant on a fixed lease',
                'cost_description'   => 'Security, structural maintenance, county levy',
                'appreciation_rate'  => 0.50,
                'volatility'         => 0.06,
                'risk_level'         => 2,
                'icon'             => '🏭',
                'image_url'        => 'https://loremflickr.com/800/500/warehouse,industrial?lock=135',
                'description'      => 'A warehouse unit in Nairobi\'s Industrial Area — where every import, export, and e-commerce order in the city passes through.',
                'flavor_text'      => 'E-commerce needs somewhere to store the boxes. This is that somewhere.',
                'educational_note' => 'Industrial property yields depend on Kenya\'s trade volumes — a slower economy means slower warehouse demand.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Airbnb Unit — Westlands',
                'slug'             => 'airbnb-westlands',
                'brand'            => null,
                'category'         => 'property',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 6200000,
                'monthly_income'   => 48000,
                'monthly_cost'     => 14000,
                'income_description' => 'Short-stay bookings — rate varies with occupancy',
                'cost_description'   => 'Cleaning, management commission, utilities, Airbnb service fee',
                'appreciation_rate'  => 0.55,
                'volatility'         => 0.22,
                'risk_level'         => 3,
                'icon'             => '🛎️',
                'image_url'        => 'https://loremflickr.com/800/500/airbnb,apartment?lock=136',
                'description'      => 'A furnished unit in Westlands run as a short-stay rental. Great returns in high season, empty weeks when travel slows down.',
                'flavor_text'      => 'Five-star reviews pay the mortgage. One bad month tests your nerves.',
                'educational_note' => 'Short-stay rental income is far more volatile than a fixed-tenant lease — higher potential yield, but occupancy risk is real.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 2,
                'is_active'        => true,
            ],

            // ═══════════════════════════════════════════════════════
            // MORE BUSINESS
            // ═══════════════════════════════════════════════════════
            [
                'name'             => 'Poultry Farm — 500 Layers',
                'slug'             => 'poultry-farm-500',
                'brand'            => null,
                'category'         => 'business',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 320000,
                'monthly_income'   => 45000,
                'monthly_cost'     => 26000,
                'income_description' => 'Egg sales (trays) plus periodic culled-bird sales',
                'cost_description'   => 'Feed, vaccines, casual labour',
                'appreciation_rate'  => 0.00,
                'volatility'         => 0.18,
                'risk_level'         => 3,
                'icon'             => '🐔',
                'image_url'        => 'https://loremflickr.com/800/500/chicken,farm?lock=137',
                'description'      => 'A 500-layer egg farm on the outskirts of town. Steady daily egg trays, sold to shops and hotels. Disease outbreak is the one nightmare.',
                'flavor_text'      => 'Every tray of eggs is a tiny, reliable paycheque.',
                'educational_note' => 'Feed costs are ~70% of poultry expenses. A feed price spike can wipe out margins overnight — hedge by buying in bulk when prices dip.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 3,
                'is_active'        => true,
            ],
            [
                'name'             => 'Mitumba Boutique',
                'slug'             => 'mitumba-boutique',
                'brand'            => null,
                'category'         => 'business',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 95000,
                'monthly_income'   => 28000,
                'monthly_cost'     => 14000,
                'income_description' => 'Curated second-hand clothing resale at a markup',
                'cost_description'   => 'Bale purchases, shop rent, steaming/pressing supplies',
                'appreciation_rate'  => 0.00,
                'volatility'         => 0.16,
                'risk_level'         => 3,
                'icon'             => '👗',
                'image_url'        => 'https://loremflickr.com/800/500/clothing,boutique?lock=138',
                'description'      => 'A curated mitumba boutique — sorted, steamed, and styled second-hand fashion for the social-media generation. Higher margin than raw bales.',
                'flavor_text'      => 'One person\'s donated jacket is another\'s "thrifted fit."',
                'educational_note' => 'Value-adding a commodity (sorting, styling, marketing) is how small traders escape thin margins. Presentation sells at 3x the bale price.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 3,
                'is_active'        => true,
            ],
            [
                'name'             => 'Car Wash & Detailing',
                'slug'             => 'car-wash-detailing',
                'brand'            => null,
                'category'         => 'business',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 220000,
                'monthly_income'   => 38000,
                'monthly_cost'     => 19000,
                'income_description' => 'Wash, vacuum, and detailing packages',
                'cost_description'   => 'Water, soap/chemicals, staff wages, water bowser in dry season',
                'appreciation_rate'  => 0.00,
                'volatility'         => 0.14,
                'risk_level'         => 3,
                'icon'             => '🚿',
                'image_url'        => 'https://loremflickr.com/800/500/carwash,cleaning?lock=139',
                'description'      => 'A busy roadside car wash. Every commuter with a car needs one weekly. Location on a main road is everything.',
                'flavor_text'      => '"Tunaosha mpaka ing\'ae" — we wash until it shines.',
                'educational_note' => 'Water-dependent businesses are exposed to county water-rationing risk — a backup borehole or tank is a real cost of doing business.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 2,
                'is_active'        => true,
            ],
            [
                'name'             => 'Hardware & Building Supplies Shop',
                'slug'             => 'hardware-shop',
                'brand'            => null,
                'category'         => 'business',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 950000,
                'monthly_income'   => 85000,
                'monthly_cost'     => 48000,
                'income_description' => 'Cement, iron sheets, fittings, paint — construction season peaks',
                'cost_description'   => 'Stock restocking, rent, staff wages, delivery truck fuel',
                'appreciation_rate'  => 0.10,
                'volatility'         => 0.14,
                'risk_level'         => 3,
                'icon'             => '🔧',
                'image_url'        => 'https://loremflickr.com/800/500/hardware,tools?lock=140',
                'description'      => 'A neighbourhood hardware shop — cement, timber, fittings, paint. Every new building in the estate walks through this door first.',
                'flavor_text'      => 'When Kenya builds, the hardware shop wins.',
                'educational_note' => 'Hardware sales track the construction cycle — interest rate hikes that slow building directly slow this business too.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 2,
                'is_active'        => true,
            ],

            // ═══════════════════════════════════════════════════════
            // MORE INVESTMENTS
            // ═══════════════════════════════════════════════════════
            [
                'name'             => 'Unit Trust Equity Fund',
                'slug'             => 'unit-trust-equity-fund',
                'brand'            => 'Old Mutual / Britam',
                'category'         => 'investment',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 20000,
                'monthly_income'   => 0,
                'monthly_cost'     => 0,
                'income_description' => 'Capital gains on NSE-listed equities (no fixed payout)',
                'cost_description'   => '',
                'appreciation_rate'  => 1.00,
                'volatility'         => 0.10,
                'risk_level'         => 3,
                'icon'             => '📊',
                'image_url'        => 'https://loremflickr.com/800/500/stocks,graph?lock=141',
                'description'      => 'A professionally managed fund holding a basket of NSE-listed companies. Diversified — one bad stock doesn\'t sink you.',
                'flavor_text'      => 'Don\'t pick one stock. Let a fund manager pick fifty.',
                'educational_note' => 'Diversification reduces risk without necessarily reducing return — this fund moves with the whole market, not one company\'s fortunes.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 10,
                'is_active'        => true,
            ],
            [
                'name'             => 'Corporate Bond (5-Year)',
                'slug'             => 'corporate-bond-5yr',
                'brand'            => null,
                'category'         => 'investment',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 300000,
                'monthly_income'   => 4200,
                'monthly_cost'     => 0,
                'income_description' => '~16.8% p.a. coupon from a listed corporate issuer',
                'cost_description'   => '',
                'appreciation_rate'  => 1.20,
                'volatility'         => 0.03,
                'risk_level'         => 2,
                'icon'             => '📃',
                'image_url'        => 'https://loremflickr.com/800/500/bond,contract?lock=142',
                'description'      => 'A 5-year bond issued by a listed Kenyan company, paying a higher coupon than government debt in exchange for slightly more risk.',
                'flavor_text'      => 'Higher reward always comes with a little more risk attached — read the prospectus.',
                'educational_note' => 'Corporate bonds pay more than T-bonds because companies can default; governments (usually) can\'t. That gap is the risk premium.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 5,
                'is_active'        => true,
            ],
            [
                'name'             => 'Gold — 10g Bar',
                'slug'             => 'gold-10g-bar',
                'brand'            => null,
                'category'         => 'investment',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 95000,
                'monthly_income'   => 0,
                'monthly_cost'     => 0,
                'income_description' => 'No income — pure store of value',
                'cost_description'   => '',
                'appreciation_rate'  => 0.60,
                'volatility'         => 0.06,
                'risk_level'         => 2,
                'icon'             => '🥇',
                'image_url'        => 'https://loremflickr.com/800/500/gold,bullion?lock=143',
                'description'      => 'Physical gold — the asset humans have trusted for 5,000 years. No dividends, no rent, just a hedge against everything else falling apart.',
                'flavor_text'      => 'When currencies wobble, gold doesn\'t ask questions.',
                'educational_note' => 'Gold pays no income and its price is driven by fear and scarcity, not earnings — it\'s insurance, not a growth investment.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 10,
                'is_active'        => true,
            ],

            // ═══════════════════════════════════════════════════════
            // MORE GADGETS
            // ═══════════════════════════════════════════════════════
            [
                'name'             => 'Drone — DJI Mini',
                'slug'             => 'drone-dji-mini',
                'brand'            => 'DJI',
                'category'         => 'gadget',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 95000,
                'monthly_income'   => 12000,
                'monthly_cost'     => 1500,
                'income_description' => 'Wedding/event aerial photography gigs',
                'cost_description'   => 'Batteries, props, cloud storage',
                'appreciation_rate'  => -3.00,
                'volatility'         => 0.10,
                'risk_level'         => 2,
                'icon'             => '🚁',
                'image_url'        => 'https://loremflickr.com/800/500/drone,camera?lock=144',
                'description'      => 'A camera drone that turns weekend weddings into weekday income. Every event now wants that aerial shot.',
                'flavor_text'      => 'The best man\'s speech is forgettable. The drone shot never is.',
                'educational_note' => 'Skill-plus-gadget combos (drone + editing skill) earn far more than the gadget alone — the tool is only as valuable as the skill behind it.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
        ];

        foreach ($assets as $data) {
            Asset::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
