<?php

namespace Database\Seeders;

use App\Models\Bill;
use Illuminate\Database\Seeder;

class BillSeeder extends Seeder
{
    public function run(): void
    {
        $bills = [

            // ═══════════════════════════════════════════════════════════════
            // 8-12: Primary School (The Student — Young)
            // ═══════════════════════════════════════════════════════════════
            [
                'age_group'          => '8-12',
                'name'               => 'School Lunch',
                'slug'               => 'lunch-primary',
                'description'        => 'Daily lunch money at the school tuck shop.',
                'flavor_text'        => 'The school tuck shop smells like freshly fried mandazi every morning. You need Ksh 50 each day for lunch — ugali, beans, sometimes chips on Fridays. That\'s Ksh 350 for the school week.',
                'consequence_text'   => 'Your tummy growls loudly in class. Mrs. Kamau asks if you ate. You lie and say yes. You can\'t focus on sums.',
                'amount'             => 350,
                'frequency_ticks'    => 7,
                'category'           => 'food',
                'icon'               => '🍱',
                'is_essential'       => true,
                'credit_impact_pay'  => 3,
                'credit_impact_miss' => -10,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '8-12',
                'name'               => 'School Bus Fare',
                'slug'               => 'bus-primary',
                'description'        => 'Monthly school bus contribution.',
                'flavor_text'        => 'The school bus picks you up at 6:45 AM sharp, right outside your gate. Miss the monthly payment and you\'re walking 3 kilometres in your school uniform. Ksh 200 buys you a seat every morning.',
                'consequence_text'   => 'You arrive sweaty, dusty, and 20 minutes late. The headteacher writes a note in your diary. Mama is not happy.',
                'amount'             => 200,
                'frequency_ticks'    => 30,
                'category'           => 'transport',
                'icon'               => '🚌',
                'is_essential'       => true,
                'credit_impact_pay'  => 3,
                'credit_impact_miss' => -10,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '8-12',
                'name'               => 'Emergency Airtime',
                'slug'               => 'airtime-primary',
                'description'        => 'Monthly airtime to call home in case of emergency.',
                'flavor_text'        => 'Baba always says the same thing: "Always have Ksh 50 airtime on that phone so you can call home if anything happens." It\'s a small top-up, but it\'s your lifeline.',
                'consequence_text'   => 'Your phone is completely dry. You have to borrow a classmate\'s phone. It\'s embarrassing, and what if it\'s a real emergency?',
                'amount'             => 50,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 70],
                    ['min_net_worth' => 5_000_000, 'amount' => 100],
                    ['min_net_worth' => 20_000_000, 'amount' => 140],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'communication',
                'icon'               => '📱',
                'is_essential'       => false,
                'credit_impact_pay'  => 2,
                'credit_impact_miss' => -5,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '8-12',
                'name'               => 'Stationery & Books',
                'slug'               => 'stationery-primary',
                'description'        => 'Monthly school stationery — pens, exercise books, ruler.',
                'flavor_text'        => 'Every term, the teacher hands out a list: 4 exercise books, two pens (blue and red), a ruler, and a compass for Standard 6 geometry. Ksh 150 keeps you fully equipped.',
                'consequence_text'   => 'You share a book with your desk-mate. The teacher notices. "Next time, come prepared," she says in front of everyone.',
                'amount'             => 150,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 210],
                    ['min_net_worth' => 5_000_000, 'amount' => 300],
                    ['min_net_worth' => 20_000_000, 'amount' => 420],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'education',
                'icon'               => '📚',
                'is_essential'       => false,
                'credit_impact_pay'  => 3,
                'credit_impact_miss' => -8,
                'auto_assign'        => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // 13-17: Secondary School (The Teen)
            // ═══════════════════════════════════════════════════════════════
            [
                'age_group'          => '13-17',
                'name'               => 'School Lunch',
                'slug'               => 'lunch-secondary',
                'description'        => 'Weekly school lunch money at the canteen.',
                'flavor_text'        => 'The school canteen has rice and beans, ugali with beef stew on Tuesdays, and pilau on the last Friday of the month. Ksh 80 a day keeps you fed and focused in afternoon lessons. Total: Ksh 560 per week.',
                'consequence_text'   => 'You skip lunch. By 2PM your concentration is gone, your head aches, and you bomb the Geography test. Your KCSE mock results will not explain "I was hungry."',
                'amount'             => 560,
                'frequency_ticks'    => 7,
                'category'           => 'food',
                'icon'               => '🍛',
                'is_essential'       => true,
                'credit_impact_pay'  => 4,
                'credit_impact_miss' => -15,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '13-17',
                'name'               => 'Matatu to School',
                'slug'               => 'matatu-secondary',
                'description'        => 'Monthly matatu fare to and from school.',
                'flavor_text'        => 'It\'s 30-bob each way on the 23 route — crammed in with school bags, conductors shouting stage names. No fare and you\'re walking, showing up sweaty and marked absent. Ksh 600/month keeps you on the bus.',
                'consequence_text'   => 'You walk. School starts at 7:30. You arrive at 8:15. Mama gets a text from the school. Another explanation needed around the dinner table.',
                'amount'             => 600,
                'frequency_ticks'    => 30,
                'category'           => 'transport',
                'icon'               => '🚐',
                'is_essential'       => true,
                'credit_impact_pay'  => 4,
                'credit_impact_miss' => -15,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '13-17',
                'name'               => 'Data Bundle',
                'slug'               => 'data-secondary',
                'description'        => 'Monthly Safaricom data bundle — 1GB.',
                'flavor_text'        => '1GB Safaricom bundle. The homework WhatsApp group sends past papers at 9PM. YouTube has the Chemistry explanation your teacher never gave. TikTok is... research. You cannot function without data. Ksh 300/month.',
                'consequence_text'   => 'You\'re offline. The study group moved on. Someone shared the leaked mock answers. You\'re the only one who didn\'t see them. FOMO has real academic consequences.',
                'amount'             => 300,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 420],
                    ['min_net_worth' => 5_000_000, 'amount' => 600],
                    ['min_net_worth' => 20_000_000, 'amount' => 840],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'communication',
                'icon'               => '📶',
                'is_essential'       => false,
                'credit_impact_pay'  => 3,
                'credit_impact_miss' => -8,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '13-17',
                'name'               => 'Stationery & School Materials',
                'slug'               => 'stationery-secondary',
                'description'        => 'Monthly school materials — exercise books, pens, revision papers.',
                'flavor_text'        => 'Form Three and the subject teachers each want a separate exercise book. Plus revision booklets from the kiosk, a scientific calculator (shared with your cousin), and highlighters. Ksh 200 a month is the minimum.',
                'consequence_text'   => 'You borrow pens from classmates every single day. Eventually they stop lending. You take notes on your phone — and the teacher confiscates it.',
                'amount'             => 200,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 280],
                    ['min_net_worth' => 5_000_000, 'amount' => 400],
                    ['min_net_worth' => 20_000_000, 'amount' => 560],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'education',
                'icon'               => '📓',
                'is_essential'       => false,
                'credit_impact_pay'  => 3,
                'credit_impact_miss' => -8,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '13-17',
                'name'               => 'School Events & Trips',
                'slug'               => 'events-secondary',
                'description'        => 'Monthly contributions for school events, trips, and clubs.',
                'flavor_text'        => 'Drama festival. Music competitions. The trip to Nairobi National Museum. Sports day refreshments. Every month something happens and contributions are collected. It\'s not optional — it\'s school community. Ksh 300/month.',
                'consequence_text'   => 'You stay behind when your classmates board the bus to Nairobi. You tell yourself it doesn\'t matter. It does. Next time, budget for it.',
                'amount'             => 300,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 420],
                    ['min_net_worth' => 5_000_000, 'amount' => 600],
                    ['min_net_worth' => 20_000_000, 'amount' => 840],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'social',
                'icon'               => '🎭',
                'is_essential'       => false,
                'credit_impact_pay'  => 3,
                'credit_impact_miss' => -5,
                'auto_assign'        => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // 18-25: Young Adult (The Graduate / Hustler)
            // ═══════════════════════════════════════════════════════════════
            [
                'age_group'          => '18-25',
                'name'               => 'Bedsitter Rent',
                'slug'               => 'rent-bedsitter',
                'description'        => 'Monthly rent for your bedsitter.',
                'flavor_text'        => 'Your bedsitter in Ruaka — one room, a small charcoal stove area, shared showers down the hall. It\'s not fancy, but it\'s YOURS. Mr. Njoroge the caretaker knocks on the 2nd of every month. He doesn\'t forget. He doesn\'t accept excuses. Rent: Ksh 4,500.',
                'consequence_text'   => 'Lock-out. Your padlock is replaced by the landlord\'s. Your mattress is in the corridor. Social media is NOT ready for these pictures.',
                'amount'             => 4500,
                'frequency_ticks'    => 30,
                'category'           => 'housing',
                'icon'               => '🏠',
                'is_essential'       => true,
                'credit_impact_pay'  => 8,
                'credit_impact_miss' => -25,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '18-25',
                'name'               => 'KPLC Tokens',
                'slug'               => 'kplc-bedsitter',
                'description'        => 'Monthly Kenya Power prepaid electricity tokens.',
                'flavor_text'        => 'The meter beeps at 11PM — only 5 units left. You\'re halfway through your assignment. Pre-pay Ksh 600 at the M-PESA counter or cook your uji in the dark and submit a blank document.',
                'consequence_text'   => 'Power is out. Laptop dead. Phone dead. Your assignment deadline doesn\'t care about your power situation. Neither does your supervisor.',
                'amount'             => 600,
                'frequency_ticks'    => 30,
                'category'           => 'utilities',
                'icon'               => '⚡',
                'is_essential'       => true,
                'credit_impact_pay'  => 5,
                'credit_impact_miss' => -15,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '18-25',
                'name'               => 'Water (Caretaker)',
                'slug'               => 'water-bedsitter',
                'description'        => 'Monthly water contribution to the caretaker.',
                'flavor_text'        => 'The water supply runs through a communal tank controlled by Mr. Njoroge. Pay Ksh 350 at the end of each month or discover your tap gives only air. Ksh 350 is cheaper than buying water in jerricans.',
                'consequence_text'   => 'Day 3 without water. You\'re borrowing a bucket from your neighbor. They start locking their door. This is not a game anymore.',
                'amount'             => 350,
                'frequency_ticks'    => 30,
                'category'           => 'utilities',
                'icon'               => '💧',
                'is_essential'       => true,
                'credit_impact_pay'  => 5,
                'credit_impact_miss' => -15,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '18-25',
                'name'               => 'Groceries',
                'slug'               => 'groceries-young',
                'description'        => 'Monthly food and household groceries.',
                'flavor_text'        => 'Rice, maize flour, sukuma wiki from the mama mboga, tomatoes, cooking oil, and sometimes a whole chicken on payday. You\'ve mastered cooking on a budget. Ksh 2,500/month keeps you fed with leftovers for lunch.',
                'consequence_text'   => 'Day 4 of plain ugali with salt. Your focus, your mood, and your energy are all on strike. Hard to hustle on an empty stomach.',
                'amount'             => 2500,
                'frequency_ticks'    => 30,
                'category'           => 'food',
                'icon'               => '🛒',
                'is_essential'       => true,
                'credit_impact_pay'  => 5,
                'credit_impact_miss' => -15,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '18-25',
                'name'               => 'Matatu & Transport',
                'slug'               => 'transport-young',
                'description'        => 'Monthly transport — matatu, boda, occasional Uber.',
                'flavor_text'        => 'Matatu to town. Boda boda when you\'re running late for an interview. Uber when it rains and you have a presentation. The 30-bob trip to town adds up. Ksh 1,500/month is the realistic budget.',
                'consequence_text'   => 'You walk everywhere. Your shoes wear out faster than your savings grow. That interview downtown? You arrive damp, late, and out of breath.',
                'amount'             => 1500,
                'frequency_ticks'    => 30,
                'category'           => 'transport',
                'icon'               => '🚐',
                'is_essential'       => true,
                'credit_impact_pay'  => 5,
                'credit_impact_miss' => -12,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '18-25',
                'name'               => 'Safaricom Airtime & Data',
                'slug'               => 'airtime-young',
                'description'        => 'Monthly Safaricom airtime and data bundle.',
                'flavor_text'        => 'M-PESA transactions. Job application calls. WhatsApp with clients and employers. Zoom calls with your remote team. LinkedIn scrolling for the next opportunity. You run entirely on Safaricom. Ksh 500/month is survival.',
                'consequence_text'   => 'Your phone becomes a camera with no SIM. Calls drop. Clients can\'t reach you. That job callback you\'ve been waiting for goes to voicemail. Opportunities don\'t wait.',
                'amount'             => 500,
                'frequency_ticks'    => 30,
                'category'           => 'communication',
                'icon'               => '📶',
                'is_essential'       => true,
                'credit_impact_pay'  => 4,
                'credit_impact_miss' => -12,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '18-25',
                'name'               => 'NHIF Contribution',
                'slug'               => 'nhif-young',
                'description'        => 'Monthly NHIF health insurance contribution.',
                'flavor_text'        => 'You\'re 22 and feel invincible. But malaria hospitalization, a motorbike accident, or a broken arm costs Ksh 40,000 without insurance. NHIF costs Ksh 500/month. The math is very, very simple.',
                'consequence_text'   => 'The hospital asks for Ksh 5,000 upfront at the reception counter before they treat you. The nurse looks at you. You look at your balance. Life is brutally expensive without a health cover.',
                'amount'             => 500,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 700],
                    ['min_net_worth' => 5_000_000, 'amount' => 1000],
                    ['min_net_worth' => 20_000_000, 'amount' => 1400],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'health',
                'icon'               => '🏥',
                'is_essential'       => false,
                'credit_impact_pay'  => 6,
                'credit_impact_miss' => -12,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '18-25',
                'name'               => 'HELB Loan Repayment',
                'slug'               => 'helb-young',
                'description'        => 'Monthly Higher Education Loans Board repayment.',
                'flavor_text'        => 'HELB funded four years of lectures, hostels, and late-night githeri. Now it\'s time to give back. Ksh 1,000/month, tracked by the Higher Education Loans Board. The interest compounds when you miss payments. Pay before it becomes a problem.',
                'consequence_text'   => 'Interest accrues at 12% per annum. Your HELB default flag gets attached to your KRA PIN. Future bank loans become difficult. You\'ll wish you had paid the Ksh 1,000.',
                'amount'             => 1000,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 1400],
                    ['min_net_worth' => 5_000_000, 'amount' => 2000],
                    ['min_net_worth' => 20_000_000, 'amount' => 2800],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'education',
                'icon'               => '🎓',
                'is_essential'       => false,
                'credit_impact_pay'  => 8,
                'credit_impact_miss' => -20,
                'auto_assign'        => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // 26+: Adult / Settler / Builder
            // ═══════════════════════════════════════════════════════════════
            [
                'age_group'          => '26+',
                'name'               => 'House Rent',
                'slug'               => 'rent-adult',
                'description'        => 'Monthly rent for a 2-bedroom apartment.',
                'flavor_text'        => 'Your 2BR in Kahawa West — near the kids\' school, safe neighborhood, actual running water on most days. Mr. Kamau texts on the 28th of every month without fail: "Kindly pay rent for next month." He\'s polite. He\'s also serious. Ksh 12,000.',
                'consequence_text'   => 'Eviction notice pinned on your door. Three days to vacate. Finding a new house mid-school-term with two kids is chaos. The deposit you lose stings more than the embarrassment.',
                'amount'             => 12000,
                'frequency_ticks'    => 30,
                'category'           => 'housing',
                'icon'               => '🏡',
                'is_essential'       => true,
                'credit_impact_pay'  => 10,
                'credit_impact_miss' => -30,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '26+',
                'name'               => 'Kenya Power (KPLC)',
                'slug'               => 'kplc-adult',
                'description'        => 'Monthly Kenya Power prepaid electricity tokens.',
                'flavor_text'        => 'The water heater for morning showers. The fridge for the week\'s groceries. The TV for news and football. Four charging cables running at any one time. Power is infrastructure, not a luxury. Ksh 1,200/month at the KPLC prepay counter.',
                'consequence_text'   => 'Dark house. Angry spouse. Crying kids who can\'t do homework. The neighbor\'s generator starts at 10PM and runs till midnight. You lie there calculating what a bad financial decision this was.',
                'amount'             => 1200,
                'frequency_ticks'    => 30,
                'category'           => 'utilities',
                'icon'               => '⚡',
                'is_essential'       => true,
                'credit_impact_pay'  => 7,
                'credit_impact_miss' => -20,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '26+',
                'name'               => 'Nairobi Water',
                'slug'               => 'water-adult',
                'description'        => 'Monthly Nairobi Water Company bill.',
                'flavor_text'        => 'Nairobi Water bills arrive via email these days — sometimes with surprise arrears from three months ago. Always fill the storage tank when the water comes. Budget Ksh 600 and keep a jerican in reserve.',
                'consequence_text'   => 'A water bowser costs Ksh 1,500 per load. The math is embarrassing. But with two kids who need baths and a kitchen that needs cleaning, you have no choice.',
                'amount'             => 600,
                'frequency_ticks'    => 30,
                'category'           => 'utilities',
                'icon'               => '💧',
                'is_essential'       => true,
                'credit_impact_pay'  => 6,
                'credit_impact_miss' => -15,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '26+',
                'name'               => 'Safaricom Home Fibre',
                'slug'               => 'internet-adult',
                'description'        => 'Monthly home internet — Safaricom 20Mbps Fibre.',
                'flavor_text'        => '20Mbps Safaricom Home Fibre. Your remote work depends on it. The kids submit school assignments through it. Netflix keeps the house peaceful on Friday nights. Zoom calls with the Nairobi office. Ksh 1,500/month is the price of staying connected.',
                'consequence_text'   => 'Mobile hotspot at 2KB/s. Your Zoom call freezes mid-presentation. The kids use your data for YouTube. Your boss thinks you work from a matatu.',
                'amount'             => 1500,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 2100],
                    ['min_net_worth' => 5_000_000, 'amount' => 3000],
                    ['min_net_worth' => 20_000_000, 'amount' => 4200],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'utilities',
                'icon'               => '🌐',
                'is_essential'       => false,
                'credit_impact_pay'  => 5,
                'credit_impact_miss' => -10,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '26+',
                'name'               => 'Groceries & Household',
                'slug'               => 'groceries-adult',
                'description'        => 'Monthly household groceries and food supplies.',
                'flavor_text'        => 'Maize flour (two 2kg bags), rice, sukuma wiki and spinach, cooking oil, milk, bread, eggs, and the inevitable "we need gas" at the worst possible time. Ksh 6,000/month keeps a family fed. It used to be Ksh 4,000. Inflation is real.',
                'consequence_text'   => 'You borrow unga from the neighbor. Once. Twice. On the third time she stops opening the door immediately. It affects more than your fridge.',
                'amount'             => 6000,
                'frequency_ticks'    => 30,
                'category'           => 'food',
                'icon'               => '🛒',
                'is_essential'       => true,
                'credit_impact_pay'  => 7,
                'credit_impact_miss' => -20,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '26+',
                'name'               => 'Fuel & Transport',
                'slug'               => 'fuel-adult',
                'description'        => 'Monthly fuel, parking, and transport costs.',
                'flavor_text'        => 'Petrol twice a week, parking in town at Ksh 200/day, the occasional Uber when the car is in the garage for a "small issue" that turns out to be expensive, and the random "honey, pick something from the shop" trips. Ksh 3,000/month is realistic.',
                'consequence_text'   => 'The car doesn\'t move this month. You\'re back on matatu at 6AM. Your knees remind you exactly why you worked hard to buy that car.',
                'amount'             => 3000,
                'frequency_ticks'    => 30,
                'category'           => 'transport',
                'icon'               => '⛽',
                'is_essential'       => true,
                'credit_impact_pay'  => 6,
                'credit_impact_miss' => -12,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '26+',
                'name'               => 'NHIF Family Cover',
                'slug'               => 'nhif-adult',
                'description'        => 'Monthly NHIF family health insurance.',
                'flavor_text'        => 'Higher income bracket, higher NHIF. Ksh 1,700/month covers you, your spouse, and up to two children. Miss a month and you\'re temporarily uninsured. Hospitals don\'t care about the reason you missed — they care about your cover status.',
                'consequence_text'   => 'Your child gets malaria. The hospital asks for Ksh 20,000 upfront. You dig into your savings. Three months later you\'re still recovering financially. All because of Ksh 1,700.',
                'amount'             => 1700,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 2400],
                    ['min_net_worth' => 5_000_000, 'amount' => 3400],
                    ['min_net_worth' => 20_000_000, 'amount' => 4800],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'health',
                'icon'               => '🏥',
                'is_essential'       => false,
                'credit_impact_pay'  => 7,
                'credit_impact_miss' => -20,
                'auto_assign'        => true,
            ],
            [
                'age_group'          => '26+',
                'name'               => 'Upcountry Family Support',
                'slug'               => 'family-support',
                'description'        => 'Monthly support for family back in the village.',
                'flavor_text'        => 'Mama calls on the 5th of every month. Not to check on you — she knows you\'re fine. She\'s asking about unga money, your younger sibling\'s school fees balance, and the church harambee next Saturday. Ksh 2,000. It\'s not negotiable.',
                'consequence_text'   => 'She stops calling for two weeks. Then your aunt calls. Then your cousin. The whole village has discussed your finances. Family pressure is a Kenyan bill that never expires.',
                'amount'             => 2000,
                'net_worth_tiers'    => ['tiers' => [
                    ['min_net_worth' => 1_000_000, 'amount' => 2800],
                    ['min_net_worth' => 5_000_000, 'amount' => 4000],
                    ['min_net_worth' => 20_000_000, 'amount' => 5600],
                ]],
                'frequency_ticks'    => 30,
                'category'           => 'family',
                'icon'               => '👨‍👩‍👧',
                'is_essential'       => false,
                'credit_impact_pay'  => 5,
                'credit_impact_miss' => -8,
                'auto_assign'        => true,
            ],

        ];

        foreach ($bills as $bill) {
            Bill::updateOrCreate(['slug' => $bill['slug']], $bill);
        }

        $this->command->info('Bill catalog seeded: ' . count($bills) . ' bills across 4 age groups.');
    }
}
