<?php

namespace Database\Seeders;

use App\Models\Asset;
use Illuminate\Database\Seeder;

class BrandGadgetSeeder extends Seeder
{
    public function run(): void
    {
        $gadgets = [

            // ── PHONES ─────────────────────────────────────────────
            [
                'name'             => 'Infinix Hot 40i',
                'slug'             => 'infinix-hot-40i',
                'brand'            => 'Infinix',
                'category'         => 'gadget',
                'tier'             => 1,
                'age_group'        => '13-17',
                'base_price'       => 12000,
                'monthly_income'   => 0,
                'monthly_cost'     => 500,
                'income_description' => '',
                'cost_description'   => 'Mobile data bundles',
                'appreciation_rate'  => -2.5,
                'volatility'         => 0.05,
                'risk_level'         => 1,
                'icon'             => '📱',
                'image_url'        => 'https://loremflickr.com/800/500/smartphone,android?lock=201',
                'description'      => 'Pocket-friendly and reliable. The Infinix Hot 40i gives you a big screen and strong battery to stay connected all day.',
                'flavor_text'      => 'Entry point to the digital economy — affordable and practical.',
                'educational_note' => 'Budget phones lose value in months. Buy one to use as a tool — not as a status symbol.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Tecno Camon 30',
                'slug'             => 'tecno-camon-30',
                'brand'            => 'Tecno',
                'category'         => 'gadget',
                'tier'             => 1,
                'age_group'        => '18-25',
                'base_price'       => 18500,
                'monthly_income'   => 0,
                'monthly_cost'     => 700,
                'income_description' => '',
                'cost_description'   => 'Data bundles, accessories',
                'appreciation_rate'  => -2.2,
                'volatility'         => 0.05,
                'risk_level'         => 1,
                'icon'             => '📱',
                'image_url'        => 'https://loremflickr.com/800/500/smartphone,camera?lock=202',
                'description'      => 'A camera-focused phone popular with students and young professionals. Shoots great content for social media.',
                'flavor_text'      => '"Content is king" — and you need a decent camera to play.',
                'educational_note' => 'Mid-range phones depreciate at ~50% per year. Use it to build a side hustle — photography, content creation, mobile banking.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Samsung Galaxy A55',
                'slug'             => 'samsung-galaxy-a55',
                'brand'            => 'Samsung',
                'category'         => 'gadget',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 52000,
                'monthly_income'   => 0,
                'monthly_cost'     => 1200,
                'income_description' => '',
                'cost_description'   => 'Data bundles, screen protection, servicing',
                'appreciation_rate'  => -1.8,
                'volatility'         => 0.04,
                'risk_level'         => 2,
                'icon'             => '📱',
                'image_url'        => 'https://loremflickr.com/800/500/samsung,smartphone?lock=203',
                'description'      => 'The Samsung A55 — powerful, stylish, and built to last. A common upgrade after your first job.',
                'flavor_text'      => 'You\'ve levelled up from a Tecno. Time to level up your game too.',
                'educational_note' => 'Lifestyle inflation is real. A phone upgrade after a salary rise feels earned — but remember it costs more to maintain. Ask: "does this earn me income?"',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Samsung Galaxy S24',
                'slug'             => 'samsung-galaxy-s24',
                'brand'            => 'Samsung',
                'category'         => 'gadget',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 145000,
                'monthly_income'   => 0,
                'monthly_cost'     => 2500,
                'income_description' => '',
                'cost_description'   => 'Insurance, accessories, screen protection',
                'appreciation_rate'  => -1.5,
                'volatility'         => 0.04,
                'risk_level'         => 2,
                'icon'             => '📱',
                'image_url'        => 'https://loremflickr.com/800/500/samsung,flagship?lock=204',
                'description'      => 'The Galaxy S24. Flagship specs, AI features, premium build. The phone that says you\'ve made it — carefully.',
                'flavor_text'      => 'Every exec needs sharp tools. Just make sure it\'s a reward, not a splurge.',
                'educational_note' => 'Flagship phones cost more to insure, repair, and eventually replace. At 145K, that\'s 4 months of a mid-level salary. Time the purchase wisely.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'iPhone 15',
                'slug'             => 'iphone-15',
                'brand'            => 'Apple',
                'category'         => 'gadget',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 165000,
                'monthly_income'   => 0,
                'monthly_cost'     => 2800,
                'income_description' => '',
                'cost_description'   => 'AppleCare, accessories, screen repair risk',
                'appreciation_rate'  => -1.2,
                'volatility'         => 0.03,
                'risk_level'         => 2,
                'icon'             => '📱',
                'image_url'        => 'https://loremflickr.com/800/500/iphone,apple?lock=205',
                'description'      => 'The iPhone 15. The ultimate Kenyan status symbol. Premium camera, seamless ecosystem, and the slowest depreciation of any smartphone.',
                'flavor_text'      => '"The iPhone tax" — social acceptance costs Ksh 165,000.',
                'educational_note' => 'iPhones hold value better than other brands (slower depreciation). If you\'re buying a phone as a "store of value," an iPhone is the closest bet — though still loses value.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'iPhone 16 Pro Max',
                'slug'             => 'iphone-16-pro-max',
                'brand'            => 'Apple',
                'category'         => 'gadget',
                'tier'             => 4,
                'age_group'        => '26+',
                'base_price'       => 230000,
                'monthly_income'   => 0,
                'monthly_cost'     => 3500,
                'income_description' => '',
                'cost_description'   => 'Insurance, accessories, premium repairs',
                'appreciation_rate'  => -1.0,
                'volatility'         => 0.03,
                'risk_level'         => 3,
                'icon'             => '📱',
                'image_url'        => 'https://loremflickr.com/800/500/iphone,pro?lock=206',
                'description'      => 'The iPhone 16 Pro Max — titanium frame, A18 Pro chip, 48MP triple camera. For those who accept no compromise. And can afford not to.',
                'flavor_text'      => 'Is this a tool or a trophy? Your answer says everything about your financial mindset.',
                'educational_note' => 'At 230K, you could put that in a Money Market Fund earning 12% p.a. and buy a budget phone with 1 month\'s interest. The opportunity cost of luxury is real.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],

            // ── LAPTOPS ────────────────────────────────────────────
            [
                'name'             => 'Lenovo IdeaPad Slim 3',
                'slug'             => 'lenovo-ideapad-slim3',
                'brand'            => 'Lenovo',
                'category'         => 'gadget',
                'tier'             => 2,
                'age_group'        => '13-17',
                'base_price'       => 55000,
                'monthly_income'   => 0,
                'monthly_cost'     => 800,
                'income_description' => '',
                'cost_description'   => 'Antivirus, accessories',
                'appreciation_rate'  => -1.8,
                'volatility'         => 0.04,
                'risk_level'         => 2,
                'icon'             => '💻',
                'image_url'        => 'https://loremflickr.com/800/500/lenovo,laptop?lock=210',
                'description'      => 'The Lenovo IdeaPad — lighter and faster than the HP, great for students who code or design.',
                'flavor_text'      => 'Your campus companion. Build the skills that build the career.',
                'educational_note' => 'A laptop is a depreciating asset that CAN generate income. If you use it to freelance, tutor online, or build apps, it pays for itself.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'MacBook Air M2',
                'slug'             => 'macbook-air-m2',
                'brand'            => 'Apple',
                'category'         => 'gadget',
                'tier'             => 3,
                'age_group'        => '18-25',
                'base_price'       => 180000,
                'monthly_income'   => 8000,
                'monthly_cost'     => 2000,
                'income_description' => 'Freelance design/dev work per month',
                'cost_description'   => 'AppleCare, accessories',
                'appreciation_rate'  => -1.0,
                'volatility'         => 0.03,
                'risk_level'         => 2,
                'icon'             => '💻',
                'image_url'        => 'https://loremflickr.com/800/500/macbook,apple?lock=211',
                'description'      => 'The MacBook Air M2. Featherlight, all-day battery, professional-grade performance. The tool of choice for Nairobi\'s creative and tech scene.',
                'flavor_text'      => 'The Apple logo in a Westlands café signals "I mean business."',
                'educational_note' => 'The MacBook M2 holds value exceptionally well — 2-year-old models still sell for 70% of retail. As tools go, this is one of the better depreciating assets to own.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Dell XPS 15',
                'slug'             => 'dell-xps-15',
                'brand'            => 'Dell',
                'category'         => 'gadget',
                'tier'             => 3,
                'age_group'        => '26+',
                'base_price'       => 210000,
                'monthly_income'   => 12000,
                'monthly_cost'     => 2500,
                'income_description' => 'Freelance tech consulting / development',
                'cost_description'   => 'Insurance, accessories, servicing',
                'appreciation_rate'  => -1.2,
                'volatility'         => 0.03,
                'risk_level'         => 2,
                'icon'             => '💻',
                'image_url'        => 'https://loremflickr.com/800/500/dell,xps,laptop?lock=212',
                'description'      => 'The Dell XPS 15 — enterprise-grade power in a premium chassis. For the professional who demands the absolute best performance.',
                'flavor_text'      => 'This machine doesn\'t just run code — it generates income.',
                'educational_note' => 'High-end laptops can be justified when they enable high-income work. At Ksh 210K, you need to earn back that investment within 18 months to make it worthwhile.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],

            // ── GAMING / OTHER ──────────────────────────────────────
            [
                'name'             => 'PlayStation 5',
                'slug'             => 'playstation-5',
                'brand'            => 'Sony',
                'category'         => 'gadget',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 75000,
                'monthly_income'   => 0,
                'monthly_cost'     => 3000,
                'income_description' => '',
                'cost_description'   => 'Games subscription (PS Plus), electricity, games',
                'appreciation_rate'  => -0.8,
                'volatility'         => 0.06,
                'risk_level'         => 2,
                'icon'             => '🎮',
                'image_url'        => 'https://loremflickr.com/800/500/playstation,gaming?lock=220',
                'description'      => 'The PlayStation 5. Pure entertainment. No income, but it appreciates at the slowest rate in the gadget category — limited supply.',
                'flavor_text'      => 'You earned it. But did you budget for it first?',
                'educational_note' => 'Entertainment electronics are the definition of pure consumption. The PS5 costs 75K upfront plus 3K/month. Before buying, check your emergency fund is funded first.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
            [
                'name'             => 'Smart TV 55" 4K',
                'slug'             => 'smart-tv-55',
                'brand'            => 'Samsung',
                'category'         => 'gadget',
                'tier'             => 2,
                'age_group'        => '18-25',
                'base_price'       => 65000,
                'monthly_income'   => 0,
                'monthly_cost'     => 1500,
                'income_description' => '',
                'cost_description'   => 'Netflix, Showmax, electricity',
                'appreciation_rate'  => -1.5,
                'volatility'         => 0.04,
                'risk_level'         => 1,
                'icon'             => '📺',
                'image_url'        => 'https://loremflickr.com/800/500/smart-tv,television?lock=221',
                'description'      => 'A Samsung 55" Smart TV. The centrepiece of every Nairobi living room upgrade. Stream, game, entertain.',
                'flavor_text'      => 'The bigger the TV, the smaller the savings.',
                'educational_note' => 'TVs lose half their value within 2-3 years. Streaming subscriptions add to the monthly cost. Upgrade your financial literacy before upgrading your screen size.',
                'creates_bill_slug'=> null,
                'max_per_player'   => 1,
                'is_active'        => true,
            ],
        ];

        foreach ($gadgets as $gadget) {
            Asset::updateOrCreate(
                ['slug' => $gadget['slug']],
                $gadget
            );
        }

        $this->command->info('BrandGadgetSeeder: ' . count($gadgets) . ' gadgets seeded/updated.');
    }
}
