<?php

namespace Database\Seeders;

use App\Models\Quest;
use Illuminate\Database\Seeder;

/**
 * Band 2 of ChallengeQuest18to25Seeder — levels 4-10. See
 * ChallengeQuest8to12Band2Seeder for the full complexity-ramp explanation.
 */
class ChallengeQuest18to25Band2Seeder extends Seeder
{
    private const AGE_GROUP = '18-25';

    private const QUESTS = [

        // ══════════════════════════════════ LEVEL 4 ══════
        ['title' => 'Net Worth Ksh 50,000', 'level' => 4, 'xp' => 260, 'kes' => 210, 'icon' => '📈',
            'desc' => 'Push your net worth to Ksh 50,000.',
            'lesson' => 'A growing net worth is many small good choices adding up, not one lucky break.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_net_worth', 'values' => ['50000']]]],
        ['title' => 'Steadier Trading', 'level' => 4, 'xp' => 260, 'kes' => 210, 'icon' => '💹',
            'desc' => 'Bank Ksh 2,500 in total shares profit.',
            'lesson' => 'Steadier trading, not one big win, is what turns a lucky trade into a real skill.',
            'mode' => 'all', 'triggers' => [['type' => 'shares_profit', 'values' => ['2500']]]],
        ['title' => 'Pesa Trail Regular', 'level' => 4, 'xp' => 260, 'kes' => 210, 'icon' => '🎲',
            'desc' => 'Win 4 games of Pesa Trail.',
            'lesson' => 'Four wins means you understand the board better than most first-timers.',
            'mode' => 'all', 'triggers' => [['type' => 'arcade_wins', 'values' => ['4']]]],
        ['title' => 'Bigger Cash Cushion', 'level' => 4, 'xp' => 260, 'kes' => 210, 'icon' => '💵',
            'desc' => 'Keep Ksh 20,000 in your wallet balance at once.',
            'lesson' => 'A bigger cushion means small surprises stop being a problem at all.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_balance', 'values' => ['20000']]]],
        ['title' => 'Savings Milestone Two', 'level' => 4, 'xp' => 260, 'kes' => 210, 'icon' => '🐷',
            'desc' => 'Grow your savings scheme balance to Ksh 25,000.',
            'lesson' => 'Each savings milestone gets easier once the habit is already built.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_savings', 'values' => ['25000']]]],
        ['title' => 'One Big Push', 'level' => 4, 'xp' => 260, 'kes' => 210, 'icon' => '💰',
            'desc' => 'Deposit Ksh 10,000 into your savings in one go.',
            'lesson' => 'A single big deposit, when you can afford it, jumpstarts a goal faster than dozens of tiny ones.',
            'mode' => 'all', 'triggers' => [['type' => 'deposit_savings', 'values' => ['10000']]]],
        ['title' => 'Trade or Play, Your Call', 'level' => 4, 'xp' => 312, 'kes' => 252, 'icon' => '🔀',
            'desc' => 'Either bank Ksh 2,500 in shares profit, or win 4 games of Pesa Trail.',
            'lesson' => 'Different strengths, same reward — growing money doesn\'t need to look the same for everyone.',
            'mode' => 'any', 'triggers' => [['type' => 'shares_profit', 'values' => ['2500']], ['type' => 'arcade_wins', 'values' => ['4']]]],
        ['title' => 'Two Ways to Save', 'level' => 4, 'xp' => 312, 'kes' => 252, 'icon' => '🔀',
            'desc' => 'Either grow your savings to Ksh 25,000, or make one Ksh 10,000 deposit.',
            'lesson' => 'Small steady saves and one big push both build the exact same habit.',
            'mode' => 'any', 'triggers' => [['type' => 'reach_savings', 'values' => ['25000']], ['type' => 'deposit_savings', 'values' => ['10000']]]],
        ['title' => 'Group or Solo Growth', 'level' => 4, 'xp' => 312, 'kes' => 252, 'icon' => '🔀',
            'desc' => 'Either join a chama, or put money into an Equity Square deal.',
            'lesson' => 'Growing money with a group and growing it alone both count as real progress.',
            'mode' => 'any', 'triggers' => [['type' => 'join_chama'], ['type' => 'invest_deal']]],
        ['title' => 'Learn or Earn', 'level' => 4, 'xp' => 312, 'kes' => 252, 'icon' => '🔀',
            'desc' => 'Either finish a course, or get hired for a job.',
            'lesson' => 'Learning and earning both move you forward — you don\'t always need to do both at once.',
            'mode' => 'any', 'triggers' => [['type' => 'take_course'], ['type' => 'get_job']]],
        ['title' => 'Wealth and Liquidity', 'level' => 4, 'xp' => 338, 'kes' => 262, 'icon' => '🎯',
            'desc' => 'Reach Ksh 50,000 net worth AND keep Ksh 20,000 cash on hand at the same time.',
            'lesson' => 'Growing wealth while keeping usable cash is the real balancing act, every single level.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_net_worth', 'values' => ['50000']], ['type' => 'reach_balance', 'values' => ['20000']]]],
        ['title' => 'Spend Smart, Live a Little', 'level' => 4, 'xp' => 338, 'kes' => 262, 'icon' => '🎯',
            'desc' => 'Buy a vehicle from the marketplace AND spend on a Fun World experience.',
            'lesson' => 'A budget with zero fun in it rarely survives contact with real life — plan for both.',
            'mode' => 'all', 'triggers' => [['type' => 'buy_item_category', 'values' => ['vehicle']], ['type' => 'fun_world_spend']]],

        // ══════════════════════════════════ LEVEL 5 ══════
        ['title' => 'Wealth Keeps Climbing', 'level' => 5, 'xp' => 310, 'kes' => 250, 'icon' => '📈',
            'desc' => 'Push your net worth to Ksh 80,000.',
            'lesson' => 'Wealth that keeps climbing usually means several habits are working together, not just one.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_net_worth', 'values' => ['80000']]]],
        ['title' => 'Trading Groove', 'level' => 5, 'xp' => 310, 'kes' => 250, 'icon' => '💹',
            'desc' => 'Bank Ksh 4,000 in total shares profit.',
            'lesson' => 'Finding a trading groove means you\'re starting to recognize patterns, not guessing.',
            'mode' => 'all', 'triggers' => [['type' => 'shares_profit', 'values' => ['4000']]]],
        ['title' => 'Five Wins Deep', 'level' => 5, 'xp' => 310, 'kes' => 250, 'icon' => '🎲',
            'desc' => 'Win 5 games of Pesa Trail.',
            'lesson' => 'Five wins deep is well past luck — that\'s a real understanding of the board.',
            'mode' => 'all', 'triggers' => [['type' => 'arcade_wins', 'values' => ['5']]]],
        ['title' => 'Upgrade Ride', 'level' => 5, 'xp' => 310, 'kes' => 250, 'icon' => '🛍️',
            'desc' => 'Buy the Toyota Vitz 2016 from the marketplace — a real upgrade from a boda.',
            'lesson' => 'Upgrading a vehicle once you can genuinely afford it beats financing beyond what you can service.',
            'mode' => 'all', 'triggers' => [['type' => 'buy_item_slug', 'values' => ['toyota-vitz-2016']]]],
        ['title' => 'Grow It Your Way', 'level' => 5, 'xp' => 372, 'kes' => 300, 'icon' => '🔀',
            'desc' => 'Either bank Ksh 4,000 in shares profit, or put money into an Equity Square deal.',
            'lesson' => 'There\'s more than one legitimate way to grow money — the goal matters more than the method.',
            'mode' => 'any', 'triggers' => [['type' => 'shares_profit', 'values' => ['4000']], ['type' => 'invest_deal']]],
        ['title' => 'Play Solo or With the Group', 'level' => 5, 'xp' => 372, 'kes' => 300, 'icon' => '🔀',
            'desc' => 'Either win 5 games of Pesa Trail, or join a chama.',
            'lesson' => 'Solo wins and group commitment are both genuine financial skills, just different ones.',
            'mode' => 'any', 'triggers' => [['type' => 'arcade_wins', 'values' => ['5']], ['type' => 'join_chama']]],
        ['title' => 'Save Fast or Save Steady', 'level' => 5, 'xp' => 372, 'kes' => 300, 'icon' => '🔀',
            'desc' => 'Either grow your savings to Ksh 40,000, or make one Ksh 16,000 deposit.',
            'lesson' => 'A fast push and a steady climb both land you at the same savings goal.',
            'mode' => 'any', 'triggers' => [['type' => 'reach_savings', 'values' => ['40000']], ['type' => 'deposit_savings', 'values' => ['16000']]]],
        ['title' => 'Prove It With a Cert or a Badge', 'level' => 5, 'xp' => 372, 'kes' => 300, 'icon' => '🔀',
            'desc' => 'Either finish a course, or earn a badge.',
            'lesson' => 'A certificate and a badge are both proof — pick whichever path fits what you\'re doing right now.',
            'mode' => 'any', 'triggers' => [['type' => 'take_course'], ['type' => 'earn_badge']]],
        ['title' => 'Three-Way Wealth Check', 'level' => 5, 'xp' => 450, 'kes' => 337, 'icon' => '🎯',
            'desc' => 'Reach Ksh 80,000 net worth, Ksh 32,000 cash on hand, AND Ksh 40,000 in savings — all at once.',
            'lesson' => 'Checking net worth, cash and savings together gives a fuller picture than any single number.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['80000']],
                ['type' => 'reach_balance', 'values' => ['32000']],
                ['type' => 'reach_savings', 'values' => ['40000']],
            ]],
        ['title' => 'Skilled, Employed, Liquid', 'level' => 5, 'xp' => 450, 'kes' => 337, 'icon' => '🎯',
            'desc' => 'Finish a course, get hired, AND keep Ksh 32,000 cash on hand.',
            'lesson' => 'Skill, income and cash on hand working together beat any one of them alone.',
            'mode' => 'all', 'triggers' => [['type' => 'take_course'], ['type' => 'get_job'], ['type' => 'reach_balance', 'values' => ['32000']]]],
        ['title' => 'Trader, Gamer, Team Player', 'level' => 5, 'xp' => 450, 'kes' => 337, 'icon' => '🎯',
            'desc' => 'Bank Ksh 4,000 in shares profit, win 5 Pesa Trail games, AND join a chama.',
            'lesson' => 'Being decent at three different money games is worth more than being great at just one.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'shares_profit', 'values' => ['4000']],
                ['type' => 'arcade_wins', 'values' => ['5']],
                ['type' => 'join_chama'],
            ]],
        ['title' => 'The Steady Climb', 'level' => 5, 'xp' => 403, 'kes' => 312, 'icon' => '🎯',
            'desc' => 'Reach Ksh 80,000 net worth AND grow your savings to Ksh 40,000.',
            'lesson' => 'Net worth and savings usually climb together — but proving both matters more than assuming it.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_net_worth', 'values' => ['80000']], ['type' => 'reach_savings', 'values' => ['40000']]]],

        // ══════════════════════════════════ LEVEL 6 ══════
        ['title' => 'Building Real Wealth', 'level' => 6, 'xp' => 360, 'kes' => 290, 'icon' => '📈',
            'desc' => 'Push your net worth to Ksh 120,000.',
            'lesson' => 'Real wealth-building shows up as a habit you barely notice anymore, not a one-time event.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_net_worth', 'values' => ['120000']]]],
        ['title' => 'Sharper Trading Instincts', 'level' => 6, 'xp' => 360, 'kes' => 290, 'icon' => '💹',
            'desc' => 'Bank Ksh 6,000 in total shares profit.',
            'lesson' => 'Sharper instincts come from watching enough trades go both right and wrong.',
            'mode' => 'all', 'triggers' => [['type' => 'shares_profit', 'values' => ['6000']]]],
        ['title' => 'Six Wins and Counting', 'level' => 6, 'xp' => 360, 'kes' => 290, 'icon' => '🎲',
            'desc' => 'Win 6 games of Pesa Trail.',
            'lesson' => 'Six wins and counting means the board no longer surprises you much.',
            'mode' => 'all', 'triggers' => [['type' => 'arcade_wins', 'values' => ['6']]]],
        ['title' => 'Serious Buffer', 'level' => 6, 'xp' => 360, 'kes' => 290, 'icon' => '💵',
            'desc' => 'Keep Ksh 48,000 in your wallet balance at once.',
            'lesson' => 'A serious buffer is the difference between a bad week and a genuine emergency.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_balance', 'values' => ['48000']]]],
        ['title' => 'Any Way You Grow It', 'level' => 6, 'xp' => 432, 'kes' => 348, 'icon' => '🔀',
            'desc' => 'Reach Ksh 120,000 net worth, OR bank Ksh 6,000 in shares profit, OR win 6 Pesa Trail games.',
            'lesson' => 'Three separate ways to hit the same goal means there\'s always a path that suits you.',
            'mode' => 'any', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['120000']],
                ['type' => 'shares_profit', 'values' => ['6000']],
                ['type' => 'arcade_wins', 'values' => ['6']],
            ]],
        ['title' => 'Three Roads to More Money', 'level' => 6, 'xp' => 432, 'kes' => 348, 'icon' => '🔀',
            'desc' => 'Either grow your savings to Ksh 60,000, join a chama, or invest in an Equity Square deal.',
            'lesson' => 'Saving, group contribution, and investing all lead to more money — pick your road.',
            'mode' => 'any', 'triggers' => [['type' => 'reach_savings', 'values' => ['60000']], ['type' => 'join_chama'], ['type' => 'invest_deal']]],
        ['title' => 'Skill, Job, or Badge', 'level' => 6, 'xp' => 432, 'kes' => 348, 'icon' => '🔀',
            'desc' => 'Either finish a course, get hired, or earn a badge.',
            'lesson' => 'Any one of these is proof you\'re still actively building — that\'s what counts.',
            'mode' => 'any', 'triggers' => [['type' => 'take_course'], ['type' => 'get_job'], ['type' => 'earn_badge']]],
        ['title' => 'Triple Wealth Check', 'level' => 6, 'xp' => 522, 'kes' => 391, 'icon' => '🎯',
            'desc' => 'Reach Ksh 120,000 net worth, Ksh 6,000 shares profit, AND Ksh 48,000 cash on hand — all together.',
            'lesson' => 'Three wealth signals moving together is a much stronger sign than one alone.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['120000']],
                ['type' => 'shares_profit', 'values' => ['6000']],
                ['type' => 'reach_balance', 'values' => ['48000']],
            ]],
        ['title' => 'Player, Partner, Investor', 'level' => 6, 'xp' => 522, 'kes' => 391, 'icon' => '🎯',
            'desc' => 'Win 6 Pesa Trail games, join a chama, AND invest in an Equity Square deal.',
            'lesson' => 'Playing, partnering, and investing together builds a much fuller money skillset than any one alone.',
            'mode' => 'all', 'triggers' => [['type' => 'arcade_wins', 'values' => ['6']], ['type' => 'join_chama'], ['type' => 'invest_deal']]],
        ['title' => 'Career Pays Off', 'level' => 6, 'xp' => 522, 'kes' => 391, 'icon' => '🎯',
            'desc' => 'Finish a course, get hired, AND reach Ksh 120,000 net worth.',
            'lesson' => 'A career only "pays off" once the skill and the job actually show up in your net worth.',
            'mode' => 'all', 'triggers' => [['type' => 'take_course'], ['type' => 'get_job'], ['type' => 'reach_net_worth', 'values' => ['120000']]]],
        ['title' => 'Save, Hold, Trade', 'level' => 6, 'xp' => 522, 'kes' => 391, 'icon' => '🎯',
            'desc' => 'Grow your savings to Ksh 60,000, hold Ksh 48,000 cash, AND bank Ksh 6,000 in shares profit.',
            'lesson' => 'Saving, holding cash, and trading are three separate muscles — none of them replace the others.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_savings', 'values' => ['60000']],
                ['type' => 'reach_balance', 'values' => ['48000']],
                ['type' => 'shares_profit', 'values' => ['6000']],
            ]],
        ['title' => 'Live Well, Stay Sharp', 'level' => 6, 'xp' => 522, 'kes' => 391, 'icon' => '🎯',
            'desc' => 'Buy a vehicle, spend on a Fun World experience, AND earn a badge.',
            'lesson' => 'Enjoying your money and still building your skills aren\'t opposites — good budgeting fits both in.',
            'mode' => 'all', 'triggers' => [['type' => 'buy_item_category', 'values' => ['vehicle']], ['type' => 'fun_world_spend'], ['type' => 'earn_badge']]],

        // ══════════════════════════════════ LEVEL 7 ══════
        ['title' => 'Wealth on the Move', 'level' => 7, 'xp' => 410, 'kes' => 330, 'icon' => '📈',
            'desc' => 'Push your net worth to Ksh 180,000.',
            'lesson' => 'Wealth "on the move" means the growth rate itself is speeding up, not just the total.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_net_worth', 'values' => ['180000']]]],
        ['title' => 'Consistent Profit Taker', 'level' => 7, 'xp' => 410, 'kes' => 330, 'icon' => '💹',
            'desc' => 'Bank Ksh 9,000 in total shares profit.',
            'lesson' => 'A consistent profit-taker sells at the right time as often as they buy at the right price.',
            'mode' => 'all', 'triggers' => [['type' => 'shares_profit', 'values' => ['9000']]]],
        ['title' => 'Eight Wins Strong', 'level' => 7, 'xp' => 410, 'kes' => 330, 'icon' => '🎲',
            'desc' => 'Win 8 games of Pesa Trail.',
            'lesson' => 'Eight wins strong is a real track record, not a streak that might end any moment.',
            'mode' => 'all', 'triggers' => [['type' => 'arcade_wins', 'values' => ['8']]]],
        ['title' => 'Three Paths, One Goal', 'level' => 7, 'xp' => 492, 'kes' => 396, 'icon' => '🔀',
            'desc' => 'Reach Ksh 180,000 net worth, OR bank Ksh 9,000 shares profit, OR win 8 Pesa Trail games.',
            'lesson' => 'Different players will hit this goal through completely different routes — that\'s by design.',
            'mode' => 'any', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['180000']],
                ['type' => 'shares_profit', 'values' => ['9000']],
                ['type' => 'arcade_wins', 'values' => ['8']],
            ]],
        ['title' => 'Save, Join, or Invest', 'level' => 7, 'xp' => 492, 'kes' => 396, 'icon' => '🔀',
            'desc' => 'Either grow your savings to Ksh 90,000, join a chama, or invest in an Equity Square deal.',
            'lesson' => 'Every one of these three grows your money — pick whichever fits this week.',
            'mode' => 'any', 'triggers' => [['type' => 'reach_savings', 'values' => ['90000']], ['type' => 'join_chama'], ['type' => 'invest_deal']]],
        ['title' => 'Skill, Job, or Badge II', 'level' => 7, 'xp' => 492, 'kes' => 396, 'icon' => '🔀',
            'desc' => 'Either finish a course, get hired, or earn a badge.',
            'lesson' => 'By this stage, whichever of these three you haven\'t done yet is worth chasing next.',
            'mode' => 'any', 'triggers' => [['type' => 'take_course'], ['type' => 'get_job'], ['type' => 'earn_badge']]],
        ['title' => 'Cash, Spend, or Enjoy', 'level' => 7, 'xp' => 492, 'kes' => 396, 'icon' => '🔀',
            'desc' => 'Either hold Ksh 72,000 cash, buy a vehicle, or spend on a Fun World experience.',
            'lesson' => 'Holding, spending, and enjoying money are all valid money moves — none is automatically the "right" one.',
            'mode' => 'any', 'triggers' => [['type' => 'reach_balance', 'values' => ['72000']], ['type' => 'buy_item_category', 'values' => ['vehicle']], ['type' => 'fun_world_spend']]],
        ['title' => 'Master of Three Games', 'level' => 7, 'xp' => 594, 'kes' => 445, 'icon' => '🎯',
            'desc' => 'Reach Ksh 180,000 net worth, Ksh 9,000 shares profit, AND win 8 Pesa Trail games — all three.',
            'lesson' => 'Being genuinely strong across net worth, trading, and gameplay is a rare, well-rounded skill set.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['180000']],
                ['type' => 'shares_profit', 'values' => ['9000']],
                ['type' => 'arcade_wins', 'values' => ['8']],
            ]],
        ['title' => 'Saver, Holder, Team Player', 'level' => 7, 'xp' => 594, 'kes' => 445, 'icon' => '🎯',
            'desc' => 'Grow your savings to Ksh 90,000, hold Ksh 72,000 cash, AND join a chama.',
            'lesson' => 'Saving, holding, and group participation together build a genuinely resilient money habit.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_savings', 'values' => ['90000']],
                ['type' => 'reach_balance', 'values' => ['72000']],
                ['type' => 'join_chama'],
            ]],
        ['title' => 'Skilled and Invested', 'level' => 7, 'xp' => 594, 'kes' => 445, 'icon' => '🎯',
            'desc' => 'Finish a course, get hired, AND invest in an Equity Square deal.',
            'lesson' => 'Skill-building and investing at the same time compound faster than doing them one after another.',
            'mode' => 'all', 'triggers' => [['type' => 'take_course'], ['type' => 'get_job'], ['type' => 'invest_deal']]],
        ['title' => 'The Complete Package', 'level' => 7, 'xp' => 656, 'kes' => 495, 'icon' => '👑',
            'desc' => 'Reach Ksh 180,000 net worth, bank Ksh 9,000 shares profit, hold Ksh 72,000 cash, AND join a chama.',
            'lesson' => 'Four different signals moving together is what a genuinely "complete" financial player looks like.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['180000']],
                ['type' => 'shares_profit', 'values' => ['9000']],
                ['type' => 'reach_balance', 'values' => ['72000']],
                ['type' => 'join_chama'],
            ]],
        ['title' => 'All-Rounder', 'level' => 7, 'xp' => 656, 'kes' => 495, 'icon' => '👑',
            'desc' => 'Win 8 Pesa Trail games, finish a course, get hired, AND earn a badge.',
            'lesson' => 'Being good at the game, the classroom, and the job market all at once is genuinely rare.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'arcade_wins', 'values' => ['8']],
                ['type' => 'take_course'],
                ['type' => 'get_job'],
                ['type' => 'earn_badge'],
            ]],

        // ══════════════════════════════════ LEVEL 8 ══════
        ['title' => 'Quarter-Million Mark', 'level' => 8, 'xp' => 470, 'kes' => 380, 'icon' => '📈',
            'desc' => 'Push your net worth to Ksh 260,000.',
            'lesson' => 'By this stage, small mistakes barely register — the base is finally solid.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_net_worth', 'values' => ['260000']]]],
        ['title' => 'Sharp Profit Margin', 'level' => 8, 'xp' => 470, 'kes' => 380, 'icon' => '💹',
            'desc' => 'Bank Ksh 13,000 in total shares profit.',
            'lesson' => 'A sharp profit margin at this stage means you\'re trading with a real plan, not a hunch.',
            'mode' => 'all', 'triggers' => [['type' => 'shares_profit', 'values' => ['13000']]]],
        ['title' => 'Ten Wins on the Board', 'level' => 8, 'xp' => 470, 'kes' => 380, 'icon' => '🎲',
            'desc' => 'Win 10 games of Pesa Trail.',
            'lesson' => 'Ten wins is a genuine track record you could show anyone.',
            'mode' => 'all', 'triggers' => [['type' => 'arcade_wins', 'values' => ['10']]]],
        ['title' => 'Any Skill Counts', 'level' => 8, 'xp' => 564, 'kes' => 456, 'icon' => '🔀',
            'desc' => 'Reach Ksh 260,000 net worth, OR bank Ksh 13,000 shares profit, OR win 10 Pesa Trail games.',
            'lesson' => 'At this stage, any one of these three proves genuine financial maturity.',
            'mode' => 'any', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['260000']],
                ['type' => 'shares_profit', 'values' => ['13000']],
                ['type' => 'arcade_wins', 'values' => ['10']],
            ]],
        ['title' => 'Three Ways to Build', 'level' => 8, 'xp' => 564, 'kes' => 456, 'icon' => '🔀',
            'desc' => 'Either grow your savings to Ksh 130,000, join a chama, or invest in an Equity Square deal.',
            'lesson' => 'Building wealth rarely looks identical for two different people — that\'s expected.',
            'mode' => 'any', 'triggers' => [['type' => 'reach_savings', 'values' => ['130000']], ['type' => 'join_chama'], ['type' => 'invest_deal']]],
        ['title' => 'Skill, Job, or Badge III', 'level' => 8, 'xp' => 564, 'kes' => 456, 'icon' => '🔀',
            'desc' => 'Either finish a course, get hired, or earn a badge.',
            'lesson' => 'Continuing to grow in any of these three areas keeps your overall progress moving.',
            'mode' => 'any', 'triggers' => [['type' => 'take_course'], ['type' => 'get_job'], ['type' => 'earn_badge']]],
        ['title' => 'Four-Way Wealth Proof', 'level' => 8, 'xp' => 752, 'kes' => 570, 'icon' => '🎯',
            'desc' => 'Reach Ksh 260,000 net worth, Ksh 13,000 shares profit, Ksh 104,000 cash on hand, AND win 10 Pesa Trail games.',
            'lesson' => 'Four wealth signals aligning at once is proof, not coincidence.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['260000']],
                ['type' => 'shares_profit', 'values' => ['13000']],
                ['type' => 'reach_balance', 'values' => ['104000']],
                ['type' => 'arcade_wins', 'values' => ['10']],
            ]],
        ['title' => "Complete Saver's Portfolio", 'level' => 8, 'xp' => 752, 'kes' => 570, 'icon' => '🎯',
            'desc' => 'Grow savings to Ksh 130,000, hold Ksh 104,000 cash, join a chama, AND invest in an Equity Square deal.',
            'lesson' => 'A complete saver spreads across savings, cash, group contributions, and real investment — all four.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_savings', 'values' => ['130000']],
                ['type' => 'reach_balance', 'values' => ['104000']],
                ['type' => 'join_chama'],
                ['type' => 'invest_deal'],
            ]],
        ['title' => 'Career and Cash, Aligned', 'level' => 8, 'xp' => 752, 'kes' => 570, 'icon' => '🎯',
            'desc' => 'Finish a course, get hired, reach Ksh 260,000 net worth, AND hold Ksh 104,000 cash.',
            'lesson' => 'Career growth and cash reserves aligning means neither one is quietly falling behind the other.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'take_course'], ['type' => 'get_job'],
                ['type' => 'reach_net_worth', 'values' => ['260000']],
                ['type' => 'reach_balance', 'values' => ['104000']],
            ]],
        ['title' => 'Every Game, Mastered', 'level' => 8, 'xp' => 752, 'kes' => 570, 'icon' => '🎯',
            'desc' => 'Bank Ksh 13,000 shares profit, win 10 Pesa Trail games, join a chama, AND earn a badge.',
            'lesson' => 'Trading, gameplay, group saving, and skill-proving — mastering all four is a genuinely broad money skill.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'shares_profit', 'values' => ['13000']],
                ['type' => 'arcade_wins', 'values' => ['10']],
                ['type' => 'join_chama'],
                ['type' => 'earn_badge'],
            ]],
        ['title' => 'Living Well, Growing Smart', 'level' => 8, 'xp' => 752, 'kes' => 570, 'icon' => '🎯',
            'desc' => 'Buy a vehicle, spend on a Fun World experience, finish a course, AND earn a badge.',
            'lesson' => 'Living well today and still growing your skills for tomorrow can both fit in the same budget.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'buy_item_category', 'values' => ['vehicle']],
                ['type' => 'fun_world_spend'],
                ['type' => 'take_course'],
                ['type' => 'earn_badge'],
            ]],
        ['title' => 'Four Pillars of Wealth', 'level' => 8, 'xp' => 752, 'kes' => 570, 'icon' => '🎯',
            'desc' => 'Reach Ksh 260,000 net worth, Ksh 130,000 in savings, Ksh 13,000 shares profit, AND join a chama.',
            'lesson' => 'Net worth, savings, trading profit, and group participation are four separate pillars — build them all.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['260000']],
                ['type' => 'reach_savings', 'values' => ['130000']],
                ['type' => 'shares_profit', 'values' => ['13000']],
                ['type' => 'join_chama'],
            ]],

        // ══════════════════════════════════ LEVEL 9 ══════
        ['title' => 'Wealth With Momentum', 'level' => 9, 'xp' => 540, 'kes' => 440, 'icon' => '📈',
            'desc' => 'Push your net worth to Ksh 360,000.',
            'lesson' => 'Wealth with real momentum grows faster each level than the level before it.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_net_worth', 'values' => ['360000']]]],
        ['title' => 'Dozen Wins Club', 'level' => 9, 'xp' => 540, 'kes' => 440, 'icon' => '🎲',
            'desc' => 'Win 12 games of Pesa Trail.',
            'lesson' => 'Twelve wins puts you firmly among players who\'ve actually studied the board.',
            'mode' => 'all', 'triggers' => [['type' => 'arcade_wins', 'values' => ['12']]]],
        ['title' => 'Whichever Way Works', 'level' => 9, 'xp' => 648, 'kes' => 528, 'icon' => '🔀',
            'desc' => 'Reach Ksh 360,000 net worth, OR bank Ksh 18,000 shares profit, OR win 12 Pesa Trail games.',
            'lesson' => 'At this level, three separate proven strengths can all lead to the same milestone.',
            'mode' => 'any', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['360000']],
                ['type' => 'shares_profit', 'values' => ['18000']],
                ['type' => 'arcade_wins', 'values' => ['12']],
            ]],
        ['title' => 'Build It However', 'level' => 9, 'xp' => 648, 'kes' => 528, 'icon' => '🔀',
            'desc' => 'Either grow your savings to Ksh 180,000, join a chama, or invest in an Equity Square deal.',
            'lesson' => 'How you build the reserve matters far less than actually building it.',
            'mode' => 'any', 'triggers' => [['type' => 'reach_savings', 'values' => ['180000']], ['type' => 'join_chama'], ['type' => 'invest_deal']]],
        ['title' => 'Prove It Any Way', 'level' => 9, 'xp' => 648, 'kes' => 528, 'icon' => '🔀',
            'desc' => 'Either finish a course, get hired, or earn a badge.',
            'lesson' => 'By now, proving continued growth in any of these three ways is what matters.',
            'mode' => 'any', 'triggers' => [['type' => 'take_course'], ['type' => 'get_job'], ['type' => 'earn_badge']]],
        ['title' => 'Four Metrics, One Player', 'level' => 9, 'xp' => 864, 'kes' => 660, 'icon' => '🎯',
            'desc' => 'Reach Ksh 360,000 net worth, Ksh 18,000 shares profit, Ksh 144,000 cash, AND win 12 Pesa Trail games.',
            'lesson' => 'Four strong metrics from one player is what genuine, well-rounded financial mastery looks like.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['360000']],
                ['type' => 'shares_profit', 'values' => ['18000']],
                ['type' => 'reach_balance', 'values' => ['144000']],
                ['type' => 'arcade_wins', 'values' => ['12']],
            ]],
        ['title' => 'Fully Diversified', 'level' => 9, 'xp' => 864, 'kes' => 660, 'icon' => '🎯',
            'desc' => 'Grow savings to Ksh 180,000, join a chama, invest in a deal, AND hold Ksh 144,000 cash.',
            'lesson' => 'A fully diversified player never has all their money in just one place.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_savings', 'values' => ['180000']],
                ['type' => 'join_chama'],
                ['type' => 'invest_deal'],
                ['type' => 'reach_balance', 'values' => ['144000']],
            ]],
        ['title' => 'Career and Capital', 'level' => 9, 'xp' => 864, 'kes' => 660, 'icon' => '🎯',
            'desc' => 'Finish a course, get hired, reach Ksh 360,000 net worth, AND bank Ksh 18,000 shares profit.',
            'lesson' => 'A career and a portfolio growing side by side is a genuinely strong combination.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'take_course'], ['type' => 'get_job'],
                ['type' => 'reach_net_worth', 'values' => ['360000']],
                ['type' => 'shares_profit', 'values' => ['18000']],
            ]],
        ['title' => 'Well-Rounded Player', 'level' => 9, 'xp' => 864, 'kes' => 660, 'icon' => '🎯',
            'desc' => 'Win 12 Pesa Trail games, earn a badge, join a chama, AND finish a course.',
            'lesson' => 'A well-rounded player never lets any single skill go untouched for too long.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'arcade_wins', 'values' => ['12']],
                ['type' => 'earn_badge'],
                ['type' => 'join_chama'],
                ['type' => 'take_course'],
            ]],
        ['title' => 'Enjoying Life, Building Wealth', 'level' => 9, 'xp' => 864, 'kes' => 660, 'icon' => '🎯',
            'desc' => 'Buy a vehicle, spend on Fun World, reach Ksh 144,000 cash, AND Ksh 360,000 net worth.',
            'lesson' => 'A budget that grows wealth AND allows real enjoyment is a genuinely sustainable one.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'buy_item_category', 'values' => ['vehicle']],
                ['type' => 'fun_world_spend'],
                ['type' => 'reach_balance', 'values' => ['144000']],
                ['type' => 'reach_net_worth', 'values' => ['360000']],
            ]],
        ['title' => 'Serious Investor Status', 'level' => 9, 'xp' => 864, 'kes' => 660, 'icon' => '🎯',
            'desc' => 'Bank Ksh 18,000 shares profit, invest in a deal, grow savings to Ksh 180,000, AND reach Ksh 360,000 net worth.',
            'lesson' => 'Serious investor status means every growth channel is pulling in the same direction.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'shares_profit', 'values' => ['18000']],
                ['type' => 'invest_deal'],
                ['type' => 'reach_savings', 'values' => ['180000']],
                ['type' => 'reach_net_worth', 'values' => ['360000']],
            ]],
        ['title' => 'Almost There', 'level' => 9, 'xp' => 864, 'kes' => 660, 'icon' => '🎯',
            'desc' => 'Reach Ksh 360,000 net worth, Ksh 18,000 shares profit, 12 Pesa Trail wins, AND Ksh 180,000 in savings.',
            'lesson' => 'Four metrics this strong means the level 10 finish line is genuinely within reach.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['360000']],
                ['type' => 'shares_profit', 'values' => ['18000']],
                ['type' => 'arcade_wins', 'values' => ['12']],
                ['type' => 'reach_savings', 'values' => ['180000']],
            ]],

        // ══════════════════════════════════ LEVEL 10 ══════
        ['title' => 'Top of the Ladder', 'level' => 10, 'xp' => 620, 'kes' => 500, 'icon' => '📈',
            'desc' => 'Push your net worth to Ksh 500,000.',
            'lesson' => 'The top of this ladder is just the base of the next one — the habits carry forward.',
            'mode' => 'all', 'triggers' => [['type' => 'reach_net_worth', 'values' => ['500000']]]],
        ['title' => 'Elite Trader Status', 'level' => 10, 'xp' => 620, 'kes' => 500, 'icon' => '💹',
            'desc' => 'Bank Ksh 25,000 in total shares profit.',
            'lesson' => 'Elite trading is patience and discipline repeated, not one spectacular call.',
            'mode' => 'all', 'triggers' => [['type' => 'shares_profit', 'values' => ['25000']]]],
        ['title' => 'Any Four Paths to the Top', 'level' => 10, 'xp' => 744, 'kes' => 600, 'icon' => '🔀',
            'desc' => 'Reach Ksh 500,000 net worth, OR bank Ksh 25,000 shares profit, OR win 15 Pesa Trail games, OR join a chama.',
            'lesson' => 'By level 10, any one of these four proven strengths gets you to the top.',
            'mode' => 'any', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['500000']],
                ['type' => 'shares_profit', 'values' => ['25000']],
                ['type' => 'arcade_wins', 'values' => ['15']],
                ['type' => 'join_chama'],
            ]],
        ['title' => 'Three Ways to Finish Strong', 'level' => 10, 'xp' => 744, 'kes' => 600, 'icon' => '🔀',
            'desc' => 'Either grow your savings to Ksh 250,000, invest in an Equity Square deal, or hold Ksh 200,000 cash.',
            'lesson' => 'Finishing strong doesn\'t require doing everything — it requires doing something well.',
            'mode' => 'any', 'triggers' => [['type' => 'reach_savings', 'values' => ['250000']], ['type' => 'invest_deal'], ['type' => 'reach_balance', 'values' => ['200000']]]],
        ['title' => 'The Level 10 Standard', 'level' => 10, 'xp' => 992, 'kes' => 750, 'icon' => '🎯',
            'desc' => 'Reach Ksh 500,000 net worth, Ksh 25,000 shares profit, Ksh 200,000 cash, AND win 15 Pesa Trail games.',
            'lesson' => 'This is the level 10 standard — four strong signals, all proven at once.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['500000']],
                ['type' => 'shares_profit', 'values' => ['25000']],
                ['type' => 'reach_balance', 'values' => ['200000']],
                ['type' => 'arcade_wins', 'values' => ['15']],
            ]],
        ['title' => 'Total Financial Discipline', 'level' => 10, 'xp' => 992, 'kes' => 750, 'icon' => '🎯',
            'desc' => 'Grow savings to Ksh 250,000, join a chama, invest in a deal, AND hold Ksh 200,000 cash.',
            'lesson' => 'Total discipline means every single channel — savings, group, investment, cash — is covered.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_savings', 'values' => ['250000']],
                ['type' => 'join_chama'],
                ['type' => 'invest_deal'],
                ['type' => 'reach_balance', 'values' => ['200000']],
            ]],
        ['title' => 'Career-Built Wealth', 'level' => 10, 'xp' => 992, 'kes' => 750, 'icon' => '🎯',
            'desc' => 'Finish a course, get hired, reach Ksh 500,000 net worth, AND bank Ksh 25,000 shares profit.',
            'lesson' => 'By level 10, career and capital should be visibly reinforcing each other.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'take_course'], ['type' => 'get_job'],
                ['type' => 'reach_net_worth', 'values' => ['500000']],
                ['type' => 'shares_profit', 'values' => ['25000']],
            ]],
        ['title' => 'Master of Every Game', 'level' => 10, 'xp' => 992, 'kes' => 750, 'icon' => '🎯',
            'desc' => 'Win 15 Pesa Trail games, earn a badge, join a chama, AND finish a course.',
            'lesson' => 'Mastering every game — board, group, classroom — is the mark of a complete player.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'arcade_wins', 'values' => ['15']],
                ['type' => 'earn_badge'],
                ['type' => 'join_chama'],
                ['type' => 'take_course'],
            ]],
        ['title' => 'Rich and Living Well', 'level' => 10, 'xp' => 992, 'kes' => 750, 'icon' => '🎯',
            'desc' => 'Buy a vehicle, spend on Fun World, reach Ksh 500,000 net worth, AND Ksh 200,000 cash.',
            'lesson' => 'Real wealth includes room to enjoy life — a plan that allows zero fun rarely survives.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'buy_item_category', 'values' => ['vehicle']],
                ['type' => 'fun_world_spend'],
                ['type' => 'reach_net_worth', 'values' => ['500000']],
                ['type' => 'reach_balance', 'values' => ['200000']],
            ]],
        ['title' => 'Investor Elite', 'level' => 10, 'xp' => 992, 'kes' => 750, 'icon' => '🎯',
            'desc' => 'Bank Ksh 25,000 shares profit, invest in a deal, grow savings to Ksh 250,000, AND reach Ksh 500,000 net worth.',
            'lesson' => 'Investor elite status means every growth channel checks out, not just the loudest one.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'shares_profit', 'values' => ['25000']],
                ['type' => 'invest_deal'],
                ['type' => 'reach_savings', 'values' => ['250000']],
                ['type' => 'reach_net_worth', 'values' => ['500000']],
            ]],
        ['title' => 'Four Pillars, Perfected', 'level' => 10, 'xp' => 992, 'kes' => 750, 'icon' => '🎯',
            'desc' => 'Reach Ksh 500,000 net worth, Ksh 250,000 savings, Ksh 200,000 cash, AND Ksh 25,000 shares profit.',
            'lesson' => 'Four financial pillars, all standing at once, is what a genuinely stable player looks like.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['500000']],
                ['type' => 'reach_savings', 'values' => ['250000']],
                ['type' => 'reach_balance', 'values' => ['200000']],
                ['type' => 'shares_profit', 'values' => ['25000']],
            ]],
        ['title' => 'Pesa City Legend', 'level' => 10, 'xp' => 1116, 'kes' => 850, 'icon' => '👑',
            'desc' => 'Reach Ksh 500,000 net worth, bank Ksh 25,000 shares profit, win 15 Pesa Trail games, join a chama, AND finish a course — the full legend run.',
            'lesson' => 'A legend isn\'t someone who got lucky once — it\'s someone who was disciplined across five different money skills at the same time.',
            'mode' => 'all', 'triggers' => [
                ['type' => 'reach_net_worth', 'values' => ['500000']],
                ['type' => 'shares_profit', 'values' => ['25000']],
                ['type' => 'arcade_wins', 'values' => ['15']],
                ['type' => 'join_chama'],
                ['type' => 'take_course'],
            ]],
    ];

    public function run(): void
    {
        $created = 0;

        foreach (self::QUESTS as $i => $q) {
            Quest::updateOrCreate(
                ['title' => $q['title'], 'age_group' => self::AGE_GROUP],
                [
                    'description'    => $q['desc'],
                    'lesson'         => $q['lesson'],
                    'icon'           => $q['icon'],
                    'xp_reward'      => $q['xp'],
                    'kes_reward'     => $q['kes'],
                    'level_required' => $q['level'],
                    'age_group'      => self::AGE_GROUP,
                    'trigger_mode'   => $q['mode'],
                    'triggers'       => $q['triggers'],
                    'source'         => 'challenge_quest',
                    'is_active'      => true,
                    'sort_order'     => 600 + $i,
                ]
            );
            $created++;
        }

        $this->command->info("ChallengeQuest18to25Band2Seeder: {$created} quests upserted (" . count(self::QUESTS) . ' total, levels 4-10).');
    }
}
