<?php

namespace Database\Seeders;

use App\Models\LifeEvent;
use Illuminate\Database\Seeder;

class LifeEventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [

            // ═══════════════════════════════════════════════════════════
            // STUDENT (8–17)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'school-prize-money',
                'chapter'         => 'student',
                'title'           => 'Top Student Prize!',
                'description'     => 'You aced your exams and the school gave you a cash prize. Mum is proud.',
                'flavor_text'     => '"Angalia mtoto wangu!" — the aunts won\'t stop talking about it.',
                'educational_note'=> 'Reward yourself, then save the rest. Even Ksh 500 saved now compounds over time.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 500, 'balance_max' => 2000],
                'probability'     => 0.015,
                'icon'            => '🏆',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'pocket-money-bonus',
                'chapter'         => 'student',
                'title'           => 'Extra Pocket Money',
                'description'     => 'Uncle came to visit and slipped you some notes. No questions asked.',
                'flavor_text'     => 'Relatives who give money are God\'s greatest gift.',
                'educational_note'=> 'Windfalls are an opportunity to practice saving. Try saving at least half.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 200, 'balance_max' => 1000],
                'probability'     => 0.020,
                'icon'            => '💸',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'phone-smashed',
                'chapter'         => 'student',
                'title'           => 'Phone Smashed at Sportsday',
                'description'     => 'You dropped your phone running the 400m relay. The screen is a cobweb.',
                'flavor_text'     => '"Sikujua mwili wangu unaweza kwenda hivyo haraka" — and now the phone knows too.',
                'educational_note'=> 'Gadgets depreciate fast and can break suddenly. Insurance and savings cushions exist for exactly this.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -3000, 'balance_max' => -500],
                'probability'     => 0.008,
                'icon'            => '📱',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'holiday-job',
                'chapter'         => 'student',
                'title'           => 'Holiday Job Secured',
                'description'     => 'You found a December holiday job delivering flyers and doing errands. Early hustle.',
                'flavor_text'     => 'Every billionaire started somewhere. Some started with flyers.',
                'educational_note'=> 'Part-time income during school builds financial muscle early. What you save now costs nothing and compounds forever.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 2000, 'balance_max' => 6000],
                'probability'     => 0.012,
                'icon'            => '🛵',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'school-trip-cost',
                'chapter'         => 'student',
                'title'           => 'School Trip Fee Due',
                'description'     => 'The class is going to Nairobi National Park and the fee is compulsory.',
                'flavor_text'     => '"Wote tutakwenda" — the teacher\'s face says otherwise if you don\'t pay.',
                'educational_note'=> 'Unexpected expenses happen even at a young age. Always keep a small emergency reserve.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -2000, 'balance_max' => -500],
                'probability'     => 0.012,
                'icon'            => '🦁',
                'is_positive'     => false,
                'is_active'       => true,
            ],

            [
                'slug'            => 'form-four-graduation-gift',
                'chapter'         => 'student',
                'title'           => 'KCSE Done — Graduation Gifts',
                'description'     => 'You finished your final exams. Aunties, uncles, and family friends showed up with envelopes.',
                'flavor_text'     => '"Umefika mbali mtoto" — every relative says it, every relative pays for it.',
                'educational_note'=> 'A one-time windfall like this is a perfect seed for a savings account you\'ll actually keep growing.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 1000, 'balance_max' => 4000],
                'probability'     => 0.010,
                'icon'            => '🎓',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'sold-old-textbooks',
                'chapter'         => 'student',
                'title'           => 'Sold Last Year\'s Textbooks',
                'description'     => 'You sold your old textbooks and revision guides to the juniors coming up behind you.',
                'flavor_text'     => 'One student\'s clutter is another student\'s exam survival kit.',
                'educational_note'=> 'Selling things you no longer need is free money hiding in plain sight — always worth doing before buying new.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 300, 'balance_max' => 1200],
                'probability'     => 0.018,
                'icon'            => '📚',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'harambee-contribution-call',
                'chapter'         => 'student',
                'title'           => 'Class Harambee for a Sick Classmate',
                'description'     => 'A classmate\'s family needs help with hospital bills. The class rep is collecting contributions today.',
                'flavor_text'     => '"Mgonjwa wa jirani ni mgonjwa wako" — nobody in class hesitates.',
                'educational_note'=> 'Giving to community harambees is a Kenyan financial norm — budget a small "generosity" line so it never derails your own savings.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -800, 'balance_max' => -200],
                'probability'     => 0.014,
                'icon'            => '🤲',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'lost-transport-money',
                'chapter'         => 'student',
                'title'           => 'Lost Your Bus Fare',
                'description'     => 'Your pocket had a hole in it — literally. The fare for the week is gone and you had to walk home.',
                'flavor_text'     => '"Miguu ni gari ya bure" — but your legs are tired now.',
                'educational_note'=> 'Small daily amounts like transport fare deserve their own safe pocket, not loose change in a pocket with holes.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -300, 'balance_max' => -100],
                'probability'     => 0.016,
                'icon'            => '🚌',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'weekend-market-helper',
                'chapter'         => 'student',
                'title'           => 'Weekend Market Helper',
                'description'     => 'You helped a family friend run their stall at the weekend market — carrying, arranging, calling out prices.',
                'flavor_text'     => 'A day of shouting prices teaches you more about business than a whole textbook chapter.',
                'educational_note'=> 'Any paid work — even a single weekend — is real income experience. Track it, save part of it, and notice how it feels to earn.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 400, 'balance_max' => 1500],
                'probability'     => 0.014,
                'icon'            => '🛍️',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // GRADUATE (18–22)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'first-salary-increment',
                'chapter'         => 'graduate',
                'title'           => 'Salary Increment!',
                'description'     => 'Your probation period is over and your boss dropped a revised offer letter on your desk. You made it.',
                'flavor_text'     => '"Salary ni ya commitment, increment ni ya performance." — your mentor said it. You lived it.',
                'educational_note'=> 'Avoid lifestyle inflation. When your salary goes up, raise your savings rate — not just your spending.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 5000, 'balance_max' => 18000],
                'probability'     => 0.018,
                'icon'            => '📈',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'freelance-gig',
                'chapter'         => 'graduate',
                'title'           => 'Freelance Project Won',
                'description'     => 'A friend referred you for a website redesign project. You quoted, delivered, and got paid.',
                'flavor_text'     => '"Side hustle ni side door" — every main income started small.',
                'educational_note'=> 'Freelance income is irregular — save 30% for when it dries up and 20% for taxes.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 8000, 'balance_max' => 35000],
                'probability'     => 0.015,
                'icon'            => '💻',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'medical-emergency-graduate',
                'chapter'         => 'graduate',
                'title'           => 'Medical Emergency',
                'description'     => 'You ended up in hospital with typhoid. The bill is waiting at reception.',
                'flavor_text'     => '"Maji ya kuchemsha iko wapi?" — the question you\'re asking yourself now.',
                'educational_note'=> 'Medical emergencies are the #1 cause of financial ruin in Kenya for young adults. NHIF and private cover are not optional.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -35000, 'balance_max' => -5000, 'credit' => -10],
                'probability'     => 0.010,
                'icon'            => '🏥',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'rent-increase',
                'chapter'         => 'graduate',
                'title'           => 'Landlord Raised Rent',
                'description'     => 'A notice was slipped under your door. "Effective next month, rent increases by 15%." No warning.',
                'flavor_text'     => '"Nairobi rents go up. Salaries think about it first."',
                'educational_note'=> 'Renting means your biggest expense is outside your control. This is why building towards ownership matters.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -3000, 'balance_max' => -1000, 'credit' => 0],
                'probability'     => 0.012,
                'icon'            => '🏠',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'chama-dividend',
                'chapter'         => 'graduate',
                'title'           => 'Chama Dividend Paid Out',
                'description'     => 'Your chama (investment group) held its year-end meeting and declared dividends. Your share is ready.',
                'flavor_text'     => '"Chama ni nguvu ya pamoja" — collective investing beats going alone.',
                'educational_note'=> 'Chamas are a powerful Kenyan savings vehicle. Rotating savings gives access to lump sums no individual could save alone.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 3000, 'balance_max' => 12000],
                'probability'     => 0.014,
                'icon'            => '🤝',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            [
                'slug'            => 'internship-stipend',
                'chapter'         => 'graduate',
                'title'           => 'Internship Stipend Cleared',
                'description'     => 'The internship pays a modest stipend, but it just landed and it\'s yours.',
                'flavor_text'     => '"Uzoefu wa kwanza ni pesa kidogo, lakini ni pesa" — first experience is small money, but it\'s still money.',
                'educational_note'=> 'A stipend feels small next to a "real" salary, but treating it seriously — budgeting and saving from it — builds habits your future salary will thank you for.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 3000, 'balance_max' => 10000],
                'probability'     => 0.016,
                'icon'            => '📄',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'certification-course-cost',
                'chapter'         => 'graduate',
                'title'           => 'Professional Certification Fee',
                'description'     => 'A certification your industry actually respects is open for enrollment — but the fee is due upfront.',
                'flavor_text'     => '"Cheti ni ufunguo" — a certificate is a key, but keys cost money to cut.',
                'educational_note'=> 'Spending on a credential is an investment, not a cost, IF it genuinely raises your earning ceiling — check that before paying.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -12000, 'balance_max' => -3000],
                'probability'     => 0.010,
                'icon'            => '📜',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'first-payslip-shock',
                'chapter'         => 'graduate',
                'title'           => 'First Payslip Shock',
                'description'     => 'PAYE, NHIF, NSSF, and a housing levy all took their cut before the money even reached your account.',
                'flavor_text'     => '"Gross ni story, net ndio ukweli" — gross salary is a story, net pay is the truth.',
                'educational_note'=> 'Always budget from your NET pay, never your gross salary — statutory deductions are not optional and catch every first-time employee off guard.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -6000, 'balance_max' => -1500, 'credit' => 0],
                'probability'     => 0.014,
                'icon'            => '🧾',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'referral-bonus',
                'chapter'         => 'graduate',
                'title'           => 'Employee Referral Bonus',
                'description'     => 'You referred a friend for an open role. They got hired and passed probation — your referral bonus just cleared.',
                'flavor_text'     => 'Helping a friend land a job and getting paid for it — rare double win.',
                'educational_note'=> 'Referral bonuses are effectively free money for a five-minute recommendation. Always ask if your employer offers one.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 2000, 'balance_max' => 8000],
                'probability'     => 0.012,
                'icon'            => '🤝',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'selling-clothes-online',
                'chapter'         => 'graduate',
                'title'           => 'Thrift Reselling Side Income',
                'description'     => 'You\'ve been reselling thrifted clothes online in your spare time. This month\'s batch sold out fast.',
                'flavor_text'     => '"Mtumba leo, biashara kesho" — thrift today, business tomorrow.',
                'educational_note'=> 'Small resale hustles are a low-capital way to practice buying, pricing, and selling — real business skills with real (if modest) money.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 2500, 'balance_max' => 9000],
                'probability'     => 0.013,
                'icon'            => '👕',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // HUSTLER (23–28)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'promotion-hustler',
                'chapter'         => 'hustler',
                'title'           => 'Promoted to Senior Role',
                'description'     => 'Your manager called you in, closed the door, and pushed a new contract across the desk.',
                'flavor_text'     => '"The meeting your calendar says is cancelled is the one that changes your life."',
                'educational_note'=> 'A salary jump is a chance to restructure — increase savings/investments proportionally, not just lifestyle.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 15000, 'balance_max' => 50000],
                'probability'     => 0.014,
                'icon'            => '🚀',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'business-break-in',
                'chapter'         => 'hustler',
                'title'           => 'Business Broken Into',
                'description'     => 'Your shop was broken into overnight. Stock gone, lock broken, and the CCTV footage is blurry.',
                'flavor_text'     => '"Hakuna mtu aliyeambia business inakuwa rahisi." — and now you believe them.',
                'educational_note'=> 'Business insurance protects against exactly this. The premium is small compared to one bad night.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -60000, 'balance_max' => -15000, 'credit' => -15],
                'probability'     => 0.008,
                'icon'            => '🔓',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'side-hustle-viral',
                'chapter'         => 'hustler',
                'title'           => 'Side Hustle Went Viral',
                'description'     => 'You posted something online and woke up to 50 DMs. Orders are flooding in.',
                'flavor_text'     => '"Nairobi Twitter ni marketing budget gani?" — zero shillings can change everything.',
                'educational_note'=> 'Viral moments create income spikes. Save the surplus; it may not last. Invest it into systems that do.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 25000, 'balance_max' => 90000],
                'probability'     => 0.006,
                'icon'            => '🔥',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'car-breakdown',
                'chapter'         => 'hustler',
                'title'           => 'Car Breakdown on Thika Road',
                'description'     => 'Engine warning light. Smoke. Tow truck. Mechanic quote that made you sit down slowly.',
                'flavor_text'     => '"Gear box." Two words. The most expensive two words in Swahili.',
                'educational_note'=> 'Vehicles always need a maintenance reserve. Set aside 5-10% of the car\'s value annually for servicing and repairs.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -55000, 'balance_max' => -8000],
                'probability'     => 0.012,
                'icon'            => '🔧',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'job-retrenchment',
                'chapter'         => 'hustler',
                'title'           => 'Retrenched — Company Downsizing',
                'description'     => 'HR called everyone into the boardroom. Some people came out with boxes. You were one of them.',
                'flavor_text'     => '"It\'s not personal, it\'s business." — it very much felt personal.',
                'educational_note'=> 'A 6-month emergency fund protects you through job loss. It\'s not paranoia — retrenchments happen to good people.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -30000, 'balance_max' => -5000, 'credit' => -25],
                'probability'     => 0.007,
                'icon'            => '📦',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'nse-bull-run-hustler',
                'chapter'         => 'hustler',
                'title'           => 'NSE Bull Run!',
                'description'     => 'The Nairobi Securities Exchange surged this quarter. Your portfolio is smiling.',
                'flavor_text'     => '"Buy when there\'s blood in the streets." — you bought earlier, you\'re smiling now.',
                'educational_note'=> 'Bull markets feel great, but they end. Resist the urge to over-invest at peaks. Rebalance instead.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'investment', 'pct' => 0.16]]],
                'probability'     => 0.010,
                'icon'            => '📈',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            [
                'slug'            => 'matatu-sacco-shares',
                'chapter'         => 'hustler',
                'title'           => 'Matatu Sacco Dividend',
                'description'     => 'You bought shares in a matatu Sacco two years ago. The AGM just declared a solid dividend.',
                'flavor_text'     => '"Sacco ni akiba ya jamii" — a Sacco is a community\'s savings, paying you back.',
                'educational_note'=> 'Sacco shares combine savings discipline with real returns — a cornerstone of Kenyan middle-class wealth building.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 6000, 'balance_max' => 22000],
                'probability'     => 0.010,
                'icon'            => '🚐',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'pos-machine-fraud',
                'chapter'         => 'hustler',
                'title'           => 'POS Chargeback Fraud',
                'description'     => 'A customer disputed a card payment days after taking the goods. The bank reversed the transaction from your account.',
                'flavor_text'     => '"Pesa ilikuwa imeonekana, sasa imepotea" — the money was there, now it\'s gone.',
                'educational_note'=> 'Card chargebacks are a real business risk — verify big transactions and keep receipts as proof of delivery.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -18000, 'balance_max' => -4000],
                'probability'     => 0.007,
                'icon'            => '💳',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'business-rent-arrears-demand',
                'chapter'         => 'hustler',
                'title'           => 'Shop Rent Arrears Demand',
                'description'     => 'A slow month meant you fell behind on shop rent. The landlord\'s agent is at the door with a final notice.',
                'flavor_text'     => '"Kodi haingoji biashara kupata pesa" — rent doesn\'t wait for business to make money.',
                'educational_note'=> 'Fixed costs like rent keep running even in slow months — a 1-2 month buffer specifically for rent protects the whole business.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -25000, 'balance_max' => -6000, 'credit' => -10],
                'probability'     => 0.009,
                'icon'            => '🏪',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'content-ad-revenue',
                'chapter'         => 'hustler',
                'title'           => 'Content Ad Revenue Payout',
                'description'     => 'Your videos crossed the monetization threshold. The first ad revenue payout landed in your account.',
                'flavor_text'     => '"Views leo, malipo kesho" — views today, payout tomorrow.',
                'educational_note'=> 'Platform ad revenue is unpredictable month to month — treat it as bonus income, not a guaranteed salary replacement.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 8000, 'balance_max' => 40000],
                'probability'     => 0.008,
                'icon'            => '🎥',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'generator-breakdown',
                'chapter'         => 'hustler',
                'title'           => 'Generator Died Mid-Shift',
                'description'     => 'A KPLC blackout hit right at peak hours, and then your backup generator refused to start. Sales stopped cold.',
                'flavor_text'     => '"Stima ikienda, akiba lazima iwepo" — when power goes, a backup plan must exist.',
                'educational_note'=> 'Equipment failure during peak hours costs twice — the repair AND the lost sales. Maintenance schedules are cheaper than emergencies.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -20000, 'balance_max' => -5000, 'credit' => 0],
                'probability'     => 0.009,
                'icon'            => '🔌',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'wholesale-bulk-discount-deal',
                'chapter'         => 'hustler',
                'title'           => 'Bulk Stock Deal',
                'description'     => 'A wholesaler offered a one-time bulk discount if you bought now. You took the deal and resold at your usual margin.',
                'flavor_text'     => '"Ununuzi wa jumla, faida ya jumla" — buy wholesale, profit wholesale.',
                'educational_note'=> 'Buying in bulk at a discount only pays off if you can actually move the stock — cash tied up in unsold inventory isn\'t profit yet.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 10000, 'balance_max' => 35000],
                'probability'     => 0.009,
                'icon'            => '📦',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // SETTLER (29–40)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'tenant-ghosted',
                'chapter'         => 'settler',
                'title'           => 'Tenant Disappeared',
                'description'     => 'You went to check the rental unit. Padlock changed, phone off, no deposit returned.',
                'flavor_text'     => '"Usidanganywe na smile ya first showing." — the landlord\'s prayer.',
                'educational_note'=> 'Tenant screening (ID, employment verification, reference check) is not optional. One bad tenant costs months of income.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -45000, 'balance_max' => -10000, 'credit' => -10],
                'probability'     => 0.010,
                'icon'            => '🚪',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'property-boom',
                'chapter'         => 'settler',
                'title'           => 'Real Estate Boom',
                'description'     => 'Infrastructure expansion and population growth pushed property values up across Nairobi this season.',
                'flavor_text'     => '"Ardhi haina bei ya chini — only up." — every property owner, every year.',
                'educational_note'=> 'Property appreciation builds generational wealth. But illiquidity means you can\'t access gains without selling or borrowing.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'property', 'pct' => 0.12]]],
                'probability'     => 0.012,
                'icon'            => '🏗️',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'government-tender',
                'chapter'         => 'settler',
                'title'           => 'Won a Government Tender',
                'description'     => 'Your company was awarded a county government supply contract. Payment terms are net-30.',
                'flavor_text'     => '"Tender ni pesa. Pesa ya serikali ni pesa nzuri zaidi."',
                'educational_note'=> 'Government contracts are lucrative but slow to pay. Working capital management is critical — don\'t spend the contract before you\'re paid.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 80000, 'balance_max' => 250000],
                'probability'     => 0.006,
                'icon'            => '📋',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'business-partner-dispute',
                'chapter'         => 'settler',
                'title'           => 'Business Partner Dispute',
                'description'     => 'Things went bad with your co-founder. Lawyers. Shouting. A split that cost everyone.',
                'flavor_text'     => '"Biashara na rafiki hazioani" — sometimes the proverb is right.',
                'educational_note'=> 'A signed shareholders\' agreement protects you before disputes happen. Legal documents are not pessimism — they\'re professionalism.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => -0.28]]],
                'probability'     => 0.008,
                'icon'            => '⚖️',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'chama-large-payout',
                'chapter'         => 'settler',
                'title'           => 'Chama Mega Payout',
                'description'     => 'Years of contributions. The chama\'s investment matured and your share is significant.',
                'flavor_text'     => '"Subira huvuta heri." — patience brings blessings.',
                'educational_note'=> 'Long-running investment groups create wealth through consistency. The power is not the amount saved each month — it\'s the years of discipline.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 30000, 'balance_max' => 120000],
                'probability'     => 0.010,
                'icon'            => '💰',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'new-family-costs',
                'chapter'         => 'settler',
                'title'           => 'Family Growing — New Expenses',
                'description'     => 'School fees, medical, food. The family budget just levelled up.',
                'flavor_text'     => '"Watoto ni baraka" — and also a line item in the budget.',
                'educational_note'=> 'Family financial planning is a skill. Budget for education, healthcare, and childcare as fixed costs, not surprises.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -20000, 'balance_max' => -8000, 'credit' => -5],
                'probability'     => 0.012,
                'icon'            => '👨‍👩‍👧',
                'is_positive'     => false,
                'is_active'       => true,
            ],

            [
                'slug'            => 'sacco-expansion-loan',
                'chapter'         => 'settler',
                'title'           => 'Sacco Loan Approved',
                'description'     => 'Your Sacco approved a low-interest loan against your accumulated shares — enough to expand the business properly.',
                'flavor_text'     => '"Sacco haikuachi mwanachama akiwa na dhamira nzuri" — a Sacco doesn\'t abandon a member with a solid plan.',
                'educational_note'=> 'Borrowing against your own savings (a Sacco share-backed loan) is often far cheaper than a bank loan — use member benefits fully.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 40000, 'balance_max' => 150000],
                'probability'     => 0.009,
                'icon'            => '🏦',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'shilling-devaluation-import-costs',
                'chapter'         => 'settler',
                'title'           => 'Shilling Weakens — Import Costs Up',
                'description'     => 'The shilling slid against the dollar this quarter. Everything you import for the business just got pricier.',
                'flavor_text'     => '"Dola ikipanda, kila kitu kinapanda" — when the dollar rises, everything rises with it.',
                'educational_note'=> 'Currency risk is real for any business relying on imports — hedging or diversifying suppliers reduces exposure to swings you can\'t control.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => -0.09]]],
                'probability'     => 0.008,
                'icon'            => '💱',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'second-rental-unit-built',
                'chapter'         => 'settler',
                'title'           => 'Second Rental Unit Complete',
                'description'     => 'Construction on your second rental unit finished on budget. Tenants moved in within two weeks.',
                'flavor_text'     => '"Nyumba moja leo, mbili kesho" — one house today, two tomorrow.',
                'educational_note'=> 'Each additional income-generating property compounds your passive income — the second one is always easier to finance than the first.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 15000, 'balance_max' => 45000],
                'probability'     => 0.008,
                'icon'            => '🏘️',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'county-permit-fee-hike',
                'chapter'         => 'settler',
                'title'           => 'County Business Permit Hike',
                'description'     => 'The county government revised its single business permit fees upward — effective immediately, no phase-in.',
                'flavor_text'     => '"Serikali ya county nayo ina bajeti" — county government has a budget to fill too.',
                'educational_note'=> 'Regulatory costs change without warning — budgeting a small annual buffer for licenses and permits avoids a cash-flow shock.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -8000, 'balance_max' => -2000],
                'probability'     => 0.011,
                'icon'            => '📋',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'diaspora-relative-investment',
                'chapter'         => 'settler',
                'title'           => 'Diaspora Relative Invests',
                'description'     => 'A relative working abroad wants to co-invest in your next venture and wired their share already.',
                'flavor_text'     => '"Pesa ya diaspora inajenga Kenya" — diaspora money is building Kenya, one project at a time.',
                'educational_note'=> 'Family investment partnerships work best with clear written terms from day one — protect the relationship by protecting the agreement.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 50000, 'balance_max' => 180000],
                'probability'     => 0.006,
                'icon'            => '✈️',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'flood-damage-rental-property',
                'chapter'         => 'settler',
                'title'           => 'Flooding Damages Rental Unit',
                'description'     => 'Unusually heavy rains flooded the ground-floor unit. Tenants moved out temporarily while repairs happen.',
                'flavor_text'     => '"Mvua haiulizi ruhusa" — rain doesn\'t ask permission before it comes.',
                'educational_note'=> 'Property insurance covering weather damage is not a luxury for landlords — the cost of a policy is small next to a full repair bill.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -35000, 'balance_max' => -8000, 'credit' => 0],
                'probability'     => 0.007,
                'icon'            => '🌊',
                'is_positive'     => false,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // BUILDER (41–55)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'kra-audit',
                'chapter'         => 'builder',
                'title'           => 'KRA Tax Audit',
                'description'     => 'KRA sent a notice. Your accounts are being reviewed. Interest and penalties apply.',
                'flavor_text'     => '"iTax ni simu inayoita bila schedule." — and you always have to pick up.',
                'educational_note'=> 'Keep clean financial records every year. Tax compliance is cheaper than audits — penalties and interest can wipe out a year\'s profit.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -120000, 'balance_max' => -25000, 'credit' => -20],
                'probability'     => 0.008,
                'icon'            => '📊',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'nse-major-bull',
                'chapter'         => 'builder',
                'title'           => 'NSE Multi-Year High',
                'description'     => 'The NSE hit its highest point in 6 years. Your portfolio is up significantly.',
                'flavor_text'     => '"Long term investing is boring until it isn\'t."',
                'educational_note'=> 'Markets reward patience. Investors who stayed through downturns always outperform those who panicked and sold.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'investment', 'pct' => 0.20]]],
                'probability'     => 0.008,
                'icon'            => '🚀',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'key-employee-left',
                'chapter'         => 'builder',
                'title'           => 'Key Employee Resigned',
                'description'     => 'Your best operations manager left for a competitor. With them went half your clients.',
                'flavor_text'     => '"Ujuzi wa mfanyakazi ni mali ya kampuni" — until they walk.',
                'educational_note'=> 'Businesses too dependent on one person are fragile. Document processes, share knowledge, and compensate key talent to retain them.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => -0.18]]],
                'probability'     => 0.010,
                'icon'            => '🏃',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'rental-income-boom',
                'chapter'         => 'builder',
                'title'           => 'Rental Market Surge',
                'description'     => 'Demand for units in your area surged. You raised rents across all your properties.',
                'flavor_text'     => '"Ardhi haizaliani, lakini inazaa pesa." — land doesn\'t reproduce, but it produces money.',
                'educational_note'=> 'Passive income from property scales with market conditions. Location choice made years ago creates income today.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'property', 'pct' => 0.09]]],
                'probability'     => 0.012,
                'icon'            => '🏢',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'private-equity-exit',
                'chapter'         => 'builder',
                'title'           => 'Private Equity Exit',
                'description'     => 'The fund you backed 5 years ago exited via acquisition. Your multiple: 3.8×.',
                'flavor_text'     => '"Patient capital creates patient wealth."',
                'educational_note'=> 'Private equity returns are lumpy — nothing for years, then a large exit. Liquidity planning matters: don\'t invest money you need.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 300000, 'balance_max' => 1200000],
                'probability'     => 0.005,
                'icon'            => '💎',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            [
                'slug'            => 'ipo-allocation-windfall',
                'chapter'         => 'builder',
                'title'           => 'IPO Share Allocation',
                'description'     => 'You applied for an IPO allocation months ago. The shares were allotted and listed above the offer price.',
                'flavor_text'     => '"Kuomba mapema, kupata mapema" — apply early, receive early.',
                'educational_note'=> 'IPO gains are exciting but not guaranteed — many listings trade below their offer price. Never invest money you can\'t afford to see drop.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 60000, 'balance_max' => 220000],
                'probability'     => 0.006,
                'icon'            => '📃',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'succession-planning-legal-fees',
                'chapter'         => 'builder',
                'title'           => 'Succession Planning Underway',
                'description'     => 'You finally hired a lawyer to formalize a succession and estate plan for the business and property you\'ve built.',
                'flavor_text'     => '"Mali bila mpango ni mali ya ugomvi" — wealth without a plan becomes wealth people fight over.',
                'educational_note'=> 'Legal fees for succession planning are an investment in family peace — the alternative is often years of costly, painful disputes.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -60000, 'balance_max' => -15000],
                'probability'     => 0.006,
                'icon'            => '⚖️',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'commercial-plot-value-surge',
                'chapter'         => 'builder',
                'title'           => 'Commercial Plot Value Surges',
                'description'     => 'A new bypass road was gazetted right past your commercial plot. Valuers are suddenly very interested.',
                'flavor_text'     => '"Barabara ikija, thamani ya ardhi hupanda" — where the road goes, land value follows.',
                'educational_note'=> 'Infrastructure-driven appreciation is one of the few genuinely predictable property plays — buying ahead of planned development pays off for patient investors.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'property', 'pct' => 0.18]]],
                'probability'     => 0.007,
                'icon'            => '🛣️',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'partner-loan-default-risk',
                'chapter'         => 'builder',
                'title'           => 'Business Partner\'s Loan Default',
                'description'     => 'A joint-collateral loan your business partner took out went into default. The bank is now looking at your shared assets.',
                'flavor_text'     => '"Dhamana ya pamoja ni hatari ya pamoja" — shared collateral is shared risk.',
                'educational_note'=> 'Co-signing or joint collateral ties your financial fate to someone else\'s decisions — enter these arrangements with extreme caution and legal clarity.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => -0.14]]],
                'probability'     => 0.006,
                'icon'            => '📉',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'reit-dividend-payout',
                'chapter'         => 'builder',
                'title'           => 'REIT Unit Dividend',
                'description'     => 'The Real Estate Investment Trust units you hold declared their semi-annual dividend today.',
                'flavor_text'     => '"Unamiliki jengo bila kubeba tofali" — you own a piece of the building without carrying a single brick.',
                'educational_note'=> 'REITs let you earn property-style income without managing tenants directly — genuine diversification for a property-heavy portfolio.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 12000, 'balance_max' => 50000],
                'probability'     => 0.010,
                'icon'            => '🏢',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // ELDER (56+)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'pension-matured',
                'chapter'         => 'elder',
                'title'           => 'Pension Fund Matured',
                'description'     => 'Decades of NSSF contributions and employer pension top-ups finally paid out. A lump sum arrived.',
                'flavor_text'     => '"Miaka ya kazi imekuwa pesa." — years of work became money.',
                'educational_note'=> 'Pensions work because contributions compound for decades. Starting early multiplies the final payout enormously.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 300000, 'balance_max' => 800000],
                'probability'     => 0.015,
                'icon'            => '🌅',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'elder-medical-costs',
                'chapter'         => 'elder',
                'title'           => 'Rising Medical Costs',
                'description'     => 'Routine check-ups, specialist visits, medication. Healthcare in your 60s is a major budget item.',
                'flavor_text'     => '"Afya ni mali" — and now you are paying for it.',
                'educational_note'=> 'Healthcare costs rise sharply after 55. Planning for medical expenses in retirement is as important as planning for food.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -150000, 'balance_max' => -30000, 'credit' => -5],
                'probability'     => 0.018,
                'icon'            => '💊',
                'is_positive'     => false,
                'is_active'       => true,
            ],

            [
                'slug'            => 'grandchildren-school-fees-support',
                'chapter'         => 'elder',
                'title'           => 'Helping With Grandchildren\'s Fees',
                'description'     => 'Your grandchildren\'s school fees deadline came around and the family looked to you to help close the gap.',
                'flavor_text'     => '"Babu na nyanya ni mfuko wa dharura wa familia" — grandparents are the family\'s emergency fund.',
                'educational_note'=> 'Supporting the next generation is meaningful, but retirees should budget it deliberately — not at the expense of their own care needs.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -40000, 'balance_max' => -8000],
                'probability'     => 0.014,
                'icon'            => '🎒',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'annuity-payout-begins',
                'chapter'         => 'elder',
                'title'           => 'Annuity Payments Begin',
                'description'     => 'The annuity you purchased at retirement started its first scheduled payout — steady income, right on time.',
                'flavor_text'     => '"Mpango wa zamani, faida ya sasa" — an old plan, a present benefit.',
                'educational_note'=> 'Annuities convert a lump sum into guaranteed income for life — the trade-off (giving up the lump sum) is exactly what protects you from outliving your savings.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 25000, 'balance_max' => 90000],
                'probability'     => 0.016,
                'icon'            => '📆',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'home-modification-costs',
                'chapter'         => 'elder',
                'title'           => 'Home Accessibility Modifications',
                'description'     => 'Stairs are harder to manage these days. You had ramps and grab rails fitted around the house.',
                'flavor_text'     => '"Nyumba lazima ibadilike na mwenye nyumba" — a home must change as its owner does.',
                'educational_note'=> 'Aging-in-place modifications are a real, predictable retirement expense — budgeting for them early avoids a rushed, costlier fix later.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -30000, 'balance_max' => -6000],
                'probability'     => 0.012,
                'icon'            => '🏡',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'family-land-subdivision-sale',
                'chapter'         => 'elder',
                'title'           => 'Sold a Subdivided Plot',
                'description'     => 'You subdivided a portion of the family land and sold one plot, keeping the rest for the family.',
                'flavor_text'     => '"Shamba kubwa, faida ndogo ndogo" — a big shamba, sold in small useful pieces.',
                'educational_note'=> 'Land held for decades is often a retiree\'s largest asset — selling a portion, rather than all of it, balances liquidity today with legacy for tomorrow.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 200000, 'balance_max' => 700000],
                'probability'     => 0.009,
                'icon'            => '🌾',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // ALL CHAPTERS — Market & Universal Events
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'nse-market-crash',
                'chapter'         => 'all',
                'title'           => 'NSE Market Crash',
                'description'     => 'Global uncertainty triggered a sell-off on the Nairobi Securities Exchange. Portfolios are down.',
                'flavor_text'     => '"Soko la hisa si ATM" — but some people learned this the hard way today.',
                'educational_note'=> 'Market crashes are normal and temporary. Investors who hold through crashes always recover — those who sell lock in the loss.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'investment', 'pct' => -0.22]]],
                'probability'     => 0.007,
                'icon'            => '📉',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'economic-downturn',
                'chapter'         => 'all',
                'title'           => 'Economic Slowdown',
                'description'     => 'Consumer spending dropped. Businesses tightened. The economy entered a rough patch.',
                'flavor_text'     => '"Uchumi umejificha" — the economy is hiding.',
                'educational_note'=> 'Recessions are the time to cut unnecessary expenses, maintain your emergency fund, and avoid panic selling.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'investment', 'pct' => -0.15], ['category' => 'business', 'pct' => -0.10]]],
                'probability'     => 0.006,
                'icon'            => '🌧️',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'tourism-boom',
                'chapter'         => 'all',
                'title'           => 'Tourism Boom Season',
                'description'     => 'A combination of great weather, security, and viral content put Kenya on every travel list.',
                'flavor_text'     => '"Kenya is open for business" — and the businesses feel it.',
                'educational_note'=> 'Sector booms create business income spikes. Diversifying across sectors means you\'re always exposed to the one growing.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => 0.10]]],
                'probability'     => 0.009,
                'icon'            => '🦒',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'long-rains-disruption',
                'chapter'         => 'all',
                'title'           => 'Long Rains Damage',
                'description'     => 'The April rains were unusually heavy. Roads flooded. Stock spoiled. Business disrupted.',
                'flavor_text'     => '"Mvua ya April ni baraka na balaa kwa wakati mmoja."',
                'educational_note'=> 'Seasonal disruptions are predictable in Kenya. Businesses should maintain a 2-3 month cash buffer for slow seasons.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => -0.07]]],
                'probability'     => 0.015,
                'icon'            => '🌧️',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'mpesa-cashback',
                'chapter'         => 'all',
                'title'           => 'Safaricom M-PESA Cashback',
                'description'     => 'Safaricom ran a promotion and your account got a surprise cashback based on your transaction history.',
                'flavor_text'     => '"Bonga Points, Cashback, Promotions — Safaricom hukuacha."',
                'educational_note'=> 'Small rewards add up. Track every cashback and bonus — redirect them to savings, not impulse spending.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 200, 'balance_max' => 1500],
                'probability'     => 0.025,
                'icon'            => '📲',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'fuel-price-hike',
                'chapter'         => 'all',
                'title'           => 'Fuel Prices Spiked',
                'description'     => 'EPRA revised pump prices upward sharply. Transport and logistics costs followed.',
                'flavor_text'     => '"Petrol imeongezeka" — the headline that changes everyone\'s morning.',
                'educational_note'=> 'Fuel price changes ripple through every cost in the economy. Owning a fuel-efficient vehicle or using public transport cushions this impact.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -3000, 'balance_max' => -800, 'credit' => 0],
                'probability'     => 0.015,
                'icon'            => '⛽',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'interest-rate-hike',
                'chapter'         => 'all',
                'title'           => 'Central Bank Raises Rates',
                'description'     => 'The Central Bank of Kenya raised its base lending rate this quarter to fight inflation. Bond prices and loan costs both moved.',
                'flavor_text'     => '"CBK ikipiga print, kila mtu anasikia" — when the Central Bank moves, everyone feels it eventually.',
                'educational_note'=> 'Rising interest rates make new borrowing costlier but also make new fixed-income investments pay more — the same move helps savers and hurts borrowers at once.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'investment', 'pct' => -0.05]]],
                'probability'     => 0.010,
                'icon'            => '🏛️',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'diaspora-remittance-surprise',
                'chapter'         => 'all',
                'title'           => 'Surprise Remittance From Abroad',
                'description'     => 'A relative working abroad sent an unexpected transfer — "just because," the message said.',
                'flavor_text'     => '"Diaspora haisahau nyumbani" — the diaspora never forgets home.',
                'educational_note'=> 'Remittances are one of Kenya\'s largest sources of household income nationally — treat an unexpected one exactly like any other windfall: save first, spend second.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 1500, 'balance_max' => 12000],
                'probability'     => 0.014,
                'icon'            => '💌',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'data-bundle-price-war',
                'chapter'         => 'all',
                'title'           => 'Telecom Data Price War',
                'description'     => 'Competing telcos slashed data bundle prices trying to win subscribers. Your monthly connectivity bill just dropped.',
                'flavor_text'     => '"Ushindani ni faida ya mteja" — competition is the customer\'s gain.',
                'educational_note'=> 'When a recurring cost drops, redirect the saving into savings or investments immediately — otherwise it quietly disappears into other spending.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 150, 'balance_max' => 900],
                'probability'     => 0.020,
                'icon'            => '📶',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'insurance-claim-dispute',
                'chapter'         => 'all',
                'title'           => 'Insurance Claim Disputed',
                'description'     => 'You filed a legitimate claim after a loss, but the insurer is dragging its feet and disputing part of the payout.',
                'flavor_text'     => '"Bima ni sawa mpaka siku ya kudai" — insurance is fine, until the day you actually need to claim.',
                'educational_note'=> 'Read policy exclusions BEFORE you need to claim, and keep every receipt and photo — documentation is what turns a dispute into a payout.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -22000, 'balance_max' => -4000, 'credit' => -5],
                'probability'     => 0.008,
                'icon'            => '📑',
                'is_positive'     => false,
                'is_active'       => true,
            ],
        ];

        foreach ($events as $data) {
            LifeEvent::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
