<?php

namespace Database\Seeders;

use App\Models\LifeEvent;
use Illuminate\Database\Seeder;

class LifeEventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [

            // ═══════════════════════════════════════════════════════════
            // STUDENT (8–17)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'school-prize-money',
                'chapter'         => 'student',
                'title'           => 'Top Student Prize!',
                'description'     => 'You aced your exams and the school gave you a cash prize. Mum is proud.',
                'flavor_text'     => '"Angalia mtoto wangu!" — the aunts won\'t stop talking about it.',
                'educational_note'=> 'Reward yourself, then save the rest. Even Ksh 500 saved now compounds over time.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 500, 'balance_max' => 2000],
                'probability'     => 0.015,
                'icon'            => '🏆',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'pocket-money-bonus',
                'chapter'         => 'student',
                'title'           => 'Extra Pocket Money',
                'description'     => 'Uncle came to visit and slipped you some notes. No questions asked.',
                'flavor_text'     => 'Relatives who give money are God\'s greatest gift.',
                'educational_note'=> 'Windfalls are an opportunity to practice saving. Try saving at least half.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 200, 'balance_max' => 1000],
                'probability'     => 0.020,
                'icon'            => '💸',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'phone-smashed',
                'chapter'         => 'student',
                'title'           => 'Phone Smashed at Sportsday',
                'description'     => 'You dropped your phone running the 400m relay. The screen is a cobweb.',
                'flavor_text'     => '"Sikujua mwili wangu unaweza kwenda hivyo haraka" — and now the phone knows too.',
                'educational_note'=> 'Gadgets depreciate fast and can break suddenly. Insurance and savings cushions exist for exactly this.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -3000, 'balance_max' => -500],
                'probability'     => 0.008,
                'icon'            => '📱',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'holiday-job',
                'chapter'         => 'student',
                'title'           => 'Holiday Job Secured',
                'description'     => 'You found a December holiday job delivering flyers and doing errands. Early hustle.',
                'flavor_text'     => 'Every billionaire started somewhere. Some started with flyers.',
                'educational_note'=> 'Part-time income during school builds financial muscle early. What you save now costs nothing and compounds forever.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 2000, 'balance_max' => 6000],
                'probability'     => 0.012,
                'icon'            => '🛵',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'school-trip-cost',
                'chapter'         => 'student',
                'title'           => 'School Trip Fee Due',
                'description'     => 'The class is going to Nairobi National Park and the fee is compulsory.',
                'flavor_text'     => '"Wote tutakwenda" — the teacher\'s face says otherwise if you don\'t pay.',
                'educational_note'=> 'Unexpected expenses happen even at a young age. Always keep a small emergency reserve.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -2000, 'balance_max' => -500],
                'probability'     => 0.012,
                'icon'            => '🦁',
                'is_positive'     => false,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // GRADUATE (18–22)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'first-salary-increment',
                'chapter'         => 'graduate',
                'title'           => 'Salary Increment!',
                'description'     => 'Your probation period is over and your boss dropped a revised offer letter on your desk. You made it.',
                'flavor_text'     => '"Salary ni ya commitment, increment ni ya performance." — your mentor said it. You lived it.',
                'educational_note'=> 'Avoid lifestyle inflation. When your salary goes up, raise your savings rate — not just your spending.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 5000, 'balance_max' => 18000],
                'probability'     => 0.018,
                'icon'            => '📈',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'freelance-gig',
                'chapter'         => 'graduate',
                'title'           => 'Freelance Project Won',
                'description'     => 'A friend referred you for a website redesign project. You quoted, delivered, and got paid.',
                'flavor_text'     => '"Side hustle ni side door" — every main income started small.',
                'educational_note'=> 'Freelance income is irregular — save 30% for when it dries up and 20% for taxes.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 8000, 'balance_max' => 35000],
                'probability'     => 0.015,
                'icon'            => '💻',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'medical-emergency-graduate',
                'chapter'         => 'graduate',
                'title'           => 'Medical Emergency',
                'description'     => 'You ended up in hospital with typhoid. The bill is waiting at reception.',
                'flavor_text'     => '"Maji ya kuchemsha iko wapi?" — the question you\'re asking yourself now.',
                'educational_note'=> 'Medical emergencies are the #1 cause of financial ruin in Kenya for young adults. NHIF and private cover are not optional.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -35000, 'balance_max' => -5000, 'credit' => -10],
                'probability'     => 0.010,
                'icon'            => '🏥',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'rent-increase',
                'chapter'         => 'graduate',
                'title'           => 'Landlord Raised Rent',
                'description'     => 'A notice was slipped under your door. "Effective next month, rent increases by 15%." No warning.',
                'flavor_text'     => '"Nairobi rents go up. Salaries think about it first."',
                'educational_note'=> 'Renting means your biggest expense is outside your control. This is why building towards ownership matters.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -3000, 'balance_max' => -1000, 'credit' => 0],
                'probability'     => 0.012,
                'icon'            => '🏠',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'chama-dividend',
                'chapter'         => 'graduate',
                'title'           => 'Chama Dividend Paid Out',
                'description'     => 'Your chama (investment group) held its year-end meeting and declared dividends. Your share is ready.',
                'flavor_text'     => '"Chama ni nguvu ya pamoja" — collective investing beats going alone.',
                'educational_note'=> 'Chamas are a powerful Kenyan savings vehicle. Rotating savings gives access to lump sums no individual could save alone.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 3000, 'balance_max' => 12000],
                'probability'     => 0.014,
                'icon'            => '🤝',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // HUSTLER (23–28)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'promotion-hustler',
                'chapter'         => 'hustler',
                'title'           => 'Promoted to Senior Role',
                'description'     => 'Your manager called you in, closed the door, and pushed a new contract across the desk.',
                'flavor_text'     => '"The meeting your calendar says is cancelled is the one that changes your life."',
                'educational_note'=> 'A salary jump is a chance to restructure — increase savings/investments proportionally, not just lifestyle.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 15000, 'balance_max' => 50000],
                'probability'     => 0.014,
                'icon'            => '🚀',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'business-break-in',
                'chapter'         => 'hustler',
                'title'           => 'Business Broken Into',
                'description'     => 'Your shop was broken into overnight. Stock gone, lock broken, and the CCTV footage is blurry.',
                'flavor_text'     => '"Hakuna mtu aliyeambia business inakuwa rahisi." — and now you believe them.',
                'educational_note'=> 'Business insurance protects against exactly this. The premium is small compared to one bad night.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -60000, 'balance_max' => -15000, 'credit' => -15],
                'probability'     => 0.008,
                'icon'            => '🔓',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'side-hustle-viral',
                'chapter'         => 'hustler',
                'title'           => 'Side Hustle Went Viral',
                'description'     => 'You posted something online and woke up to 50 DMs. Orders are flooding in.',
                'flavor_text'     => '"Nairobi Twitter ni marketing budget gani?" — zero shillings can change everything.',
                'educational_note'=> 'Viral moments create income spikes. Save the surplus; it may not last. Invest it into systems that do.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 25000, 'balance_max' => 90000],
                'probability'     => 0.006,
                'icon'            => '🔥',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'car-breakdown',
                'chapter'         => 'hustler',
                'title'           => 'Car Breakdown on Thika Road',
                'description'     => 'Engine warning light. Smoke. Tow truck. Mechanic quote that made you sit down slowly.',
                'flavor_text'     => '"Gear box." Two words. The most expensive two words in Swahili.',
                'educational_note'=> 'Vehicles always need a maintenance reserve. Set aside 5-10% of the car\'s value annually for servicing and repairs.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => -55000, 'balance_max' => -8000],
                'probability'     => 0.012,
                'icon'            => '🔧',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'job-retrenchment',
                'chapter'         => 'hustler',
                'title'           => 'Retrenched — Company Downsizing',
                'description'     => 'HR called everyone into the boardroom. Some people came out with boxes. You were one of them.',
                'flavor_text'     => '"It\'s not personal, it\'s business." — it very much felt personal.',
                'educational_note'=> 'A 6-month emergency fund protects you through job loss. It\'s not paranoia — retrenchments happen to good people.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -30000, 'balance_max' => -5000, 'credit' => -25],
                'probability'     => 0.007,
                'icon'            => '📦',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'nse-bull-run-hustler',
                'chapter'         => 'hustler',
                'title'           => 'NSE Bull Run!',
                'description'     => 'The Nairobi Securities Exchange surged this quarter. Your portfolio is smiling.',
                'flavor_text'     => '"Buy when there\'s blood in the streets." — you bought earlier, you\'re smiling now.',
                'educational_note'=> 'Bull markets feel great, but they end. Resist the urge to over-invest at peaks. Rebalance instead.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'investment', 'pct' => 0.16]]],
                'probability'     => 0.010,
                'icon'            => '📈',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // SETTLER (29–40)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'tenant-ghosted',
                'chapter'         => 'settler',
                'title'           => 'Tenant Disappeared',
                'description'     => 'You went to check the rental unit. Padlock changed, phone off, no deposit returned.',
                'flavor_text'     => '"Usidanganywe na smile ya first showing." — the landlord\'s prayer.',
                'educational_note'=> 'Tenant screening (ID, employment verification, reference check) is not optional. One bad tenant costs months of income.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -45000, 'balance_max' => -10000, 'credit' => -10],
                'probability'     => 0.010,
                'icon'            => '🚪',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'property-boom',
                'chapter'         => 'settler',
                'title'           => 'Real Estate Boom',
                'description'     => 'Infrastructure expansion and population growth pushed property values up across Nairobi this season.',
                'flavor_text'     => '"Ardhi haina bei ya chini — only up." — every property owner, every year.',
                'educational_note'=> 'Property appreciation builds generational wealth. But illiquidity means you can\'t access gains without selling or borrowing.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'property', 'pct' => 0.12]]],
                'probability'     => 0.012,
                'icon'            => '🏗️',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'government-tender',
                'chapter'         => 'settler',
                'title'           => 'Won a Government Tender',
                'description'     => 'Your company was awarded a county government supply contract. Payment terms are net-30.',
                'flavor_text'     => '"Tender ni pesa. Pesa ya serikali ni pesa nzuri zaidi."',
                'educational_note'=> 'Government contracts are lucrative but slow to pay. Working capital management is critical — don\'t spend the contract before you\'re paid.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 80000, 'balance_max' => 250000],
                'probability'     => 0.006,
                'icon'            => '📋',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'business-partner-dispute',
                'chapter'         => 'settler',
                'title'           => 'Business Partner Dispute',
                'description'     => 'Things went bad with your co-founder. Lawyers. Shouting. A split that cost everyone.',
                'flavor_text'     => '"Biashara na rafiki hazioani" — sometimes the proverb is right.',
                'educational_note'=> 'A signed shareholders\' agreement protects you before disputes happen. Legal documents are not pessimism — they\'re professionalism.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => -0.28]]],
                'probability'     => 0.008,
                'icon'            => '⚖️',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'chama-large-payout',
                'chapter'         => 'settler',
                'title'           => 'Chama Mega Payout',
                'description'     => 'Years of contributions. The chama\'s investment matured and your share is significant.',
                'flavor_text'     => '"Subira huvuta heri." — patience brings blessings.',
                'educational_note'=> 'Long-running investment groups create wealth through consistency. The power is not the amount saved each month — it\'s the years of discipline.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 30000, 'balance_max' => 120000],
                'probability'     => 0.010,
                'icon'            => '💰',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'new-family-costs',
                'chapter'         => 'settler',
                'title'           => 'Family Growing — New Expenses',
                'description'     => 'School fees, medical, food. The family budget just levelled up.',
                'flavor_text'     => '"Watoto ni baraka" — and also a line item in the budget.',
                'educational_note'=> 'Family financial planning is a skill. Budget for education, healthcare, and childcare as fixed costs, not surprises.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -20000, 'balance_max' => -8000, 'credit' => -5],
                'probability'     => 0.012,
                'icon'            => '👨‍👩‍👧',
                'is_positive'     => false,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // BUILDER (41–55)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'kra-audit',
                'chapter'         => 'builder',
                'title'           => 'KRA Tax Audit',
                'description'     => 'KRA sent a notice. Your accounts are being reviewed. Interest and penalties apply.',
                'flavor_text'     => '"iTax ni simu inayoita bila schedule." — and you always have to pick up.',
                'educational_note'=> 'Keep clean financial records every year. Tax compliance is cheaper than audits — penalties and interest can wipe out a year\'s profit.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -120000, 'balance_max' => -25000, 'credit' => -20],
                'probability'     => 0.008,
                'icon'            => '📊',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'nse-major-bull',
                'chapter'         => 'builder',
                'title'           => 'NSE Multi-Year High',
                'description'     => 'The NSE hit its highest point in 6 years. Your portfolio is up significantly.',
                'flavor_text'     => '"Long term investing is boring until it isn\'t."',
                'educational_note'=> 'Markets reward patience. Investors who stayed through downturns always outperform those who panicked and sold.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'investment', 'pct' => 0.20]]],
                'probability'     => 0.008,
                'icon'            => '🚀',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'key-employee-left',
                'chapter'         => 'builder',
                'title'           => 'Key Employee Resigned',
                'description'     => 'Your best operations manager left for a competitor. With them went half your clients.',
                'flavor_text'     => '"Ujuzi wa mfanyakazi ni mali ya kampuni" — until they walk.',
                'educational_note'=> 'Businesses too dependent on one person are fragile. Document processes, share knowledge, and compensate key talent to retain them.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => -0.18]]],
                'probability'     => 0.010,
                'icon'            => '🏃',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'rental-income-boom',
                'chapter'         => 'builder',
                'title'           => 'Rental Market Surge',
                'description'     => 'Demand for units in your area surged. You raised rents across all your properties.',
                'flavor_text'     => '"Ardhi haizaliani, lakini inazaa pesa." — land doesn\'t reproduce, but it produces money.',
                'educational_note'=> 'Passive income from property scales with market conditions. Location choice made years ago creates income today.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'property', 'pct' => 0.09]]],
                'probability'     => 0.012,
                'icon'            => '🏢',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'private-equity-exit',
                'chapter'         => 'builder',
                'title'           => 'Private Equity Exit',
                'description'     => 'The fund you backed 5 years ago exited via acquisition. Your multiple: 3.8×.',
                'flavor_text'     => '"Patient capital creates patient wealth."',
                'educational_note'=> 'Private equity returns are lumpy — nothing for years, then a large exit. Liquidity planning matters: don\'t invest money you need.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 300000, 'balance_max' => 1200000],
                'probability'     => 0.005,
                'icon'            => '💎',
                'is_positive'     => true,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // ELDER (56+)
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'pension-matured',
                'chapter'         => 'elder',
                'title'           => 'Pension Fund Matured',
                'description'     => 'Decades of NSSF contributions and employer pension top-ups finally paid out. A lump sum arrived.',
                'flavor_text'     => '"Miaka ya kazi imekuwa pesa." — years of work became money.',
                'educational_note'=> 'Pensions work because contributions compound for decades. Starting early multiplies the final payout enormously.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 300000, 'balance_max' => 800000],
                'probability'     => 0.015,
                'icon'            => '🌅',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'elder-medical-costs',
                'chapter'         => 'elder',
                'title'           => 'Rising Medical Costs',
                'description'     => 'Routine check-ups, specialist visits, medication. Healthcare in your 60s is a major budget item.',
                'flavor_text'     => '"Afya ni mali" — and now you are paying for it.',
                'educational_note'=> 'Healthcare costs rise sharply after 55. Planning for medical expenses in retirement is as important as planning for food.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -150000, 'balance_max' => -30000, 'credit' => -5],
                'probability'     => 0.018,
                'icon'            => '💊',
                'is_positive'     => false,
                'is_active'       => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // ALL CHAPTERS — Market & Universal Events
            // ═══════════════════════════════════════════════════════════
            [
                'slug'            => 'nse-market-crash',
                'chapter'         => 'all',
                'title'           => 'NSE Market Crash',
                'description'     => 'Global uncertainty triggered a sell-off on the Nairobi Securities Exchange. Portfolios are down.',
                'flavor_text'     => '"Soko la hisa si ATM" — but some people learned this the hard way today.',
                'educational_note'=> 'Market crashes are normal and temporary. Investors who hold through crashes always recover — those who sell lock in the loss.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'investment', 'pct' => -0.22]]],
                'probability'     => 0.007,
                'icon'            => '📉',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'economic-downturn',
                'chapter'         => 'all',
                'title'           => 'Economic Slowdown',
                'description'     => 'Consumer spending dropped. Businesses tightened. The economy entered a rough patch.',
                'flavor_text'     => '"Uchumi umejificha" — the economy is hiding.',
                'educational_note'=> 'Recessions are the time to cut unnecessary expenses, maintain your emergency fund, and avoid panic selling.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'investment', 'pct' => -0.15], ['category' => 'business', 'pct' => -0.10]]],
                'probability'     => 0.006,
                'icon'            => '🌧️',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'tourism-boom',
                'chapter'         => 'all',
                'title'           => 'Tourism Boom Season',
                'description'     => 'A combination of great weather, security, and viral content put Kenya on every travel list.',
                'flavor_text'     => '"Kenya is open for business" — and the businesses feel it.',
                'educational_note'=> 'Sector booms create business income spikes. Diversifying across sectors means you\'re always exposed to the one growing.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => 0.10]]],
                'probability'     => 0.009,
                'icon'            => '🦒',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'long-rains-disruption',
                'chapter'         => 'all',
                'title'           => 'Long Rains Damage',
                'description'     => 'The April rains were unusually heavy. Roads flooded. Stock spoiled. Business disrupted.',
                'flavor_text'     => '"Mvua ya April ni baraka na balaa kwa wakati mmoja."',
                'educational_note'=> 'Seasonal disruptions are predictable in Kenya. Businesses should maintain a 2-3 month cash buffer for slow seasons.',
                'effect_type'     => 'market_event',
                'effect_data'     => ['market_categories' => [['category' => 'business', 'pct' => -0.07]]],
                'probability'     => 0.015,
                'icon'            => '🌧️',
                'is_positive'     => false,
                'is_active'       => true,
            ],
            [
                'slug'            => 'mpesa-cashback',
                'chapter'         => 'all',
                'title'           => 'Safaricom M-PESA Cashback',
                'description'     => 'Safaricom ran a promotion and your account got a surprise cashback based on your transaction history.',
                'flavor_text'     => '"Bonga Points, Cashback, Promotions — Safaricom hukuacha."',
                'educational_note'=> 'Small rewards add up. Track every cashback and bonus — redirect them to savings, not impulse spending.',
                'effect_type'     => 'balance_delta',
                'effect_data'     => ['balance_min' => 200, 'balance_max' => 1500],
                'probability'     => 0.025,
                'icon'            => '📲',
                'is_positive'     => true,
                'is_active'       => true,
            ],
            [
                'slug'            => 'fuel-price-hike',
                'chapter'         => 'all',
                'title'           => 'Fuel Prices Spiked',
                'description'     => 'EPRA revised pump prices upward sharply. Transport and logistics costs followed.',
                'flavor_text'     => '"Petrol imeongezeka" — the headline that changes everyone\'s morning.',
                'educational_note'=> 'Fuel price changes ripple through every cost in the economy. Owning a fuel-efficient vehicle or using public transport cushions this impact.',
                'effect_type'     => 'compound',
                'effect_data'     => ['balance_min' => -3000, 'balance_max' => -800, 'credit' => 0],
                'probability'     => 0.015,
                'icon'            => '⛽',
                'is_positive'     => false,
                'is_active'       => true,
            ],
        ];

        foreach ($events as $data) {
            LifeEvent::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
