<?php

namespace Database\Seeders;

use App\Models\Quest;
use Illuminate\Database\Seeder;

class QuestExpansion18to25Band1Seeder extends Seeder
{
    public function run(): void
    {
        $quests = [

            // ══════════════════════════════════════════ LEVEL 1 ══════════════════════════════════════════
            [
                'title'          => 'Shares of Confidence',
                'description'    => 'Buy your first share on the Market. Ownership starts with one unit.',
                'icon'           => '📊',
                'xp_reward'      => 115,
                'kes_reward'     => 95,
                'level_required' => 1,
                'trigger_type'   => 'buy_share',
                'trigger_value'  => null,
                'trigger_label'  => 'Buy any share on the Market',
                'lesson'         => 'Buying one share is how every investor starts — the amount matters less than building the habit of putting money to work instead of letting it sit idle.',
                'sort_order'     => 11,
            ],
            [
                'title'          => 'First Business Brick',
                'description'    => 'Buy a business-category asset from the Marketplace — your first stake in someone\'s enterprise.',
                'icon'           => '🧱',
                'xp_reward'      => 130,
                'kes_reward'     => 110,
                'level_required' => 1,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'business',
                'trigger_label'  => 'Buy a business-category asset',
                'lesson'         => 'A business asset (like a kiosk stake or a piece of equipment) earns income from activity, not just price growth — a different kind of wealth than a car or phone.',
                'sort_order'     => 12,
            ],
            [
                'title'          => 'Wallet Check-In',
                'description'    => 'Grow your wallet balance to Ksh 3,000. Know your number before you spend it.',
                'icon'           => '👛',
                'xp_reward'      => 110,
                'kes_reward'     => 90,
                'level_required' => 1,
                'trigger_type'   => 'reach_balance',
                'trigger_value'  => '3000',
                'trigger_label'  => 'Grow your wallet to Ksh 3,000',
                'lesson'         => 'Checking your actual balance regularly — not guessing — is the single habit that separates people who budget from people who just hope.',
                'sort_order'     => 13,
            ],
            [
                'title'          => 'Fun Money, Planned Money',
                'description'    => 'Spend something in Fun World. A budget with zero fun in it rarely survives contact with real life.',
                'icon'           => '🎢',
                'xp_reward'      => 105,
                'kes_reward'     => 85,
                'level_required' => 1,
                'trigger_type'   => 'fun_world_spend',
                'trigger_value'  => null,
                'trigger_label'  => 'Spend on any Fun World activity',
                'lesson'         => 'A budget that bans every small pleasure gets abandoned fast — the trick is a planned "fun" line, not a zero one.',
                'sort_order'     => 14,
            ],
            [
                'title'          => 'Wheel of Fortune Kickoff',
                'description'    => 'Take a spin on the Lucky Wheel. Small risk, real lesson about luck versus a plan.',
                'icon'           => '🎡',
                'xp_reward'      => 120,
                'kes_reward'     => 100,
                'level_required' => 1,
                'trigger_type'   => 'spin_wheel',
                'trigger_value'  => null,
                'trigger_label'  => 'Spin the Lucky Wheel',
                'lesson'         => 'A lucky win feels the same as a planned one in the moment — but only one of them shows up again next month.',
                'sort_order'     => 15,
            ],
            [
                'title'          => 'Study, Then Save',
                'description'    => 'Complete Financial Literacy 101, then put the lesson to work: deposit Ksh 1,000 into savings.',
                'icon'           => '📘',
                'xp_reward'      => 168,
                'kes_reward'     => 140,
                'level_required' => 1,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'take_course',     'values' => ['financial-literacy-101'], 'label' => 'Complete Financial Literacy 101'],
                    ['type' => 'deposit_savings', 'values' => ['1000'],                    'label' => 'Deposit Ksh 1,000 into savings'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'Knowledge that never turns into an action is just trivia — the deposit is what makes the lesson real.',
                'sort_order'     => 16,
            ],
            [
                'title'          => 'Circle of Support',
                'description'    => 'Join a chama. Pooled money and peer pressure both work in your favour.',
                'icon'           => '🤝',
                'xp_reward'      => 135,
                'kes_reward'     => 115,
                'level_required' => 1,
                'trigger_type'   => 'join_chama',
                'trigger_value'  => null,
                'trigger_label'  => 'Join a chama',
                'lesson'         => 'A chama makes saving a social contract, not just a private intention — much harder to quietly skip.',
                'sort_order'     => 17,
            ],

            // ══════════════════════════════════════════ LEVEL 2 ══════════════════════════════════════════
            [
                'title'          => 'Deal Maker Debut',
                'description'    => 'Put money into an Equity Square investment deal. Real businesses, real returns, real risk.',
                'icon'           => '🤵',
                'xp_reward'      => 165,
                'kes_reward'     => 145,
                'level_required' => 2,
                'trigger_type'   => 'invest_deal',
                'trigger_value'  => null,
                'trigger_label'  => 'Invest in any Equity Square deal',
                'lesson'         => 'A deal is a bet on a specific business, not a diversified fund — read the terms before the excitement of "in on the ground floor" takes over.',
                'sort_order'     => 21,
            ],
            [
                'title'          => 'Fixed and Safe',
                'description'    => 'Put money into a fixed-income asset, then grow your wallet to Ksh 5,000 on top of it.',
                'icon'           => '🏛️',
                'xp_reward'      => 224,
                'kes_reward'     => 196,
                'level_required' => 2,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'buy_item_category', 'values' => ['fixed_income'], 'label' => 'Buy an MMF, T-Bill, or T-Bond'],
                    ['type' => 'reach_balance',      'values' => ['5000'],         'label' => 'Grow your wallet to Ksh 5,000'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'A fixed-income asset pays a predictable, government-or-fund-backed return — the boring, reliable base every portfolio needs before the exciting bets.',
                'sort_order'     => 22,
            ],
            [
                'title'          => 'Gadget Upgrade',
                'description'    => 'Buy a gadget-category asset that can actually earn you money, not just look nice.',
                'icon'           => '📱',
                'xp_reward'      => 150,
                'kes_reward'     => 130,
                'level_required' => 2,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'gadget',
                'trigger_label'  => 'Buy a gadget-category asset',
                'lesson'         => 'The right tool (a phone for gigs, a laptop for freelancing) pays for itself if it opens up income — the wrong one is just a depreciating toy.',
                'sort_order'     => 23,
            ],
            [
                'title'          => 'Savings Streak Level 2',
                'description'    => 'Grow your total savings to Ksh 6,000. Consistency, not luck.',
                'icon'           => '📈',
                'xp_reward'      => 175,
                'kes_reward'     => 155,
                'level_required' => 2,
                'trigger_type'   => 'reach_savings',
                'trigger_value'  => '6000',
                'trigger_label'  => 'Grow your total savings to Ksh 6,000',
                'lesson'         => 'Ksh 6,000 saved steadily beats a bigger one-off windfall spent carelessly — the habit compounds even when the amount looks small.',
                'sort_order'     => 24,
            ],
            [
                'title'          => 'A Story Worth Living',
                'description'    => 'Play through a life-decision scenario and see where your choice leads.',
                'icon'           => '📖',
                'xp_reward'      => 145,
                'kes_reward'     => 125,
                'level_required' => 2,
                'trigger_type'   => 'play_scenario',
                'trigger_value'  => '',
                'trigger_label'  => 'Play any life-decision scenario',
                'lesson'         => 'Every scenario is a low-stakes rehearsal for a real decision you\'ll eventually face with real money on the line.',
                'sort_order'     => 25,
            ],
            [
                'title'          => 'Level Chaser',
                'description'    => 'Reach player Level 3, then grow your wallet to Ksh 8,000 to prove the level-up wasn\'t a fluke.',
                'icon'           => '⭐',
                'xp_reward'      => 225,
                'kes_reward'     => 195,
                'level_required' => 2,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'reach_level',  'values' => ['3'],    'label' => 'Reach Level 3'],
                    ['type' => 'reach_balance', 'values' => ['8000'], 'label' => 'Grow your wallet to Ksh 8,000'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'Leveling up feels good, but the number that actually matters is what\'s left in your wallet once the celebration is over.',
                'sort_order'     => 26,
            ],
            [
                'title'          => 'First Real Job',
                'description'    => 'Get hired for any job at the Opportunity Hub. Steady income changes everything else you can do.',
                'icon'           => '💼',
                'xp_reward'      => 180,
                'kes_reward'     => 160,
                'level_required' => 2,
                'trigger_type'   => 'get_job',
                'trigger_value'  => null,
                'trigger_label'  => 'Get hired for any job',
                'lesson'         => 'Investing without income is fragile — a steady paycheck is what lets you take real financial risks elsewhere.',
                'sort_order'     => 27,
            ],

            // ══════════════════════════════════════════ LEVEL 3 ══════════════════════════════════════════
            [
                'title'          => 'Property Curious',
                'description'    => 'Buy a property-category asset. Real estate is the classic long game.',
                'icon'           => '🏠',
                'xp_reward'      => 195,
                'kes_reward'     => 175,
                'level_required' => 3,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'property',
                'trigger_label'  => 'Buy a property-category asset',
                'lesson'         => 'Property is illiquid — you can\'t cash it out overnight — but it\'s historically one of the steadiest stores of value for patient money.',
                'sort_order'     => 31,
            ],
            [
                'title'          => 'Vehicle Value',
                'description'    => 'Buy a vehicle-category asset that can earn you fares, deliveries, or hire income.',
                'icon'           => '🏍️',
                'xp_reward'      => 205,
                'kes_reward'     => 180,
                'level_required' => 3,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'vehicle',
                'trigger_label'  => 'Buy a vehicle-category asset',
                'lesson'         => 'A vehicle only pays for itself if it\'s working most days — an idle asset just accumulates costs and depreciation with nothing to show for it.',
                'sort_order'     => 32,
            ],
            [
                'title'          => 'Share Portfolio Grows',
                'description'    => 'Buy another share. One position is luck; a portfolio is a plan.',
                'icon'           => '📊',
                'xp_reward'      => 185,
                'kes_reward'     => 165,
                'level_required' => 3,
                'trigger_type'   => 'buy_share',
                'trigger_value'  => null,
                'trigger_label'  => 'Buy any share on the Market',
                'lesson'         => 'Holding more than one share spreads your risk — if one company has a bad week, your whole net worth doesn\'t move with it.',
                'sort_order'     => 33,
            ],
            [
                'title'          => 'Net Worth Ascend',
                'description'    => 'Push your net worth past Ksh 20,000. Assets and savings, minus what you owe.',
                'icon'           => '📈',
                'xp_reward'      => 210,
                'kes_reward'     => 190,
                'level_required' => 3,
                'trigger_type'   => 'reach_net_worth',
                'trigger_value'  => '20000',
                'trigger_label'  => 'Push your net worth past Ksh 20,000',
                'lesson'         => 'Net worth — not income, not wallet cash — is the real financial scoreboard, because it accounts for what you owe too.',
                'sort_order'     => 34,
            ],
            [
                'title'          => 'Deal Number Two',
                'description'    => 'Invest in another Equity Square deal. Spreading bets is a strategy, not indecision.',
                'icon'           => '🤵',
                'xp_reward'      => 175,
                'kes_reward'     => 150,
                'level_required' => 3,
                'trigger_type'   => 'invest_deal',
                'trigger_value'  => null,
                'trigger_label'  => 'Invest in any Equity Square deal',
                'lesson'         => 'One deal going bad shouldn\'t sink your whole plan — a second, unrelated deal is how professionals manage that risk.',
                'sort_order'     => 35,
            ],
            [
                'title'          => 'Scenario Sense',
                'description'    => 'Play another life-decision scenario, then grow your savings to Ksh 10,000.',
                'icon'           => '📖',
                'xp_reward'      => 266,
                'kes_reward'     => 238,
                'level_required' => 3,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'play_scenario', 'values' => [],       'label' => 'Play any life-decision scenario'],
                    ['type' => 'reach_savings', 'values' => ['10000'], 'label' => 'Grow your total savings to Ksh 10,000'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'The scenarios rehearse the decision; the savings target proves you\'d actually follow through with real money.',
                'sort_order'     => 36,
            ],
            [
                'title'          => 'Badge in Hand',
                'description'    => 'Earn any badge in Pesa City — proof your habits are being noticed, not just felt.',
                'icon'           => '🏅',
                'xp_reward'      => 200,
                'kes_reward'     => 180,
                'level_required' => 3,
                'trigger_type'   => 'earn_badge',
                'trigger_value'  => '',
                'trigger_label'  => 'Earn any badge',
                'lesson'         => 'A badge is a lagging indicator — by the time you earn one, the good habit behind it is already working for you.',
                'sort_order'     => 37,
            ],
        ];

        foreach ($quests as $data) {
            Quest::updateOrCreate(
                ['title' => $data['title']],
                $data + ['is_active' => true, 'age_group' => '18-25']
            );
        }
    }
}
