<?php

namespace Database\Seeders;

use App\Models\Quest;
use Illuminate\Database\Seeder;

class QuestExpansion18to25Band2Seeder extends Seeder
{
    public function run(): void
    {
        $quests = [

            // ── Level 4 ──────────────────────────────────────────────────────
            [
                'title'          => 'First Page of the Portfolio',
                'description'    => 'Buy your first business-category asset from the Marketplace — a stake in someone else\'s hustle instead of just your own paycheck.',
                'icon'           => '🏗️',
                'xp_reward'      => 210,
                'kes_reward'     => 190,
                'level_required' => 4,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'business',
                'trigger_label'  => 'Buy any business asset 🏗️',
                'lesson'         => 'Business assets can pay you monthly income even while you sleep — that\'s the real difference between a job and an investment.',
                'sort_order'     => 41,
            ],
            [
                'title'          => 'First Trade',
                'description'    => 'Buy your first share on the NSE floor. One share is enough — the point is crossing the line from saver to shareholder.',
                'icon'           => '📈',
                'xp_reward'      => 230,
                'kes_reward'     => 210,
                'level_required' => 4,
                'trigger_type'   => 'buy_share',
                'trigger_value'  => '',
                'trigger_label'  => 'Buy any share on the market 📈',
                'lesson'         => 'Owning even one share makes you a part-owner of a real company — its profits and losses are now partly yours.',
                'sort_order'     => 42,
            ],
            [
                'title'          => 'Rainy Day Reserve',
                'description'    => 'Push your total savings to Ksh 15,000 — enough to survive a real emergency without borrowing.',
                'icon'           => '☔',
                'xp_reward'      => 220,
                'kes_reward'     => 200,
                'level_required' => 4,
                'trigger_type'   => 'reach_savings',
                'trigger_value'  => '15000',
                'trigger_label'  => 'Reach Ksh 15,000 in total savings',
                'lesson'         => 'An emergency fund is money with one job: absorbing shocks so a flat tyre never turns into a loan.',
                'sort_order'     => 43,
            ],
            [
                'title'          => 'Sealing the Deal',
                'description'    => 'Put money into any Equity Square investment deal. Real investors back real ventures — now it\'s your turn.',
                'icon'           => '🤝',
                'xp_reward'      => 235,
                'kes_reward'     => 215,
                'level_required' => 4,
                'trigger_type'   => 'invest_deal',
                'trigger_value'  => '',
                'trigger_label'  => 'Invest in any Equity Square deal 🤝',
                'lesson'         => 'Equity deals pay you a share of profit, not a fixed wage — bigger upside, but you carry the downside too.',
                'sort_order'     => 44,
            ],
            [
                'title'          => 'Spin for Seed Capital',
                'description'    => 'Spin the Lucky Wheel once. Whatever it pays out, treat it as seed capital, not pocket money.',
                'icon'           => '🎡',
                'xp_reward'      => 200,
                'kes_reward'     => 180,
                'level_required' => 4,
                'trigger_type'   => 'spin_wheel',
                'trigger_value'  => '',
                'trigger_label'  => 'Spin the Lucky Wheel 🎡',
                'lesson'         => 'Windfalls disappear fast without a plan — decide what a bonus is for before it lands in your wallet.',
                'sort_order'     => 45,
            ],
            [
                'title'          => 'Trust Fund',
                'description'    => 'Join a chama, then make your first deposit into it. Kenyans have pooled money together for generations, and it still works.',
                'icon'           => '🫱🏾‍🫲🏾',
                'xp_reward'      => 300,
                'kes_reward'     => 280,
                'level_required' => 4,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'join_chama',      'values' => [],       'label' => 'Join a chama'],
                    ['type' => 'deposit_savings', 'values' => ['5000'], 'label' => 'Deposit at least Ksh 5,000 into any savings pocket'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'A chama turns individual discipline into group accountability — it\'s much harder to skip a contribution when others are watching.',
                'sort_order'     => 46,
            ],

            // ── Level 5 ──────────────────────────────────────────────────────
            [
                'title'          => 'Fixed Income Debut',
                'description'    => 'Buy into the Fixed Income category — an MMF, Treasury Bill, or Treasury Bond. Steady beats flashy.',
                'icon'           => '🏛️',
                'xp_reward'      => 270,
                'kes_reward'     => 290,
                'level_required' => 5,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'fixed_income',
                'trigger_label'  => 'Buy any Fixed Income asset 🏛️',
                'lesson'         => 'Fixed-income products trade excitement for certainty — a smaller, near-guaranteed return instead of a share\'s rollercoaster.',
                'sort_order'     => 51,
            ],
            [
                'title'          => 'Doubling Down',
                'description'    => 'Buy shares again. One trade was luck — a second one is the start of a habit.',
                'icon'           => '📊',
                'xp_reward'      => 290,
                'kes_reward'     => 310,
                'level_required' => 5,
                'trigger_type'   => 'buy_share',
                'trigger_value'  => '',
                'trigger_label'  => 'Buy any share on the market 📊',
                'lesson'         => 'Consistent investing — not one lucky trade — is what actually builds wealth over years.',
                'sort_order'     => 52,
            ],
            [
                'title'          => 'Balance Check',
                'description'    => 'Grow your wallet cash to Ksh 20,000. Liquid cash matters just as much as what you\'ve locked away.',
                'icon'           => '💵',
                'xp_reward'      => 280,
                'kes_reward'     => 300,
                'level_required' => 5,
                'trigger_type'   => 'reach_balance',
                'trigger_value'  => '20000',
                'trigger_label'  => 'Grow your wallet to Ksh 20,000 💵',
                'lesson'         => 'Cash on hand is what keeps a small problem small — everything you own on paper can\'t pay an urgent bill.',
                'sort_order'     => 53,
            ],
            [
                'title'          => 'Life Lessons, Live',
                'description'    => 'Play through any life-decision scenario in Pesa City. Every choice teaches something, even the wrong ones.',
                'icon'           => '🎭',
                'xp_reward'      => 260,
                'kes_reward'     => 280,
                'level_required' => 5,
                'trigger_type'   => 'play_scenario',
                'trigger_value'  => '',
                'trigger_label'  => 'Play any life-decision scenario 🎭',
                'lesson'         => 'Practicing a hard decision in a game costs nothing — practicing it for the first time in real life can cost a lot.',
                'sort_order'     => 54,
            ],
            [
                'title'          => 'Badge in the Bag',
                'description'    => 'Earn any badge in Pesa City — proof your habits are being noticed, not just felt.',
                'icon'           => '🏅',
                'xp_reward'      => 300,
                'kes_reward'     => 320,
                'level_required' => 5,
                'trigger_type'   => 'earn_badge',
                'trigger_value'  => '',
                'trigger_label'  => 'Earn any badge 🏅',
                'lesson'         => 'Recognition is a nice side effect of good habits — it\'s proof the habit is sticking, not the reason to build it.',
                'sort_order'     => 55,
            ],
            [
                'title'          => 'Scenario Sharp',
                'description'    => 'Play through a life-decision scenario, then push your savings to Ksh 25,000. Practice the lesson, then prove it with real money.',
                'icon'           => '🧭',
                'xp_reward'      => 390,
                'kes_reward'     => 420,
                'level_required' => 5,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'play_scenario',  'values' => [],        'label' => 'Play any life-decision scenario'],
                    ['type' => 'reach_savings',  'values' => ['25000'], 'label' => 'Reach Ksh 25,000 in total savings'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'A lesson only counts once it changes what you actually do with your money — not just what you know.',
                'sort_order'     => 56,
            ],

            // ── Level 6 ──────────────────────────────────────────────────────
            [
                'title'          => 'Equity Square, First Visit',
                'description'    => 'Invest in another Equity Square deal — this time with a clearer head about the risk you\'re taking on.',
                'icon'           => '📐',
                'xp_reward'      => 330,
                'kes_reward'     => 390,
                'level_required' => 6,
                'trigger_type'   => 'invest_deal',
                'trigger_value'  => '',
                'trigger_label'  => 'Invest in any Equity Square deal 📐',
                'lesson'         => 'Every deal has a different risk profile — read the terms before the money leaves your account, not after.',
                'sort_order'     => 61,
            ],
            [
                'title'          => 'Property Ladder',
                'description'    => 'Buy your first property-category asset. Land and buildings have anchored Kenyan wealth for generations.',
                'icon'           => '🏘️',
                'xp_reward'      => 350,
                'kes_reward'     => 410,
                'level_required' => 6,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'property',
                'trigger_label'  => 'Buy any property asset 🏘️',
                'lesson'         => 'Property is slow to sell but historically slow to lose value too — it rewards patience more than any other asset class.',
                'sort_order'     => 62,
            ],
            [
                'title'          => 'Net Worth Nudge',
                'description'    => 'Push your net worth past Ksh 80,000. Everything you own minus everything you owe, moving the right direction.',
                'icon'           => '📶',
                'xp_reward'      => 340,
                'kes_reward'     => 400,
                'level_required' => 6,
                'trigger_type'   => 'reach_net_worth',
                'trigger_value'  => '80000',
                'trigger_label'  => 'Push your net worth past Ksh 80,000 📶',
                'lesson'         => 'Net worth is the real scoreboard — a big salary spent as fast as it lands still nets out to zero.',
                'sort_order'     => 63,
            ],
            [
                'title'          => 'Leisure Budget, Real Limits',
                'description'    => 'Spend something in Fun World — on purpose, from a budget, not by accident.',
                'icon'           => '🎢',
                'xp_reward'      => 320,
                'kes_reward'     => 380,
                'level_required' => 6,
                'trigger_type'   => 'fun_world_spend',
                'trigger_value'  => '',
                'trigger_label'  => 'Spend on any Fun World activity 🎢',
                'lesson'         => 'A budget with zero fun money usually fails — the goal is a planned amount for enjoyment, not none at all.',
                'sort_order'     => 64,
            ],
            [
                'title'          => 'Level Milestone',
                'description'    => 'Reach Level 7. Keep stacking XP — the habits are compounding just like the money.',
                'icon'           => '⭐',
                'xp_reward'      => 360,
                'kes_reward'     => 420,
                'level_required' => 6,
                'trigger_type'   => 'reach_level',
                'trigger_value'  => '7',
                'trigger_label'  => 'Reach Level 7 ⭐',
                'lesson'         => 'Progress compounds quietly — you rarely feel level 7 coming until you\'re already there.',
                'sort_order'     => 65,
            ],
            [
                'title'          => 'Gadget Hustle',
                'description'    => 'Buy a gadget-category asset that can earn you money, then grow your wallet to Ksh 30,000 using it.',
                'icon'           => '📷',
                'xp_reward'      => 480,
                'kes_reward'     => 560,
                'level_required' => 6,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'buy_item_category', 'values' => ['gadget'], 'label' => 'Buy any gadget asset'],
                    ['type' => 'reach_balance',      'values' => ['30000'], 'label' => 'Grow your wallet to Ksh 30,000'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'A gadget is only an investment if the income it earns outpaces what it cost you — otherwise it\'s just a nice-to-have.',
                'sort_order'     => 66,
            ],

            // ── Level 7 ──────────────────────────────────────────────────────
            [
                'title'          => 'Bond Buyer',
                'description'    => 'Buy a 5-Year Treasury Bond. Your money is locked for years, but the government pays you every six months for the privilege.',
                'icon'           => '📜',
                'xp_reward'      => 390,
                'kes_reward'     => 490,
                'level_required' => 7,
                'trigger_type'   => 'buy_item_slug',
                'trigger_value'  => 'treasury-bonds-5yr',
                'trigger_label'  => 'Buy the Treasury Bonds (5-Year) 📜',
                'lesson'         => 'Locking money away isn\'t wasted money — it\'s money working somewhere you can\'t accidentally spend it.',
                'sort_order'     => 71,
            ],
            [
                'title'          => 'Second Share Play',
                'description'    => 'Buy shares again. A real investor doesn\'t stop at one purchase.',
                'icon'           => '📈',
                'xp_reward'      => 410,
                'kes_reward'     => 510,
                'level_required' => 7,
                'trigger_type'   => 'buy_share',
                'trigger_value'  => '',
                'trigger_label'  => 'Buy any share on the market 📈',
                'lesson'         => 'Spreading purchases over time smooths out the ups and downs of buying at just one price.',
                'sort_order'     => 72,
            ],
            [
                'title'          => 'Savings Sprint',
                'description'    => 'Push your total savings to Ksh 40,000. The number keeps climbing because the habit never stopped.',
                'icon'           => '🏃🏾',
                'xp_reward'      => 400,
                'kes_reward'     => 500,
                'level_required' => 7,
                'trigger_type'   => 'reach_savings',
                'trigger_value'  => '40000',
                'trigger_label'  => 'Reach Ksh 40,000 in total savings',
                'lesson'         => 'Savings targets should keep moving — the discipline that got you to 15,000 is what gets you to 40,000 too.',
                'sort_order'     => 73,
            ],
            [
                'title'          => 'Badge Number Two',
                'description'    => 'Earn another badge. The first one was luck, this one is a pattern.',
                'icon'           => '🎖️',
                'xp_reward'      => 420,
                'kes_reward'     => 520,
                'level_required' => 7,
                'trigger_type'   => 'earn_badge',
                'trigger_value'  => '',
                'trigger_label'  => 'Earn any badge 🎖️',
                'lesson'         => 'One good result can be an accident — two is the beginning of a track record.',
                'sort_order'     => 74,
            ],
            [
                'title'          => 'Career Pivot',
                'description'    => 'Complete the Web Design Basics course. Skills are the one asset nobody can repossess.',
                'icon'           => '💻',
                'xp_reward'      => 380,
                'kes_reward'     => 480,
                'level_required' => 7,
                'trigger_type'   => 'take_course',
                'trigger_value'  => 'web-design-basics',
                'trigger_label'  => 'Complete Web Design Basics 💻',
                'lesson'         => 'A skill you can sell is inflation-proof — its value rises with demand instead of eroding with prices.',
                'sort_order'     => 75,
            ],
            [
                'title'          => 'The Big Ascend',
                'description'    => 'Reach Level 8, and push your net worth past Ksh 120,000 along the way. Both numbers should be climbing together.',
                'icon'           => '🚀',
                'xp_reward'      => 560,
                'kes_reward'     => 700,
                'level_required' => 7,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'reach_level',     'values' => ['8'],      'label' => 'Reach Level 8'],
                    ['type' => 'reach_net_worth', 'values' => ['120000'], 'label' => 'Push your net worth past Ksh 120,000'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'XP and net worth should rise together — a high level with a flat net worth means the habits aren\'t translating into money yet.',
                'sort_order'     => 76,
            ],
        ];

        foreach ($quests as $data) {
            Quest::updateOrCreate(
                ['title' => $data['title']],
                $data + ['is_active' => true, 'age_group' => '18-25']
            );
        }
    }
}
