<?php

namespace Database\Seeders;

use App\Models\Quest;
use Illuminate\Database\Seeder;

class QuestExpansion13to17Band1Seeder extends Seeder
{
    public function run(): void
    {
        $quests = [

            // ═══════════════════════════════════════════════════════════════
            // LEVEL 1
            // ═══════════════════════════════════════════════════════════════
            [
                'title'          => 'Vault at Thirteen',
                'description'    => 'Open your own savings account at the Bank district — no parent needed in Pesa City.',
                'icon'           => '🏦',
                'xp_reward'      => 110,
                'kes_reward'     => 95,
                'level_required' => 1,
                'trigger_type'   => 'open_savings',
                'trigger_value'  => '',
                'trigger_label'  => 'Open a savings account',
                'lesson'         => 'A teen who opens a savings account before 18 has already out-planned most Kenyan adults — the account matters less than the habit it starts.',
                'sort_order'     => 11,
            ],
            [
                'title'          => 'Gadget Scout',
                'description'    => 'Buy any gadget from the Marketplace — even a modest one holds resale value if you choose well.',
                'icon'           => '📱',
                'xp_reward'      => 130,
                'kes_reward'     => 110,
                'level_required' => 1,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'gadget',
                'trigger_label'  => 'Buy any gadget from the Marketplace',
                'lesson'         => 'Gadgets lose value fast, but a well-kept one still resells for something — a car doesn\'t, once it\'s truly worn out.',
                'sort_order'     => 12,
            ],
            [
                'title'          => 'Lucky Spin, Smart Landing',
                'description'    => 'Spin the Lucky Wheel once — whatever you land, decide where it goes before you touch it.',
                'icon'           => '🎡',
                'xp_reward'      => 115,
                'kes_reward'     => 90,
                'level_required' => 1,
                'trigger_type'   => 'spin_wheel',
                'trigger_value'  => '',
                'trigger_label'  => 'Spin the Lucky Wheel',
                'lesson'         => 'Windfalls disappear fastest when they arrive with no plan attached — decide the destination before the money lands in your hand.',
                'sort_order'     => 13,
            ],
            [
                'title'          => 'Story of a Shilling',
                'description'    => 'Play through a life-decision scenario in Pesa City and see where your choice leads.',
                'icon'           => '📖',
                'xp_reward'      => 120,
                'kes_reward'     => 100,
                'level_required' => 1,
                'trigger_type'   => 'play_scenario',
                'trigger_value'  => '',
                'trigger_label'  => 'Resolve any life-decision scenario',
                'lesson'         => 'Every money decision is a small story with consequences down the line — practising them here costs nothing but time.',
                'sort_order'     => 14,
            ],
            [
                'title'          => 'First Shilling In',
                'description'    => 'Deposit at least Ksh 300 into any savings pocket.',
                'icon'           => '💵',
                'xp_reward'      => 125,
                'kes_reward'     => 105,
                'level_required' => 1,
                'trigger_type'   => 'deposit_savings',
                'trigger_value'  => '300',
                'trigger_label'  => 'Deposit at least Ksh 300 into savings',
                'lesson'         => 'The first deposit is always the hardest one to make — every deposit after it gets easier because the habit is already built.',
                'sort_order'     => 15,
            ],
            [
                'title'          => 'Fun Money, Real Plan',
                'description'    => 'Spend something in Fun World, then deposit Ksh 200 into savings — prove fun and discipline can share a wallet.',
                'icon'           => '🎮',
                'xp_reward'      => 170,
                'kes_reward'     => 140,
                'level_required' => 1,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'fun_world_spend', 'values' => [], 'label' => 'Spend on any Fun World activity'],
                    ['type' => 'deposit_savings', 'values' => ['200'], 'label' => 'Deposit at least Ksh 200 into savings'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'Fun money is still money — budgeting for it on purpose beats discovering afterward that it ate your whole week\'s allowance.',
                'sort_order'     => 16,
            ],
            [
                'title'          => 'Foundations Set',
                'description'    => 'Grow your savings to Ksh 500 and play through a life-decision scenario — proof you can save AND think a decision through.',
                'icon'           => '🧱',
                'xp_reward'      => 175,
                'kes_reward'     => 145,
                'level_required' => 1,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'deposit_savings', 'values' => ['500'], 'label' => 'Deposit at least Ksh 500 into savings'],
                    ['type' => 'play_scenario',   'values' => [],      'label' => 'Resolve any life-decision scenario'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'Saving builds the cushion; good decisions protect it. Neither one alone is enough — Pesa City rewards both together.',
                'sort_order'     => 17,
            ],

            // ═══════════════════════════════════════════════════════════════
            // LEVEL 2
            // ═══════════════════════════════════════════════════════════════
            [
                'title'          => 'Circle Starter',
                'description'    => 'Join a chama — Kenyans have pooled money together for generations, and now it\'s your turn.',
                'icon'           => '🤝',
                'xp_reward'      => 150,
                'kes_reward'     => 130,
                'level_required' => 2,
                'trigger_type'   => 'join_chama',
                'trigger_value'  => '',
                'trigger_label'  => 'Join a chama',
                'lesson'         => 'A chama turns individual willpower into group accountability — it\'s much harder to skip a contribution when ten other people are watching.',
                'sort_order'     => 21,
            ],
            [
                'title'          => 'Skill Sharpener',
                'description'    => 'Complete the Digital Skills Intro course at Skill Campus.',
                'icon'           => '💻',
                'xp_reward'      => 165,
                'kes_reward'     => 145,
                'level_required' => 2,
                'trigger_type'   => 'take_course',
                'trigger_value'  => 'digital-skills-intro',
                'trigger_label'  => 'Complete Digital Skills Intro',
                'lesson'         => 'Digital skills are now table stakes for almost every paying job in Kenya, not just tech ones — this is the cheapest investment you\'ll ever make in yourself.',
                'sort_order'     => 22,
            ],
            [
                'title'          => 'Business Eye',
                'description'    => 'Buy any business-category asset from the Marketplace — you\'re not spending, you\'re acquiring.',
                'icon'           => '🏪',
                'xp_reward'      => 170,
                'kes_reward'     => 150,
                'level_required' => 2,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'business',
                'trigger_label'  => 'Buy any business-category asset',
                'lesson'         => 'A business asset can pay you back over and over — that\'s the whole difference between spending and investing.',
                'sort_order'     => 23,
            ],
            [
                'title'          => 'First Bet on a Company',
                'description'    => 'Buy shares in any listed company on the Market.',
                'icon'           => '📈',
                'xp_reward'      => 175,
                'kes_reward'     => 155,
                'level_required' => 2,
                'trigger_type'   => 'buy_share',
                'trigger_value'  => '',
                'trigger_label'  => 'Buy shares in any company',
                'lesson'         => 'Owning even one share makes you a part-owner of a real business — small stakes are still real stakes.',
                'sort_order'     => 24,
            ],
            [
                'title'          => 'Second Purchase',
                'description'    => 'Add a Money Market Fund unit to your portfolio — the safest place to grow spare cash.',
                'icon'           => '💰',
                'xp_reward'      => 160,
                'kes_reward'     => 140,
                'level_required' => 2,
                'trigger_type'   => 'buy_item_slug',
                'trigger_value'  => 'money-market-fund',
                'trigger_label'  => 'Buy into the Money Market Fund',
                'lesson'         => 'An MMF pays more than a bank savings account while staying accessible in days, not years — a smart parking spot for cash you\'re not ready to risk.',
                'sort_order'     => 25,
            ],
            [
                'title'          => 'Double Down',
                'description'    => 'Buy shares in a company AND grow your total savings to Ksh 2,000 — investing and saving working together.',
                'icon'           => '🚀',
                'xp_reward'      => 225,
                'kes_reward'     => 195,
                'level_required' => 2,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'buy_share',      'values' => [],       'label' => 'Buy shares in any company'],
                    ['type' => 'reach_savings',  'values' => ['2000'], 'label' => 'Reach Ksh 2,000 in total savings'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'Investing doesn\'t replace saving — the two work best side by side, one building your cushion, the other building your upside.',
                'sort_order'     => 26,
            ],
            [
                'title'          => 'Balance & Beyond',
                'description'    => 'Grow your wallet to Ksh 3,000, then push on to Level 3 — money in hand and momentum both matter.',
                'icon'           => '⭐',
                'xp_reward'      => 230,
                'kes_reward'     => 200,
                'level_required' => 2,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'reach_balance', 'values' => ['3000'], 'label' => 'Grow your wallet to Ksh 3,000'],
                    ['type' => 'reach_level',   'values' => ['3'],    'label' => 'Reach Level 3'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'Cash in hand and progress made are two different wins — chase both, not just one.',
                'sort_order'     => 27,
            ],

            // ═══════════════════════════════════════════════════════════════
            // LEVEL 3
            // ═══════════════════════════════════════════════════════════════
            [
                'title'          => 'Curious About Property',
                'description'    => 'Buy any property-category asset from the Marketplace.',
                'icon'           => '🏠',
                'xp_reward'      => 185,
                'kes_reward'     => 165,
                'level_required' => 3,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'property',
                'trigger_label'  => 'Buy any property-category asset',
                'lesson'         => 'Property is the one asset class that doesn\'t vanish or wear out — it\'s also usually the slowest one to pay you back.',
                'sort_order'     => 31,
            ],
            [
                'title'          => 'Deal Room Debut',
                'description'    => 'Invest in your first Equity Square deal.',
                'icon'           => '💼',
                'xp_reward'      => 195,
                'kes_reward'     => 175,
                'level_required' => 3,
                'trigger_type'   => 'invest_deal',
                'trigger_value'  => '',
                'trigger_label'  => 'Invest in any Equity Square deal',
                'lesson'         => 'Equity deals put your money to work in someone else\'s business — you share the upside, but also the risk if it doesn\'t pan out.',
                'sort_order'     => 32,
            ],
            [
                'title'          => 'Badge Worth Earning',
                'description'    => 'Earn any badge in Pesa City.',
                'icon'           => '🏅',
                'xp_reward'      => 190,
                'kes_reward'     => 170,
                'level_required' => 3,
                'trigger_type'   => 'earn_badge',
                'trigger_value'  => '',
                'trigger_label'  => 'Earn any badge',
                'lesson'         => 'Recognition is a side effect of good habits, not the goal — but it\'s solid proof the habit is actually sticking.',
                'sort_order'     => 33,
            ],
            [
                'title'          => 'Weekend Gig',
                'description'    => 'Get hired for any job at the Opportunity Hub.',
                'icon'           => '💼',
                'xp_reward'      => 200,
                'kes_reward'     => 180,
                'level_required' => 3,
                'trigger_type'   => 'get_job',
                'trigger_value'  => '',
                'trigger_label'  => 'Get hired for any job',
                'lesson'         => 'A steady payday, even a small one, is the engine that makes every other financial move possible.',
                'sort_order'     => 34,
            ],
            [
                'title'          => 'Fixed Income First Look',
                'description'    => 'Buy into any fixed-income asset — Money Market Fund, Treasury Bill, or Treasury Bond.',
                'icon'           => '🏛️',
                'xp_reward'      => 195,
                'kes_reward'     => 175,
                'level_required' => 3,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'fixed_income',
                'trigger_label'  => 'Buy any fixed-income asset',
                'lesson'         => 'Fixed-income assets trade a lower return for near-certainty — the government or a fund manager pays you on a schedule, not a guess.',
                'sort_order'     => 35,
            ],
            [
                'title'          => 'Growth & Grounded',
                'description'    => 'Push your net worth past Ksh 8,000 and resolve a life-decision scenario — growth and judgement, together.',
                'icon'           => '🌱',
                'xp_reward'      => 265,
                'kes_reward'     => 235,
                'level_required' => 3,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'reach_net_worth', 'values' => ['8000'], 'label' => 'Push your net worth past Ksh 8,000'],
                    ['type' => 'play_scenario',   'values' => [],       'label' => 'Resolve any life-decision scenario'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'Net worth measures the outcome; every scenario you play through sharpens the judgement that produces it.',
                'sort_order'     => 36,
            ],
            [
                'title'          => 'Portfolio Beginnings',
                'description'    => 'Buy shares in a company AND invest in an Equity Square deal — the start of a real, two-legged portfolio.',
                'icon'           => '💎',
                'xp_reward'      => 270,
                'kes_reward'     => 240,
                'level_required' => 3,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'buy_share',    'values' => [], 'label' => 'Buy shares in any company'],
                    ['type' => 'invest_deal',  'values' => [], 'label' => 'Invest in any Equity Square deal'],
                ],
                'trigger_mode'   => 'all',
                'lesson'         => 'No single investment should carry your whole future — spreading across shares and deals is how real portfolios start.',
                'sort_order'     => 37,
            ],

        ];

        foreach ($quests as $data) {
            Quest::updateOrCreate(
                ['title' => $data['title']],
                array_merge($data, ['is_active' => true, 'age_group' => '13-17'])
            );
        }
    }
}
