<?php

namespace Database\Seeders;

use App\Models\Quest;
use Illuminate\Database\Seeder;

class QuestExpansion26PlusBand3Seeder extends Seeder
{
    public function run(): void
    {
        $quests = [

            // ══════════════════════════════════════════════════════════
            // LEVEL 8
            // ══════════════════════════════════════════════════════════
            [
                'title'          => 'Cushion of Confidence',
                'icon'           => '🛡️',
                'description'    => 'Push your total savings to Ksh 150,000 — a real buffer, not a rounding error.',
                'lesson'         => 'At this stage a buffer isn\'t about emergencies anymore — it\'s what lets you take a calculated risk elsewhere without panic.',
                'xp_reward'      => 440,
                'kes_reward'     => 600,
                'level_required' => 8,
                'trigger_type'   => 'reach_savings',
                'trigger_value'  => '150000',
                'trigger_label'  => 'Reach Ksh 150,000 in total savings',
                'sort_order'     => 81,
            ],
            [
                'title'          => 'Brick in the Portfolio',
                'icon'           => '🧱',
                'description'    => 'Buy any business-category asset from the Marketplace — a stake in something that produces, not just sits.',
                'lesson'         => 'Business assets (a stall, a machine, a franchise slot) earn because they do work. That\'s different from an asset that just hopes to appreciate.',
                'xp_reward'      => 470,
                'kes_reward'     => 650,
                'level_required' => 8,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'business',
                'trigger_label'  => 'Buy any business asset',
                'sort_order'     => 82,
            ],
            [
                'title'          => 'First Rungs on the Exchange',
                'icon'           => '📈',
                'description'    => 'Buy a share on the exchange. Ownership, not a fixed rate — you now move with the company.',
                'lesson'         => 'Shares carry more risk than a savings account or a bond, but also more upside — you\'re paid for taking on that uncertainty.',
                'xp_reward'      => 500,
                'kes_reward'     => 700,
                'level_required' => 8,
                'trigger_type'   => 'buy_share',
                'trigger_value'  => '',
                'trigger_label'  => 'Buy any share',
                'sort_order'     => 83,
            ],
            [
                'title'          => 'Backing a Real Deal',
                'icon'           => '🧩',
                'description'    => 'Put money into an Equity Square investment deal — someone else\'s venture, your capital, a shared outcome.',
                'lesson'         => 'Investing in a deal means your return depends on someone else executing well. Read the terms like you\'d read a job offer.',
                'xp_reward'      => 520,
                'kes_reward'     => 720,
                'level_required' => 8,
                'trigger_type'   => 'invest_deal',
                'trigger_value'  => '',
                'trigger_label'  => 'Invest in any deal',
                'sort_order'     => 84,
            ],
            [
                'title'          => 'A Detour Worth Taking',
                'icon'           => '🎭',
                'description'    => 'Play through a life-decision scenario. Every choice you make there is a rehearsal for the real one.',
                'lesson'         => 'Rehearsing a financial decision in a low-stakes scenario builds the instinct you\'ll need when the real version shows up uninvited.',
                'xp_reward'      => 450,
                'kes_reward'     => 620,
                'level_required' => 8,
                'trigger_type'   => 'play_scenario',
                'trigger_value'  => '',
                'trigger_label'  => 'Play any life-decision scenario',
                'sort_order'     => 85,
            ],
            [
                'title'          => 'Fun Money, Fixed Ceiling',
                'icon'           => '🎢',
                'description'    => 'Spend something in Fun World, then prove the fun didn\'t dent your wallet — grow your balance to Ksh 60,000 after.',
                'lesson'         => 'A fun budget is healthy. A fun budget with no ceiling is how savings quietly disappear one small purchase at a time.',
                'xp_reward'      => 660,
                'kes_reward'     => 910,
                'level_required' => 8,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'fun_world_spend', 'values' => [], 'label' => 'Spend on any Fun World activity'],
                    ['type' => 'reach_balance',   'values' => ['60000'], 'label' => 'Grow your wallet to Ksh 60,000'],
                ],
                'trigger_mode'   => 'all',
                'sort_order'     => 86,
            ],

            // ══════════════════════════════════════════════════════════
            // LEVEL 9
            // ══════════════════════════════════════════════════════════
            [
                'title'          => 'Half a Million and Climbing',
                'icon'           => '💎',
                'description'    => 'Push your net worth past Ksh 600,000. The Settler chapter is getting closer than it looks.',
                'lesson'         => 'Net worth compounds unevenly — most of it comes late, once your assets are doing more of the earning than your salary is.',
                'xp_reward'      => 520,
                'kes_reward'     => 760,
                'level_required' => 9,
                'trigger_type'   => 'reach_net_worth',
                'trigger_value'  => '600000',
                'trigger_label'  => 'Push your net worth past Ksh 600,000',
                'sort_order'     => 91,
            ],
            [
                'title'          => 'Parking It Safely',
                'icon'           => '🏦',
                'description'    => 'Buy into a Money Market Fund — cash that stays liquid, still earns, and never surprises you.',
                'lesson'         => 'An MMF is where money waits, not where it grows fastest. Knowing the difference between "parked" and "invested" saves you from bad comparisons later.',
                'xp_reward'      => 550,
                'kes_reward'     => 800,
                'level_required' => 9,
                'trigger_type'   => 'buy_item_slug',
                'trigger_value'  => 'money-market-fund',
                'trigger_label'  => 'Buy into a Money Market Fund',
                'sort_order'     => 92,
            ],
            [
                'title'          => 'Eleven Voices, One Pot',
                'icon'           => '👥',
                'description'    => 'Join a chama. Eleven other people now know exactly when your contribution is due.',
                'lesson'         => 'Peer accountability is a financial tool, not just a social one — a chama makes discipline social rather than purely internal.',
                'xp_reward'      => 580,
                'kes_reward'     => 840,
                'level_required' => 9,
                'trigger_type'   => 'join_chama',
                'trigger_value'  => '',
                'trigger_label'  => 'Join a chama',
                'sort_order'     => 93,
            ],
            [
                'title'          => 'One Spin for the Road',
                'icon'           => '🎡',
                'description'    => 'Spin the Lucky Wheel once. A small thrill, kept small on purpose.',
                'lesson'         => 'Occasional, bounded chance-taking isn\'t the enemy of a financial plan — unbounded chance-taking is. Know which one you\'re doing.',
                'xp_reward'      => 600,
                'kes_reward'     => 870,
                'level_required' => 9,
                'trigger_type'   => 'spin_wheel',
                'trigger_value'  => '',
                'trigger_label'  => 'Spin the Lucky Wheel',
                'sort_order'     => 94,
            ],
            [
                'title'          => 'A Name Worth Earning',
                'icon'           => '🏅',
                'description'    => 'Earn any badge in Pesa City. Recognition that came from doing, not asking.',
                'lesson'         => 'A badge is just a marker — the habit behind it is the actual asset. Don\'t chase the marker and skip the habit.',
                'xp_reward'      => 560,
                'kes_reward'     => 810,
                'level_required' => 9,
                'trigger_type'   => 'earn_badge',
                'trigger_value'  => '',
                'trigger_label'  => 'Earn any badge',
                'sort_order'     => 95,
            ],
            [
                'title'          => 'From Ledger to Letterhead',
                'icon'           => '📊',
                'description'    => 'Complete Bookkeeping Basics, then get hired somewhere that actually needs the skill.',
                'lesson'         => 'A skill only pays once it\'s attached to a role. The course is the investment; the job is the return showing up.',
                'xp_reward'      => 770,
                'kes_reward'     => 1120,
                'level_required' => 9,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'take_course', 'values' => ['bookkeeping-basics'], 'label' => 'Complete Bookkeeping Basics'],
                    ['type' => 'get_job',     'values' => [],                    'label' => 'Get hired for any job'],
                ],
                'trigger_mode'   => 'all',
                'sort_order'     => 96,
            ],

            // ══════════════════════════════════════════════════════════
            // LEVEL 10
            // ══════════════════════════════════════════════════════════
            [
                'title'          => 'One Level From Legend',
                'icon'           => '⭐',
                'description'    => 'Reach Level 11 — the top of the ladder, PesaQuest Legend status.',
                'lesson'         => 'The last stretch of any ladder is the slowest — the XP curve gets steeper on purpose, so the milestone still means something.',
                'xp_reward'      => 620,
                'kes_reward'     => 950,
                'level_required' => 10,
                'trigger_type'   => 'reach_level',
                'trigger_value'  => '11',
                'trigger_label'  => 'Reach Level 11',
                'sort_order'     => 101,
            ],
            [
                'title'          => 'Anchored in Government Paper',
                'icon'           => '🏛️',
                'description'    => 'Buy any fixed-income asset — a Treasury Bill or Bond. Slower, steadier, backed by the state.',
                'lesson'         => 'A diversified portfolio holds both growth assets and anchors. Government paper is the anchor — it won\'t make you rich, but it won\'t abandon you either.',
                'xp_reward'      => 650,
                'kes_reward'     => 1000,
                'level_required' => 10,
                'trigger_type'   => 'buy_item_category',
                'trigger_value'  => 'fixed_income',
                'trigger_label'  => 'Buy any fixed-income asset',
                'sort_order'     => 102,
            ],
            [
                'title'          => 'Quarter-Million Buffer',
                'icon'           => '🧮',
                'description'    => 'Grow your wallet balance to Ksh 250,000 in ready cash.',
                'lesson'         => 'Ready cash and net worth are not the same thing — a portfolio you can\'t access when you need it isn\'t a buffer, it\'s a trap.',
                'xp_reward'      => 680,
                'kes_reward'     => 1050,
                'level_required' => 10,
                'trigger_type'   => 'reach_balance',
                'trigger_value'  => '250000',
                'trigger_label'  => 'Grow your wallet to Ksh 250,000',
                'sort_order'     => 103,
            ],
            [
                'title'          => 'Portfolio, Then Principal',
                'icon'           => '📜',
                'description'    => 'Buy a share, then separately grow your total savings to Ksh 400,000. Growth and safety, both funded.',
                'lesson'         => 'A mature investor runs two accounts at once in their head: the money that\'s working hard, and the money that\'s just staying safe.',
                'xp_reward'      => 910,
                'kes_reward'     => 1400,
                'level_required' => 10,
                'trigger_type'   => null,
                'trigger_value'  => null,
                'trigger_label'  => null,
                'triggers'       => [
                    ['type' => 'buy_share',      'values' => [],          'label' => 'Buy any share'],
                    ['type' => 'reach_savings',  'values' => ['400000'],  'label' => 'Reach Ksh 400,000 in total savings'],
                ],
                'trigger_mode'   => 'all',
                'sort_order'     => 104,
            ],
            [
                'title'          => 'The Road Not Taken, Twice',
                'icon'           => '🛤️',
                'description'    => 'Play through another life-decision scenario. Different fork, different lesson.',
                'lesson'         => 'The same financial dilemma rarely repeats exactly — but the underlying trade-off (now vs. later, safe vs. sure) always does.',
                'xp_reward'      => 700,
                'kes_reward'     => 1080,
                'level_required' => 10,
                'trigger_type'   => 'play_scenario',
                'trigger_value'  => '',
                'trigger_label'  => 'Play any life-decision scenario',
                'sort_order'     => 105,
            ],
            [
                'title'          => 'Skin in Someone Else\'s Game',
                'icon'           => '🎯',
                'description'    => 'Invest in another Equity Square deal. A second bet, a second set of terms to actually read.',
                'lesson'         => 'One good deal can be luck. Evaluating a second one with the same discipline is the start of an actual investing habit.',
                'xp_reward'      => 660,
                'kes_reward'     => 1010,
                'level_required' => 10,
                'trigger_type'   => 'invest_deal',
                'trigger_value'  => '',
                'trigger_label'  => 'Invest in any deal',
                'sort_order'     => 106,
            ],
        ];

        foreach ($quests as $data) {
            Quest::updateOrCreate(
                ['title' => $data['title']],
                $data + ['is_active' => true, 'age_group' => '26+']
            );
        }
    }
}
