<?php

namespace Database\Seeders;

use App\Models\Quest;
use Illuminate\Database\Seeder;

class QuestExpansion26PlusBand1Seeder extends Seeder
{
    public function run(): void
    {
        $quests = [

            // ═══════════════════════════════════════════════════════
            // LEVEL 1
            // ═══════════════════════════════════════════════════════
            [
                'title'         => 'Grown-Up Money Move',
                'description'   => 'Formalize your money life — open a proper bank savings account, not just an M-Pesa wallet.',
                'icon'          => '🏦',
                'xp_reward'     => 110,
                'kes_reward'    => 90,
                'level_required'=> 1,
                'trigger_type'  => 'open_savings',
                'trigger_value' => '',
                'trigger_label' => 'Open a savings account',
                'lesson'        => 'An M-Pesa wallet is for moving money; a bank account is for growing it. Adults who separate the two save more without noticing.',
                'sort_order'    => 1,
            ],
            [
                'title'         => 'First Stock in the Game',
                'description'   => 'Buy your first share on the Pesa City exchange. Ownership, not just savings, is how real wealth compounds.',
                'icon'          => '📈',
                'xp_reward'     => 130,
                'kes_reward'    => 110,
                'level_required'=> 1,
                'trigger_type'  => 'buy_share',
                'trigger_value' => '',
                'trigger_label' => 'Buy any share',
                'lesson'        => 'Owning even one share makes you a part-owner of a real business — its profits, and its risks, are now partly yours.',
                'sort_order'    => 2,
            ],
            [
                'title'         => 'Own a Piece of Business',
                'description'   => 'Buy any business-category asset from the Marketplace — a stake in something that can generate income for you.',
                'icon'          => '🏪',
                'xp_reward'     => 125,
                'kes_reward'    => 105,
                'level_required'=> 1,
                'trigger_type'  => 'buy_item_category',
                'trigger_value' => 'business',
                'trigger_label' => 'Buy any business-category asset',
                'lesson'        => 'A business asset works while you sleep. That is the entire difference between a job and an investment.',
                'sort_order'    => 3,
            ],
            [
                'title'         => 'Save First, Then Invest',
                'description'   => 'Grow your savings to Ksh 3,000, then put some of it to work by buying a share.',
                'icon'          => '🌱',
                'xp_reward'     => 170,
                'kes_reward'    => 140,
                'level_required'=> 1,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'reach_savings', 'values' => ['3000'], 'label' => 'Grow your savings to Ksh 3,000'],
                    ['type' => 'buy_share',     'values' => [],       'label' => 'Buy any share'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'Savings is your safety net; investing is your growth engine. Adults who skip straight to investing without savings first are one bad month from disaster.',
                'sort_order'    => 4,
            ],
            [
                'title'         => 'Real Life, Real Choices',
                'description'   => 'Play through any Life Decision scenario in Pesa City — every choice you make there teaches something real.',
                'icon'          => '🎭',
                'xp_reward'     => 115,
                'kes_reward'    => 95,
                'level_required'=> 1,
                'trigger_type'  => 'play_scenario',
                'trigger_value' => '',
                'trigger_label' => 'Play any Life Decision scenario',
                'lesson'        => 'Every financial decision is really a trade-off. Practicing them here costs nothing; getting them wrong in real life does.',
                'sort_order'    => 5,
            ],
            [
                'title'         => 'Adult Luck, Adult Plan',
                'description'   => 'Spin the Lucky Wheel once — then decide with your head, not your excitement, what to do with whatever you land.',
                'icon'          => '🎡',
                'xp_reward'     => 105,
                'kes_reward'    => 85,
                'level_required'=> 1,
                'trigger_type'  => 'spin_wheel',
                'trigger_value' => '',
                'trigger_label' => 'Spin the Lucky Wheel',
                'lesson'        => 'Windfalls test discipline more than paychecks do. What you do with easy money reveals your real money habits.',
                'sort_order'    => 6,
            ],
            [
                'title'         => 'Pooling Power',
                'description'   => 'Join a chama and make your first contribution of at least Ksh 1,500.',
                'icon'          => '🤝',
                'xp_reward'     => 172,
                'kes_reward'    => 145,
                'level_required'=> 1,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'join_chama',      'values' => [],        'label' => 'Join a chama'],
                    ['type' => 'deposit_savings', 'values' => ['1500'],  'label' => 'Contribute at least Ksh 1,500'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'A chama turns individual willpower into group accountability — Kenyans have used this trick for generations because it works.',
                'sort_order'    => 7,
            ],

            // ═══════════════════════════════════════════════════════
            // LEVEL 2
            // ═══════════════════════════════════════════════════════
            [
                'title'         => 'The Safe Starter',
                'description'   => "Put money into a Money Market Fund — the safest place for cash you're not ready to risk yet.",
                'icon'          => '💰',
                'xp_reward'     => 150,
                'kes_reward'    => 130,
                'level_required'=> 2,
                'trigger_type'  => 'buy_item_slug',
                'trigger_value' => 'money-market-fund',
                'trigger_label' => 'Buy into the Money Market Fund',
                'lesson'        => 'An MMF beats a bank savings account by several times over while staying just as accessible. It is the first real investment most Kenyans should make.',
                'sort_order'    => 8,
            ],
            [
                'title'         => 'Cutting a Real Deal',
                'description'   => 'Back an investment deal at Equity Square. Real capital, real risk, real returns.',
                'icon'          => '🤝',
                'xp_reward'     => 165,
                'kes_reward'    => 145,
                'level_required'=> 2,
                'trigger_type'  => 'invest_deal',
                'trigger_value' => '',
                'trigger_label' => 'Back any investment deal',
                'lesson'        => 'Direct deals often pay more than passive assets — because you are also taking on more direct risk. Read the terms.',
                'sort_order'    => 9,
            ],
            [
                'title'         => 'Six Thousand Cushion',
                'description'   => 'Keep at least Ksh 6,000 sitting in your wallet at all times — your buffer for the unexpected.',
                'icon'          => '💵',
                'xp_reward'     => 155,
                'kes_reward'    => 135,
                'level_required'=> 2,
                'trigger_type'  => 'reach_balance',
                'trigger_value' => '6000',
                'trigger_label' => 'Grow your wallet to Ksh 6,000',
                'lesson'        => 'A cash buffer is not lazy money — it is what stops a flat tyre from becoming a loan.',
                'sort_order'    => 10,
            ],
            [
                'title'         => 'Work Hard, Play Smart',
                'description'   => 'Spend on something in Fun World — guilt-free, because you budgeted for it.',
                'icon'          => '🎉',
                'xp_reward'     => 148,
                'kes_reward'    => 128,
                'level_required'=> 2,
                'trigger_type'  => 'fun_world_spend',
                'trigger_value' => '',
                'trigger_label' => 'Spend on anything in Fun World',
                'lesson'        => 'A budget with zero room for fun rarely survives contact with real life. Planned fun is not a leak — unplanned fun is.',
                'sort_order'    => 11,
            ],
            [
                'title'         => 'Recognition Round One',
                'description'   => 'Earn any badge in Pesa City — proof your habits are being noticed.',
                'icon'          => '🏅',
                'xp_reward'     => 170,
                'kes_reward'    => 150,
                'level_required'=> 2,
                'trigger_type'  => 'earn_badge',
                'trigger_value' => '',
                'trigger_label' => 'Earn any badge',
                'lesson'        => 'Badges are a side effect of good habits, never the goal. But noticing your own progress keeps you going.',
                'sort_order'    => 12,
            ],
            [
                'title'         => 'One Rung Higher',
                'description'   => 'Push through to Level 3 — the next chapter of your financial journey starts there.',
                'icon'          => '⭐',
                'xp_reward'     => 175,
                'kes_reward'    => 155,
                'level_required'=> 2,
                'trigger_type'  => 'reach_level',
                'trigger_value' => '3',
                'trigger_label' => 'Reach Level 3',
                'lesson'        => 'Progress compounds like interest — each level you clear makes the next easier, not harder.',
                'sort_order'    => 13,
            ],
            [
                'title'         => 'Wheels and Worth',
                'description'   => 'Buy a vehicle-category asset and grow your net worth past Ksh 8,000 in the same stretch.',
                'icon'          => '🚗',
                'xp_reward'     => 224,
                'kes_reward'    => 196,
                'level_required'=> 2,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'buy_item_category', 'values' => ['vehicle'], 'label' => 'Buy any vehicle-category asset'],
                    ['type' => 'reach_net_worth',    'values' => ['8000'],   'label' => 'Push your net worth past Ksh 8,000'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'A vehicle can be an asset or a liability depending entirely on whether it earns more than it costs you each month.',
                'sort_order'    => 14,
            ],

            // ═══════════════════════════════════════════════════════
            // LEVEL 3
            // ═══════════════════════════════════════════════════════
            [
                'title'         => 'Sharpen the Basics',
                'description'   => 'Complete Financial Literacy 101 — the fundamentals every adult should have learned in school but rarely did.',
                'icon'          => '📚',
                'xp_reward'     => 185,
                'kes_reward'    => 165,
                'level_required'=> 3,
                'trigger_type'  => 'take_course',
                'trigger_value' => 'financial-literacy-101',
                'trigger_label' => 'Complete Financial Literacy 101',
                'lesson'        => 'The gap between people who build wealth and people who do not is rarely intelligence — it is exposure to basic financial concepts.',
                'sort_order'    => 15,
            ],
            [
                'title'         => 'Back on the Job Market',
                'description'   => 'Land a job in Pesa City — a fresh income stream, or a better one than before.',
                'icon'          => '💼',
                'xp_reward'     => 195,
                'kes_reward'    => 175,
                'level_required'=> 3,
                'trigger_type'  => 'get_job',
                'trigger_value' => '',
                'trigger_label' => 'Get hired for any job',
                'lesson'        => 'Income is the raw material of every financial plan. Nothing else works without it.',
                'sort_order'    => 16,
            ],
            [
                'title'         => 'Ninety-One Days to Grow',
                'description'   => 'Buy into a 91-Day Treasury Bill — lend to the government, get paid a guaranteed rate.',
                'icon'          => '🏛️',
                'xp_reward'     => 200,
                'kes_reward'    => 180,
                'level_required'=> 3,
                'trigger_type'  => 'buy_item_slug',
                'trigger_value' => 'treasury-bills-91',
                'trigger_label' => 'Buy a 91-Day Treasury Bill',
                'lesson'        => 'T-Bills are about as close to risk-free as money gets — the trade-off is your cash is locked for the full term.',
                'sort_order'    => 17,
            ],
            [
                'title'         => 'Deposit, Then Defend',
                'description'   => 'Deposit at least Ksh 4,000 into savings, and keep your wallet balance above Ksh 9,000 at the same time.',
                'icon'          => '🛡️',
                'xp_reward'     => 266,
                'kes_reward'    => 238,
                'level_required'=> 3,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'deposit_savings', 'values' => ['4000'], 'label' => 'Deposit at least Ksh 4,000 into savings'],
                    ['type' => 'reach_balance',   'values' => ['9000'], 'label' => 'Keep your wallet above Ksh 9,000'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'Real financial security means growing your savings AND keeping cash on hand — one without the other leaves you exposed.',
                'sort_order'    => 18,
            ],
            [
                'title'         => 'Another Day, Another Decision',
                'description'   => 'Play through another Life Decision scenario — the choices only get more nuanced from here.',
                'icon'          => '🎭',
                'xp_reward'     => 188,
                'kes_reward'    => 168,
                'level_required'=> 3,
                'trigger_type'  => 'play_scenario',
                'trigger_value' => '',
                'trigger_label' => 'Play any Life Decision scenario',
                'lesson'        => 'Financial maturity is not making perfect choices — it is making slightly better ones than last time, consistently.',
                'sort_order'    => 19,
            ],
            [
                'title'         => 'Wheel of Adult Fortune',
                'description'   => "Spin the Lucky Wheel again — and prove last time wasn't a fluke.",
                'icon'          => '🎡',
                'xp_reward'     => 182,
                'kes_reward'    => 162,
                'level_required'=> 3,
                'trigger_type'  => 'spin_wheel',
                'trigger_value' => '',
                'trigger_label' => 'Spin the Lucky Wheel',
                'lesson'        => 'Consistency in how you treat windfalls, not the size of any one windfall, is what actually builds wealth.',
                'sort_order'    => 20,
            ],
            [
                'title'         => 'Portfolio and Position',
                'description'   => 'Buy another share and push your net worth past Ksh 12,000 — ownership and growth, together.',
                'icon'          => '📊',
                'xp_reward'     => 270,
                'kes_reward'    => 240,
                'level_required'=> 3,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'buy_share',      'values' => [],        'label' => 'Buy any share'],
                    ['type' => 'reach_net_worth', 'values' => ['12000'], 'label' => 'Push your net worth past Ksh 12,000'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'Net worth is the real scoreboard — not income, not savings alone, but everything you own minus everything you owe.',
                'sort_order'    => 21,
            ],
        ];

        foreach ($quests as $data) {
            Quest::updateOrCreate(
                ['title' => $data['title']],
                array_merge($data, ['is_active' => true, 'age_group' => '26+'])
            );
        }
    }
}
