<?php

namespace Database\Seeders;

use App\Models\Quest;
use Illuminate\Database\Seeder;

class QuestExpansion13to17Band3Seeder extends Seeder
{
    public function run(): void
    {
        $quests = [

            // ── Level 8 ──────────────────────────────────────────────────────
            [
                'title'         => 'Boda Fare Buffer',
                'description'   => 'Build a buffer big enough to cover a term of boda/matatu fares without touching your main savings.',
                'icon'          => '🛵',
                'xp_reward'     => 470,
                'kes_reward'    => 650,
                'level_required'=> 8,
                'trigger_type'  => 'reach_savings',
                'trigger_value' => '24000',
                'trigger_label' => 'Reach Ksh 24,000 in total savings',
                'lesson'        => 'A transport buffer means one matatu strike or fare hike never derails your week — small, boring funds prevent big, stressful problems.',
                'sort_order'    => 80,
            ],
            [
                'title'         => 'First Slice of the Market',
                'description'   => 'Buy your first share on the Pesa City exchange. You now own a piece of a real company, not just a wish.',
                'icon'          => '📊',
                'xp_reward'     => 430,
                'kes_reward'    => 580,
                'level_required'=> 8,
                'trigger_type'  => 'buy_share',
                'trigger_value' => '',
                'trigger_label' => 'Buy any share on the exchange',
                'lesson'        => 'Owning shares means owning a sliver of a business\'s profits and problems both — it is a different kind of money than a salary.',
                'sort_order'    => 81,
            ],
            [
                'title'         => 'Business Instinct',
                'description'   => 'Buy any business-category asset from the Marketplace — a real income-producing venture, not a toy.',
                'icon'          => '🏪',
                'xp_reward'     => 470,
                'kes_reward'    => 650,
                'level_required'=> 8,
                'trigger_type'  => 'buy_item_category',
                'trigger_value' => 'business',
                'trigger_label' => 'Buy any business asset',
                'lesson'        => 'A business asset can pay you back every month, unlike a gadget that only ever costs you money after the purchase.',
                'sort_order'    => 82,
            ],
            [
                'title'         => "Founders' Chama",
                'description'   => 'Join a chama. Pooling money with people you trust builds bigger goals faster than saving alone.',
                'icon'          => '🤝',
                'xp_reward'     => 500,
                'kes_reward'    => 700,
                'level_required'=> 8,
                'trigger_type'  => 'join_chama',
                'trigger_value' => null,
                'trigger_label' => 'Join a chama',
                'lesson'        => 'A chama works because the group notices if you skip a contribution — social pressure is a surprisingly powerful savings tool.',
                'sort_order'    => 83,
            ],
            [
                'title'         => 'Whispers From Rafiki',
                'description'   => 'Play through any life-decision scenario in the city — every choice teaches something, win or lose.',
                'icon'          => '💬',
                'xp_reward'     => 430,
                'kes_reward'    => 580,
                'level_required'=> 8,
                'trigger_type'  => 'play_scenario',
                'trigger_value' => '',
                'trigger_label' => 'Play any life-decision scenario',
                'lesson'        => 'Every scenario is a low-stakes rehearsal for a real decision you will eventually face with real money.',
                'sort_order'    => 84,
            ],
            [
                'title'         => 'Diversify Early',
                'description'   => 'Do not put all your eggs in one basket: buy a business asset AND buy a share in the same stretch.',
                'icon'          => '🧺',
                'xp_reward'     => 660,
                'kes_reward'    => 910,
                'level_required'=> 8,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'buy_item_category', 'values' => ['business'], 'label' => 'Buy any business asset'],
                    ['type' => 'buy_share',         'values' => [],           'label' => 'Buy any share'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'Spreading money across a business asset and a share means one bad month in either doesn\'t sink your whole plan.',
                'sort_order'    => 85,
            ],

            // ── Level 9 ──────────────────────────────────────────────────────
            [
                'title'         => 'Fixed Income Focus',
                'description'   => 'Buy into a Money Market Fund, Treasury Bill, or Treasury Bond — steady, government-backed growth.',
                'icon'          => '🏛️',
                'xp_reward'     => 550,
                'kes_reward'    => 800,
                'level_required'=> 9,
                'trigger_type'  => 'buy_item_category',
                'trigger_value' => 'fixed_income',
                'trigger_label' => 'Buy any fixed-income asset',
                'lesson'        => 'Fixed-income assets trade excitement for certainty — a smart trade once you have money you genuinely cannot afford to lose.',
                'sort_order'    => 90,
            ],
            [
                'title'         => 'First Steps Into Equity Square',
                'description'   => 'Put money into any investment deal at Equity Square. Real deals, real terms, real returns.',
                'icon'          => '🤝',
                'xp_reward'     => 520,
                'kes_reward'    => 750,
                'level_required'=> 9,
                'trigger_type'  => 'invest_deal',
                'trigger_value' => '',
                'trigger_label' => 'Invest in any Equity Square deal',
                'lesson'        => 'A deal with clear terms up front beats a vague promise every time — read what you\'re agreeing to before you commit cash.',
                'sort_order'    => 91,
            ],
            [
                'title'         => 'A Badge Worth Displaying',
                'description'   => 'Earn any badge in Pesa City — proof your habits are being noticed by more than just your own wallet.',
                'icon'          => '🏅',
                'xp_reward'     => 500,
                'kes_reward'    => 700,
                'level_required'=> 9,
                'trigger_type'  => 'earn_badge',
                'trigger_value' => '',
                'trigger_label' => 'Earn any badge',
                'lesson'        => 'Recognition is a side effect of good habits, not the goal — but it\'s a fair signal you\'re on the right track.',
                'sort_order'    => 92,
            ],
            [
                'title'         => 'Thirty Thousand Strong',
                'description'   => 'Grow your wallet balance to Ksh 30,000 — cash on hand, ready to deploy the moment the right opportunity shows up.',
                'icon'          => '💵',
                'xp_reward'     => 550,
                'kes_reward'    => 800,
                'level_required'=> 9,
                'trigger_type'  => 'reach_balance',
                'trigger_value' => '30000',
                'trigger_label' => 'Grow your wallet to Ksh 30,000',
                'lesson'        => 'Idle cash still has a job: being ready. The trick is not leaving it idle for too long once an opportunity is real.',
                'sort_order'    => 93,
            ],
            [
                'title'         => 'Second Story, Same Hustle',
                'description'   => 'Land a second job or gig in the city. Two income streams beat one, even if both are small.',
                'icon'          => '💼',
                'xp_reward'     => 600,
                'kes_reward'    => 850,
                'level_required'=> 9,
                'trigger_type'  => 'get_job',
                'trigger_value' => '',
                'trigger_label' => 'Get hired for a job',
                'lesson'        => 'Two smaller income streams are more resilient than one big one — if either dries up, you\'re not starting from zero.',
                'sort_order'    => 94,
            ],
            [
                'title'         => 'Almost There, Almost Rich',
                'description'   => 'Push your savings to Ksh 35,000 and play through a life scenario along the way — the road to the top level is paved with both.',
                'icon'          => '🛣️',
                'xp_reward'     => 770,
                'kes_reward'    => 1120,
                'level_required'=> 9,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'reach_savings',  'values' => ['35000'], 'label' => 'Reach Ksh 35,000 in total savings'],
                    ['type' => 'play_scenario',  'values' => [],        'label' => 'Play any life-decision scenario'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'Big financial goals are always a mix of discipline (saving) and judgement (decisions) — neither alone gets you there.',
                'sort_order'    => 95,
            ],

            // ── Level 10 ─────────────────────────────────────────────────────
            [
                'title'         => 'The Six-Figure Reach',
                'description'   => 'Push your net worth past Ksh 100,000 — six figures, earned one decision at a time.',
                'icon'          => '📈',
                'xp_reward'     => 650,
                'kes_reward'    => 1000,
                'level_required'=> 10,
                'trigger_type'  => 'reach_net_worth',
                'trigger_value' => '100000',
                'trigger_label' => 'Push your net worth past Ksh 100,000',
                'lesson'        => 'Net worth counts everything you own minus everything you owe — it grows quietly even on days you don\'t feel richer.',
                'sort_order'    => 100,
            ],
            [
                'title'         => 'Level Ten Ascension',
                'description'   => 'Keep climbing past level 10 toward Pesa City Legend status.',
                'icon'          => '⭐',
                'xp_reward'     => 700,
                'kes_reward'    => 1050,
                'level_required'=> 10,
                'trigger_type'  => 'reach_level',
                'trigger_value' => '11',
                'trigger_label' => 'Reach Level 11',
                'lesson'        => 'The top level isn\'t a finish line — it\'s proof you\'ve built habits that compound on their own.',
                'sort_order'    => 101,
            ],
            [
                'title'         => 'Vehicle Venture',
                'description'   => 'Buy a vehicle-category asset and play through a life scenario in the same stretch — wheels plus wisdom.',
                'icon'          => '🏍️',
                'xp_reward'     => 910,
                'kes_reward'    => 1400,
                'level_required'=> 10,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'buy_item_category', 'values' => ['vehicle'], 'label' => 'Buy any vehicle asset'],
                    ['type' => 'play_scenario',     'values' => [],          'label' => 'Play any life-decision scenario'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'A vehicle can be an income tool or a money pit depending entirely on whether you\'ve run the numbers first.',
                'sort_order'    => 102,
            ],
            [
                'title'         => 'Gadget for Growth',
                'description'   => 'Buy the DJI Mini drone — a gadget that pays for itself through weekend event gigs.',
                'icon'          => '🚁',
                'xp_reward'     => 650,
                'kes_reward'    => 1000,
                'level_required'=> 10,
                'trigger_type'  => 'buy_item_slug',
                'trigger_value' => 'drone-dji-mini',
                'trigger_label' => 'Buy the DJI Mini drone',
                'lesson'        => 'A skill-plus-gadget combo earns far more than the gadget alone — the tool is only as valuable as what you know to do with it.',
                'sort_order'    => 103,
            ],
            [
                'title'         => 'One Course, Big Payoff',
                'description'   => 'Complete Bookkeeping Basics — the one course every future business owner eventually needs.',
                'icon'          => '📒',
                'xp_reward'     => 650,
                'kes_reward'    => 1000,
                'level_required'=> 10,
                'trigger_type'  => 'take_course',
                'trigger_value' => 'bookkeeping-basics',
                'trigger_label' => 'Complete Bookkeeping Basics',
                'lesson'        => 'You cannot manage what you do not measure — bookkeeping turns "I think I made money" into "I know exactly how much."',
                'sort_order'    => 104,
            ],
            [
                'title'         => 'Capstone Circle',
                'description'   => 'Spend something in Fun World and still push your net worth past Ksh 120,000 — proof that balance beats deprivation.',
                'icon'          => '🎡',
                'xp_reward'     => 910,
                'kes_reward'    => 1400,
                'level_required'=> 10,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'fun_world_spend', 'values' => [],          'label' => 'Spend on any Fun World activity'],
                    ['type' => 'reach_net_worth', 'values' => ['120000'],  'label' => 'Push your net worth past Ksh 120,000'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'A budget that has zero room for fun rarely survives contact with real life — plan for joy, don\'t just ban it.',
                'sort_order'    => 105,
            ],
        ];

        foreach ($quests as $data) {
            Quest::updateOrCreate(
                ['title' => $data['title']],
                $data + ['is_active' => true, 'age_group' => '13-17']
            );
        }
    }
}
