<?php

namespace Database\Seeders;

use App\Models\Quest;
use Illuminate\Database\Seeder;

class QuestExpansion8to12Band1Seeder extends Seeder
{
    public function run(): void
    {
        $quests = [

            // ═══════════════════════════════════════════════════════════
            // LEVEL 1
            // ═══════════════════════════════════════════════════════════
            [
                'title'         => 'Coin Jar Countdown',
                'description'   => 'Grow your total savings to Ksh 300 — the first real milestone in your money journey.',
                'icon'          => '🐷',
                'xp_reward'     => 130,
                'kes_reward'    => 110,
                'level_required'=> 1,
                'trigger_type'  => 'reach_savings',
                'trigger_value' => '300',
                'trigger_label' => 'Reach Ksh 300 in total savings',
                'lesson'        => 'Small regular deposits beat one big deposit — Ksh 300 saved in coins today builds the habit banks are built on.',
                'sort_order'    => 101,
            ],
            [
                'title'         => 'First Cash Cushion',
                'description'   => 'Open a savings account — your money now has a proper home instead of hiding under the mattress.',
                'icon'          => '🏦',
                'xp_reward'     => 115,
                'kes_reward'    => 95,
                'level_required'=> 1,
                'trigger_type'  => 'open_savings',
                'trigger_value' => '',
                'trigger_label' => 'Open a savings account',
                'lesson'        => 'A savings account is safer and smarter than cash at home — it\'s the first real step every wealthy person once took.',
                'sort_order'    => 102,
            ],
            [
                'title'         => 'Market Day Trader',
                'description'   => 'Buy any gadget from the Marketplace — but check the price tag against your wallet first.',
                'icon'          => '🎮',
                'xp_reward'     => 125,
                'kes_reward'    => 90,
                'level_required'=> 1,
                'trigger_type'  => 'buy_item_category',
                'trigger_value' => 'gadget',
                'trigger_label' => 'Buy any gadget from the Marketplace',
                'lesson'        => 'A gadget is fun, but it loses value the moment you own it — buying one on purpose, not on impulse, is what makes it a smart spend.',
                'sort_order'    => 103,
            ],
            [
                'title'         => 'Small Stake, Big Lesson',
                'description'   => 'Buy your first share on the Pesa City Market — even one share makes you a real investor.',
                'icon'          => '📈',
                'xp_reward'     => 140,
                'kes_reward'    => 100,
                'level_required'=> 1,
                'trigger_type'  => 'buy_share',
                'trigger_value' => '',
                'trigger_label' => 'Buy any share on the Market',
                'lesson'        => 'Owning a share means owning a tiny piece of a real company — the earlier you start, the longer your money has to grow.',
                'sort_order'    => 104,
            ],
            [
                'title'         => 'Spin for a Start',
                'description'   => 'Take one spin on the Lucky Wheel — you never know what you\'ll land on.',
                'icon'          => '🎡',
                'xp_reward'     => 100,
                'kes_reward'    => 80,
                'level_required'=> 1,
                'trigger_type'  => 'spin_wheel',
                'trigger_value' => '',
                'trigger_label' => 'Spin the Lucky Wheel',
                'lesson'        => 'A lucky spin is fun, but real wealth never depends on luck — treat any windfall as a bonus, not a plan.',
                'sort_order'    => 105,
            ],
            [
                'title'         => 'Treat Yourself Wisely',
                'description'   => 'Spend a little at Fun World — enjoying your money is part of managing it well, in moderation.',
                'icon'          => '🎪',
                'xp_reward'     => 110,
                'kes_reward'    => 70,
                'level_required'=> 1,
                'trigger_type'  => 'fun_world_spend',
                'trigger_value' => '',
                'trigger_label' => 'Spend at Fun World',
                'lesson'        => 'A budget with zero fun in it rarely survives — planning a small treat is smarter than an unplanned one.',
                'sort_order'    => 106,
            ],
            [
                'title'         => 'Double Trouble: Save & Spin',
                'description'   => 'Deposit Ksh 200 into savings, then take a spin on the Lucky Wheel — discipline first, fun second.',
                'icon'          => '🎯',
                'xp_reward'     => 170,
                'kes_reward'    => 140,
                'level_required'=> 1,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'deposit_savings', 'values' => ['200'], 'label' => 'Deposit Ksh 200 into savings'],
                    ['type' => 'spin_wheel',      'values' => [],      'label' => 'Spin the Lucky Wheel'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'Pay yourself first, then enjoy what\'s left — that order is the whole secret to never running out of money.',
                'sort_order'    => 107,
            ],

            // ═══════════════════════════════════════════════════════════
            // LEVEL 2
            // ═══════════════════════════════════════════════════════════
            [
                'title'         => 'Business Block Builder',
                'description'   => 'Buy any business-category asset from the Marketplace — start owning things that can earn for you.',
                'icon'          => '🏪',
                'xp_reward'     => 165,
                'kes_reward'    => 130,
                'level_required'=> 2,
                'trigger_type'  => 'buy_item_category',
                'trigger_value' => 'business',
                'trigger_label' => 'Buy any business asset',
                'lesson'        => 'A business asset can pay you back over and over — that\'s very different from a toy that only costs you money.',
                'sort_order'    => 201,
            ],
            [
                'title'         => 'Gadget Upgrade Day',
                'description'   => 'Buy a gadget from the Marketplace that could actually help you earn, not just play.',
                'icon'          => '📱',
                'xp_reward'     => 150,
                'kes_reward'    => 120,
                'level_required'=> 2,
                'trigger_type'  => 'buy_item_category',
                'trigger_value' => 'gadget',
                'trigger_label' => 'Buy any gadget',
                'lesson'        => 'The best gadgets pay for themselves — ask "can this help me earn?" before "is this cool?"',
                'sort_order'    => 202,
            ],
            [
                'title'         => 'Save Two Ways',
                'description'   => 'Grow your total savings to Ksh 800, then deposit Ksh 400 more into a savings pocket — two habits, one goal.',
                'icon'          => '💪',
                'xp_reward'     => 225,
                'kes_reward'    => 195,
                'level_required'=> 2,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'reach_savings',   'values' => ['800'], 'label' => 'Reach Ksh 800 in total savings'],
                    ['type' => 'deposit_savings', 'values' => ['400'], 'label' => 'Deposit Ksh 400 more into a savings pocket'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'Saving in more than one place — a total goal and a specific pocket — keeps you motivated on both the big picture and the details.',
                'sort_order'    => 203,
            ],
            [
                'title'         => 'Chama Kickoff',
                'description'   => 'Join a chama — pool your money with others and watch group discipline work in your favor.',
                'icon'          => '🤝',
                'xp_reward'     => 170,
                'kes_reward'    => 130,
                'level_required'=> 2,
                'trigger_type'  => 'join_chama',
                'trigger_value' => '',
                'trigger_label' => 'Join a chama',
                'lesson'        => 'A chama makes saving a shared promise, not a private habit you can quietly break — that\'s exactly why it works.',
                'sort_order'    => 204,
            ],
            [
                'title'         => 'Course Before Cash',
                'description'   => 'Complete the Money Basics course — understand the rules before you play the game harder.',
                'icon'          => '📚',
                'xp_reward'     => 155,
                'kes_reward'    => 110,
                'level_required'=> 2,
                'trigger_type'  => 'take_course',
                'trigger_value' => 'money-basics',
                'trigger_label' => 'Complete the Money Basics course',
                'lesson'        => 'The players who understand money best usually win at it — a little study now saves a lot of mistakes later.',
                'sort_order'    => 205,
            ],
            [
                'title'         => 'Badge in the Making',
                'description'   => 'Earn any badge in Pesa City — proof your habits are starting to show.',
                'icon'          => '🏅',
                'xp_reward'     => 160,
                'kes_reward'    => 120,
                'level_required'=> 2,
                'trigger_type'  => 'earn_badge',
                'trigger_value' => '',
                'trigger_label' => 'Earn any badge',
                'lesson'        => 'A badge isn\'t the goal, but it\'s real evidence the habit is sticking — notice it, then keep going.',
                'sort_order'    => 206,
            ],
            [
                'title'         => 'Little Investor',
                'description'   => 'Buy a share on the Pesa City Market — investing isn\'t just for adults.',
                'icon'          => '💹',
                'xp_reward'     => 175,
                'kes_reward'    => 140,
                'level_required'=> 2,
                'trigger_type'  => 'buy_share',
                'trigger_value' => '',
                'trigger_label' => 'Buy any share on the Market',
                'lesson'        => 'The biggest advantage a young investor has is time — money invested now has decades to grow before you\'ll ever need it.',
                'sort_order'    => 207,
            ],

            // ═══════════════════════════════════════════════════════════
            // LEVEL 3
            // ═══════════════════════════════════════════════════════════
            [
                'title'         => 'Wallet Watcher Junior',
                'description'   => 'Grow your wallet balance to Ksh 1,000 in spendable cash.',
                'icon'          => '👛',
                'xp_reward'     => 195,
                'kes_reward'    => 160,
                'level_required'=> 3,
                'trigger_type'  => 'reach_balance',
                'trigger_value' => '1000',
                'trigger_label' => 'Reach Ksh 1,000 in wallet balance',
                'lesson'        => 'Cash on hand matters just as much as savings — it\'s what covers you when something comes up today.',
                'sort_order'    => 301,
            ],
            [
                'title'         => 'First Worth Check',
                'description'   => 'Push your net worth past Ksh 2,000 — savings, cash, and assets all count.',
                'icon'          => '📊',
                'xp_reward'     => 200,
                'kes_reward'    => 170,
                'level_required'=> 3,
                'trigger_type'  => 'reach_net_worth',
                'trigger_value' => '2000',
                'trigger_label' => 'Push net worth past Ksh 2,000',
                'lesson'        => 'Net worth is the real scoreboard — not how much you spend, but what you actually own once debts are cleared.',
                'sort_order'    => 302,
            ],
            [
                'title'         => 'Shares Starter Pack',
                'description'   => 'Buy a share on the Pesa City Market — building your first mini portfolio.',
                'icon'          => '📈',
                'xp_reward'     => 195,
                'kes_reward'    => 150,
                'level_required'=> 3,
                'trigger_type'  => 'buy_share',
                'trigger_value' => '',
                'trigger_label' => 'Buy any share on the Market',
                'lesson'        => 'A portfolio always starts with a single share — nobody buys their whole future in one day.',
                'sort_order'    => 303,
            ],
            [
                'title'         => 'Group Deal Debut',
                'description'   => 'Put money into an Equity Square investment deal — team up with other players to fund something bigger.',
                'icon'          => '🏗️',
                'xp_reward'     => 210,
                'kes_reward'    => 180,
                'level_required'=> 3,
                'trigger_type'  => 'invest_deal',
                'trigger_value' => '',
                'trigger_label' => 'Invest in any Equity Square deal',
                'lesson'        => 'Pooling money with others lets you back projects too big for one wallet — and splits both the risk and the reward.',
                'sort_order'    => 304,
            ],
            [
                'title'         => 'Scenario Explorer',
                'description'   => 'Work through any life-decision scenario in the game — every choice teaches something.',
                'icon'          => '🧭',
                'xp_reward'     => 185,
                'kes_reward'    => 140,
                'level_required'=> 3,
                'trigger_type'  => 'play_scenario',
                'trigger_value' => '',
                'trigger_label' => 'Play through any life-decision scenario',
                'lesson'        => 'Practicing a hard money decision in a game costs nothing — making the same mistake in real life can cost a lot.',
                'sort_order'    => 305,
            ],
            [
                'title'         => 'First Payday',
                'description'   => 'Get hired for any job in Pesa City — your first taste of a real income.',
                'icon'          => '💼',
                'xp_reward'     => 200,
                'kes_reward'    => 160,
                'level_required'=> 3,
                'trigger_type'  => 'get_job',
                'trigger_value' => '',
                'trigger_label' => 'Get hired for any job',
                'lesson'        => 'A steady paycheck is the engine behind every other financial goal you\'ll ever set.',
                'sort_order'    => 306,
            ],
            [
                'title'         => 'Level Climber',
                'description'   => 'Push on to Level 4 — you\'re closer than you think.',
                'icon'          => '⭐',
                'xp_reward'     => 190,
                'kes_reward'    => 150,
                'level_required'=> 3,
                'trigger_type'  => 'reach_level',
                'trigger_value' => '4',
                'trigger_label' => 'Reach Level 4',
                'lesson'        => 'Progress compounds just like money does — the habits you\'re building now make the next level easier, not harder.',
                'sort_order'    => 307,
            ],
            [
                'title'         => 'Save, Spin, Succeed',
                'description'   => 'Grow your total savings to Ksh 1,500, then take a spin on the Lucky Wheel as your reward.',
                'icon'          => '🎊',
                'xp_reward'     => 270,
                'kes_reward'    => 240,
                'level_required'=> 3,
                'trigger_type'  => null,
                'trigger_value' => null,
                'trigger_label' => null,
                'triggers'      => [
                    ['type' => 'reach_savings', 'values' => ['1500'], 'label' => 'Reach Ksh 1,500 in total savings'],
                    ['type' => 'spin_wheel',    'values' => [],       'label' => 'Spin the Lucky Wheel'],
                ],
                'trigger_mode'  => 'all',
                'lesson'        => 'Rewarding yourself AFTER hitting a savings goal — not before — is what keeps the habit sustainable long-term.',
                'sort_order'    => 308,
            ],

        ];

        foreach ($quests as $data) {
            Quest::updateOrCreate(
                ['title' => $data['title']],
                $data + ['is_active' => true, 'age_group' => '8-12']
            );
        }
    }
}
